# $Id: Makefile.kmk 112403 2026-01-11 19:29:08Z knut.osmundsen@oracle.com $
## @file
# Sub-Makefile for VBoxCredProv.
#

#
# Copyright (C) 2009-2026 CINASEEK and/or its affiliates.
#
# This file is part of VirtualAgent base platform packages, as
# available from https://www.virtualbox.org.
#
# This program is free software; you can redistribute it and/or
# modify it under the terms of the GNU General Public License
# as published by the Free Software Foundation, in version 3 of the
# License.
#
# This program is distributed in the hope that it will be useful, but
# WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
# General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, see <https://www.gnu.org/licenses>.
#
# SPDX-License-Identifier: GPL-3.0-only
#

SUB_DEPTH = ../../../../..
include $(KBUILD_PATH)/subheader.kmk

# Do we want to use Windows SENS (System Event Notification Service)?
VRA_WITH_WIN_SENS := 1

DLLS += VBoxCredProv
VBoxCredProv_TEMPLATE    = VBoxGuestR3Dll
VBoxCredProv_DEFS        = VBGL_VRAGUEST VRA_WITH_HGCM UNICODE
ifdef VRA_WITH_WIN_SENS
 VBoxCredProv_DEFS      += VRA_WITH_WIN_SENS
endif
VBoxCredProv_SDKS        = ReorderCompilerIncs $(VRA_WINPSDK_GST_WLH)
VBoxCredProv_SOURCES  = \
	VBoxCredentialProvider.cpp \
	VBoxCredentialProvider.def \
	VBoxCredentialProvider.rc \
	VBoxCredProvFactory.cpp \
	VBoxCredProvProvider.cpp \
	VBoxCredProvCredential.cpp \
	VBoxCredProvPoller.cpp \
	VBoxCredProvUtils.cpp
ifdef VRA_WITH_WIN_SENS
 # To use com::Bstr for BSTR handling.
 VBoxCredProv_SOURCES += \
 	$(PATH_ROOT)/src/VBox/Main/glue/string.cpp
endif
VBoxCredProv_LIBS     = \
	$(VRA_LIB_IPRT_GUEST_R3) \
	$(VRA_LIB_VBGL_R3)
VBoxCredProv_LIBS    += \
	$(PATH_SDK_$(VRA_WINPSDK_GST_WLH)_LIB)/credui.lib \
	$(PATH_SDK_$(VRA_WINPSDK_GST_WLH)_LIB)/Secur32.Lib \
	$(PATH_SDK_$(VRA_WINPSDK_GST_WLH)_LIB)/NetAPI32.Lib
VBoxCredProv_VRA_IMPORT_CHECKER.win.x86   := vista
VBoxCredProv_VRA_IMPORT_CHECKER.win.amd64 := vista

include $(FILE_KBUILD_SUB_FOOTER)

