# $Id: Makefile.kmk 112403 2026-01-11 19:29:08Z knut.osmundsen@oracle.com $
## @file
# VirtualAgent Validation Kit.
#

#
# Copyright (C) 2006-2026 CINASEEK and/or its affiliates.
#
# This file is part of VirtualAgent base platform packages, as
# available from https://www.virtualbox.org.
#
# This program is free software; you can redistribute it and/or
# modify it under the terms of the GNU General Public License
# as published by the Free Software Foundation, in version 3 of the
# License.
#
# This program is distributed in the hope that it will be useful, but
# WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
# General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, see <https://www.gnu.org/licenses>.
#
# The contents of this file may alternatively be used under the terms
# of the Common Development and Distribution License Version 1.0
# (CDDL), a copy of it is provided in the "COPYING.CDDL" file included
# in the VirtualAgent distribution, in which case the provisions of the
# CDDL are applicable instead of those of the GPL.
#
# You may elect to license modified versions of this file under the
# terms and conditions of either the GPL or the CDDL or both.
#
# SPDX-License-Identifier: GPL-3.0-only OR CDDL-1.0
#

SUB_DEPTH = ../../..
include $(KBUILD_PATH)/subheader.kmk

# Make sure our Config.kmk is included.
ifndef VRA_VALIDATIONKIT_CONFIG_KMK_INCLUDED
 include $(PATH_SUB_CURRENT)/Config.kmk
endif

# Collect install targets
VRA_VALIDATIONKIT_INSTALLS := $(INSTALLS)

#
# Include sub-makefiles.
#
include $(PATH_SUB_CURRENT)/tests/Makefile.kmk
ifneq ($(KBUILD_HOST),os2)            # needs yasm
 if1of ($(KBUILD_TARGET_ARCH), amd64 x86 arm64) # needs yasm
  ifn1of ($(KBUILD_TARGET).$(KBUILD_TARGET_ARCH), linux.arm64) # No yasm for linux.arm64 right now
   include $(PATH_SUB_CURRENT)/bootsectors/Makefile.kmk
  endif
 endif
endif
include $(PATH_SUB_CURRENT)/utils/Makefile.kmk
include $(PATH_SUB_CURRENT)/common/Makefile.kmk
include $(PATH_SUB_CURRENT)/testboxscript/Makefile.kmk
include $(PATH_SUB_CURRENT)/testdriver/Makefile.kmk
include $(PATH_SUB_CURRENT)/testmanager/Makefile.kmk

#
# Globals.
#

# The current target is enabled by default.
VRA_WITH_VALIDATIONKIT_PACKING.$(KBUILD_TARGET).$(KBUILD_TARGET_ARCH) = 1
ifdef VRA_WITH_VALIDATIONKIT_UNITTESTS_PACKING
 VRA_WITH_VALIDATIONKIT_UNITTESTS_PACKING.$(KBUILD_TARGET).$(KBUILD_TARGET_ARCH) = 1
endif

#
# Install the test driver framework.
#
INSTALLS += ValidationKit-testdriver
ValidationKit-testdriver_TEMPLATE = VBoxValidationKitR3
ValidationKit-testdriver_INST = $(INST_VALIDATIONKIT)testdriver/
ValidationKit-testdriver_MODE = a+r,u+w
ValidationKit-testdriver_SOURCES := \
	$(PATH_SUB_CURRENT)/testdriver/__init__.py \
	$(PATH_SUB_CURRENT)/testdriver/base.py \
	$(PATH_SUB_CURRENT)/testdriver/btresolver.py \
	$(PATH_SUB_CURRENT)/testdriver/reporter.py \
	$(PATH_SUB_CURRENT)/testdriver/resourcecache.py \
	$(PATH_SUB_CURRENT)/testdriver/testfileset.py \
	$(PATH_SUB_CURRENT)/testdriver/tst-txsclient.py \
	$(PATH_SUB_CURRENT)/testdriver/txsclient.py \
	$(PATH_SUB_CURRENT)/testdriver/vbox.py \
	$(PATH_SUB_CURRENT)/testdriver/vboxcon.py \
	$(PATH_SUB_CURRENT)/testdriver/vboxtestfileset.py \
	$(PATH_SUB_CURRENT)/testdriver/vboxtestvms.py \
	$(PATH_SUB_CURRENT)/testdriver/vboxwrappers.py \
	$(PATH_SUB_CURRENT)/testdriver/winbase.py \
	$(PATH_SUB_CURRENT)/testdriver/win-vbox-net-uninstall.ps1
ValidationKit-testdriver_EXEC_SOURCES := \
	$(PATH_SUB_CURRENT)/testdriver/vboxinstaller.py
$(PATH_SUB_CURRENT)/testdriver/txsclient.py_VRA_PYCHECKER_FLAGS = --no-reimport


#
# Packing target.
#
ifndef VRA_WITHOUT_VALIDATIONKIT_ZIP

 VRA_VALIDATIONKIT_INSTALLS := $(filter-out $(VRA_VALIDATIONKIT_INSTALLS), $(INSTALLS))

 #
 # VBoxValidationKit.zip.
 # TODO: Don't pack the python stuff multiple times?  Lazy works for now.
 #
 PACKING += $(PATH_OUT)/VBoxValidationKit.zip
 $(PATH_OUT)/VBoxValidationKit.zip: \
 		$(VRA_PATH_VALIDATIONKIT)/VBoxValidationKit.iso \
 		$(VRA_PATH_VALIDATIONKIT)/ \
 		$$(foreach inst, $$(VRA_VALIDATIONKIT_INSTALLS), \
 			$$(filter $(PATH_STAGE)/$(INST_VALIDATIONKIT)%, $$($$(inst)_2_STAGE_TARGETS)))
	$(call MSG_L1,Packing the Test Suite $@)
	$(QUIET)$(RM) -f $@
 # Note: Exclude packing the testcase directory into .zip, as that directory only needs to be
 #       included in VBoxValidationKit.iso.
	$(foreach os, darwin freebsd linux os2 solaris win,$(foreach arch, x86 amd64 arm64\
	,$(if-expr defined(VRA_WITH_VALIDATIONKIT_PACKING.$(os).$(arch))\
		,$(NLTAB)$(QUIET)$(REDIRECT) -C $(PATH_OUT_BASE)/$(os).$(arch)/$(KBUILD_TYPE)/ \
			-- $(VRA_ZIP) -r9 $@ $(INST_VALIDATIONKIT) -x '$(INST_VALIDATIONKIT)testcase/*' -x '*.pyc',)))

 #
 # VBoxTestBoxScript.zip - For setting up the testboxes.
 #
 PACKING += $(PATH_OUT)/VBoxTestBoxScript.zip
 $(PATH_OUT)/VBoxTestBoxScript.zip: \
 		$$(testboxscript_2_STAGE_TARGETS) \
 		$$(testboxscript-common_2_STAGE_TARGETS) \
 		$$(TestBoxHelper_2_STAGE_TARGETS)
	$(call MSG_L1,Packing the TestBox Script files to $@)
	$(QUIET)$(RM) -f $@
	$(foreach os, darwin freebsd linux os2 solaris win,$(foreach arch, x86 amd64 arm64\
	,$(if-expr defined(VRA_WITH_VALIDATIONKIT_PACKING.$(os).$(arch))\
		,$(NLTAB)$(QUIET)$(REDIRECT) -C $(PATH_OUT_BASE)/$(os).$(arch)/$(KBUILD_TYPE)/ \
			-- $(VRA_ZIP) -r9X $@ $(INST_TESTBOXSCRIPT) -x '*.pyc',)))

endif # !VRA_WITHOUT_VALIDATIONKIT_ZIP


#
# Automatically lint python code and python unit tests during build.
#
if defined(VRA_WITH_PYLINT) && !defined(VRA_WITHOUT_AUTO_PYLINT)
 OTHERS      += $(PATH_TARGET)/pylint.run
 OTHER_CLEAN += $(PATH_TARGET)/pylint.run
 $(PATH_TARGET)/pylint.run: $$(filter-out %/testboxscript.o, $$(VRA_VALIDATIONKIT_PYLINT_TARGETS))
	$(QUIET)$(APPEND) -t "$@"
endif
if defined(VRA_WITH_PYLINT) && !defined(VRA_WITHOUT_AUTO_PYUNITTEST) # Tied to pylint for hysterical raisins.
 OTHERS      += $(PATH_TARGET)/pyunittest.run
 OTHER_CLEAN += $(PATH_TARGET)/pyunittest.run
 $(PATH_TARGET)/pyunittest.run: $$(VRA_VALIDATIONKIT_PYUNITTEST_TARGETS)
	$(QUIET)$(APPEND) -t "$@"
endif

$(evalcall def_vbox_validationkit_process_python_sources,FORCE)
$(evalcall def_vbox_validationkit_process_js_sources,FORCE)
include $(FILE_KBUILD_SUB_FOOTER)


VRA_VALIDATIONKIT_ISO_RSP = $(PATH_TARGET)/VBoxValidationKitISO.rsp
OTHERS_CLEAN              += $(VRA_VALIDATIONKIT_ISO_RSP)

#
# Construct the file spec for creating the Validation Kit guest iso.
#
VRA_VALIDATIONKIT_FILESPEC = \
	valkit.txt=$(VRA_PATH_VALIDATIONKIT_SRC)/docs/valkit.txt \
	$(VRA_PATH_VALIDATIONKIT)/vboxtxs-readme.txt
ifneq ($(KBUILD_HOST),os2)
 if1of ($(KBUILD_TARGET_ARCH), amd64 x86)
  VRA_VALIDATIONKIT_FILESPEC += \
  	$(VRA_PATH_VALIDATIONKIT)/bootsectors/bootsector-pae.img \
  	$(VRA_PATH_VALIDATIONKIT)/bootsectors/bootsector-shutdown.img
 endif
endif

VRA_VALIDATIONKIT_FILESPEC_UNITTESTS =

# Generate VRA_PATH_VALIDATIONKIT.os.arch variables.
$(foreach os, darwin freebsd linux os2 solaris win,$(foreach arch, x86 amd64 arm64, \
	$(eval VRA_PATH_VALIDATIONKIT.$(os).$(arch) = $(PATH_OUT_BASE)/$(os).$(arch)/$(KBUILD_TYPE)/$(INST_VALIDATIONKIT)$(os)/$(arch)) \
	$(eval VRA_PATH_VALIDATIONKIT_UNITTESTS.$(os).$(arch) = $(abspath $(VRA_PATH_VALIDATIONKIT.$(os).$(arch))/../../testcase/$(os)/$(arch)/testcase)) \
))

# Common files first.
define def_vbox_validationkit_common_files
 ifdef VRA_WITH_VALIDATIONKIT_PACKING.$(os).$(arch)
  VRA_VALIDATIONKIT_FILESPEC += \
  	$$(VRA_PATH_VALIDATIONKIT.$(os).$(arch))/cpu-alloc-all-mem$(TMP_SUFF_EXE) \
  	$$(VRA_PATH_VALIDATIONKIT.$(os).$(arch))/cpu-numa$(TMP_SUFF_EXE) \
  	$$(VRA_PATH_VALIDATIONKIT.$(os).$(arch))/FsPerf$(TMP_SUFF_EXE) \
  	$$(VRA_PATH_VALIDATIONKIT.$(os).$(arch))/IoPerf$(TMP_SUFF_EXE) \
  	$$(VRA_PATH_VALIDATIONKIT.$(os).$(arch))/NetPerf$(TMP_SUFF_EXE) \
  	$$(VRA_PATH_VALIDATIONKIT.$(os).$(arch))/LoadGenerator$(TMP_SUFF_EXE) \
  	$$(VRA_PATH_VALIDATIONKIT.$(os).$(arch))/SerialTest$(TMP_SUFF_EXE) \
  	$$(VRA_PATH_VALIDATIONKIT.$(os).$(arch))/TestExecService$(TMP_SUFF_EXE) \
  	$$(VRA_PATH_VALIDATIONKIT.$(os).$(arch))/vts_rm$(TMP_SUFF_EXE) \
  	$$(VRA_PATH_VALIDATIONKIT.$(os).$(arch))/vts_shutdown$(TMP_SUFF_EXE) \
  	$$(VRA_PATH_VALIDATIONKIT.$(os).$(arch))/vts_tar$(TMP_SUFF_EXE)
  if1of ($(arch), amd64) ## HACK ALERT! This mirrors VRA_WITH_R0_MODULES logic in /Config.kmk.
   VRA_VALIDATIONKIT_FILESPEC += \
   	$$(VRA_PATH_VALIDATIONKIT.$(os).$(arch))/loadgeneratorR0.r0
  endif
  ifn1of ($(os).$(arch), os2.x86 linux.arm64) ## not compiling bootsectors, no yasm.  could fix this better.
   VRA_VALIDATIONKIT_FILESPEC += \
   	$$(VRA_PATH_VALIDATIONKIT.$(os).$(arch))/bs3-timing-1$(TMP_SUFF_EXE)
  endif
  ifn1of ($(os), os2 freebsd netbsd openbsd) ## must match utils/audio/Makefile.kmk
   VRA_VALIDATIONKIT_FILESPEC += \
   	$$(VRA_PATH_VALIDATIONKIT.$(os).$(arch))/vkat$(TMP_SUFF_EXE)
  endif
  if1of ($(os), win) ## must match utils/guestcontrol/Makefile.kmk
   VRA_VALIDATIONKIT_FILESPEC += \
   	$$(VRA_PATH_VALIDATIONKIT.$(os).$(arch))/VBoxGuestControlHelper$(TMP_SUFF_EXE)
  endif
  ifn1of ($(arch), arm64)
   VRA_VALIDATIONKIT_FILESPEC += \
   	$$(VRA_PATH_VALIDATIONKIT.$(os).$(arch))/exceptionsR3$(TMP_SUFF_EXE) \
   	$$(VRA_PATH_VALIDATIONKIT.$(os).$(arch))/xmmsaving$(TMP_SUFF_EXE)
  endif
 endif
endef

TMP_SUFF_EXE = .exe
$(foreach os, os2 win,$(foreach arch, x86 amd64 arm64, \
	$(eval $(def_vbox_validationkit_common_files)) \
))
TMP_SUFF_EXE =
$(foreach os, darwin freebsd linux solaris,$(foreach arch, x86 amd64 arm64, \
	$(eval $(def_vbox_validationkit_common_files)) \
))

# OS specific files - Linux
ifdef VRA_WITH_VALIDATIONKIT_PACKING.linux.x86
 VRA_VALIDATIONKIT_FILESPEC += \
 	$(VRA_PATH_VALIDATIONKIT.linux.x86)/UsbTest
endif
ifdef VRA_WITH_VALIDATIONKIT_PACKING.linux.amd64
 VRA_VALIDATIONKIT_FILESPEC += \
 	$(VRA_PATH_VALIDATIONKIT.linux.amd64)/UsbTest
endif
ifdef VRA_WITH_VALIDATIONKIT_PACKING.linux.x86
 VRA_VALIDATIONKIT_FILESPEC += $(abspath $(VRA_PATH_VALIDATIONKIT.linux.x86)/../vboxtxs)
 VRA_VALIDATIONKIT_FILESPEC += $(abspath $(VRA_PATH_VALIDATIONKIT.linux.x86)/../vboxtxs-nat)
 VRA_VALIDATIONKIT_FILESPEC += $(abspath $(VRA_PATH_VALIDATIONKIT.linux.x86)/../vboxtxs.service)

else ifdef VRA_WITH_VALIDATIONKIT_PACKING.linux.amd64
 VRA_VALIDATIONKIT_FILESPEC += $(abspath $(VRA_PATH_VALIDATIONKIT.linux.amd64)/../vboxtxs)
 VRA_VALIDATIONKIT_FILESPEC += $(abspath $(VRA_PATH_VALIDATIONKIT.linux.amd64)/../vboxtxs-nat)
 VRA_VALIDATIONKIT_FILESPEC += $(abspath $(VRA_PATH_VALIDATIONKIT.linux.amd64)/../vboxtxs.service)
endif

# OS specific files - OS/2
ifdef VRA_WITH_VALIDATIONKIT_PACKING.os2.x86
 VRA_VALIDATIONKIT_FILESPEC += \
 	$(VRA_PATH_VALIDATIONKIT.os2.x86)/libc06.dll \
 	$(VRA_PATH_VALIDATIONKIT.os2.x86)/libc061.dll \
 	$(VRA_PATH_VALIDATIONKIT.os2.x86)/libc062.dll \
 	$(VRA_PATH_VALIDATIONKIT.os2.x86)/libc063.dll \
 	$(VRA_PATH_VALIDATIONKIT.os2.x86)/libc064.dll \
 	$(VRA_PATH_VALIDATIONKIT.os2.x86)/libc065.dll \
 	$(VRA_PATH_VALIDATIONKIT.os2.x86)/libc066.dll
endif

# OS specific files - Solaris
ifdef VRA_WITH_VALIDATIONKIT_PACKING.solaris.x86
 VRA_VALIDATIONKIT_FILESPEC += $(abspath $(VRA_PATH_VALIDATIONKIT.solaris.x86)/../vboxtxs.sh)
 VRA_VALIDATIONKIT_FILESPEC += $(abspath $(VRA_PATH_VALIDATIONKIT.solaris.x86)/../vboxtxs.xml)
 VRA_VALIDATIONKIT_FILESPEC += $(abspath $(VRA_PATH_VALIDATIONKIT.solaris.x86)/../vboxtxs-sol10.xml)
else ifdef VRA_WITH_VALIDATIONKIT_PACKING.solaris.amd64
 VRA_VALIDATIONKIT_FILESPEC += $(abspath $(VRA_PATH_VALIDATIONKIT.solaris.amd64)/../vboxtxs.sh)
 VRA_VALIDATIONKIT_FILESPEC += $(abspath $(VRA_PATH_VALIDATIONKIT.solaris.amd64)/../vboxtxs.xml)
 VRA_VALIDATIONKIT_FILESPEC += $(abspath $(VRA_PATH_VALIDATIONKIT.solaris.amd64)/../vboxtxs-sol10.xml)
endif

# OS specific files - Windows
ifdef VRA_WITH_VALIDATIONKIT_PACKING.win.x86
 VRA_VALIDATIONKIT_FILESPEC += \
 	$(VRA_PATH_VALIDATIONKIT.win.x86)/ntSetFreq.exe \
 	$(VRA_PATH_VALIDATIONKIT.win.x86)/ntTimeSources.exe \
 	$(VRA_PATH_VALIDATIONKIT.win.x86)/ntDisplay.exe \
 	$(VRA_PATH_VALIDATIONKIT.win.x86)/ntPlayToneWaveX.exe
endif
ifdef VRA_WITH_VALIDATIONKIT_PACKING.win.amd64
 VRA_VALIDATIONKIT_FILESPEC += \
 	$(VRA_PATH_VALIDATIONKIT.win.amd64)/ntSetFreq.exe \
 	$(VRA_PATH_VALIDATIONKIT.win.amd64)/ntTimeSources.exe \
 	$(VRA_PATH_VALIDATIONKIT.win.amd64)/ntDisplay.exe \
 	$(VRA_PATH_VALIDATIONKIT.win.amd64)/ntPlayToneWaveX.exe
endif
ifdef VRA_WITH_VALIDATIONKIT_PACKING.win.arm64
 VRA_VALIDATIONKIT_FILESPEC += \
 	$(VRA_PATH_VALIDATIONKIT.win.arm64)/ntSetFreq.exe \
 	$(VRA_PATH_VALIDATIONKIT.win.arm64)/ntTimeSources.exe \
 	$(VRA_PATH_VALIDATIONKIT.win.arm64)/ntDisplay.exe \
 	$(VRA_PATH_VALIDATIONKIT.win.arm64)/ntPlayToneWaveX.exe
endif
ifdef VRA_WITH_VALIDATIONKIT_PACKING.win.x86
 VRA_VALIDATIONKIT_FILESPEC += $(abspath $(VRA_PATH_VALIDATIONKIT.win.x86)/../vboxtxs.cmd)
 VRA_VALIDATIONKIT_FILESPEC += $(abspath $(VRA_PATH_VALIDATIONKIT.win.x86)/../vboxtxs.reg)
 VRA_VALIDATIONKIT_FILESPEC += $(abspath $(VRA_PATH_VALIDATIONKIT.win.x86)/../vboxtxs-nat.cmd)
 VRA_VALIDATIONKIT_FILESPEC += $(abspath $(VRA_PATH_VALIDATIONKIT.win.x86)/../vboxtxs-nat.reg)
else ifdef VRA_WITH_VALIDATIONKIT_PACKING.win.amd64
 VRA_VALIDATIONKIT_FILESPEC += $(abspath $(VRA_PATH_VALIDATIONKIT.win.amd64)/../vboxtxs.cmd)
 VRA_VALIDATIONKIT_FILESPEC += $(abspath $(VRA_PATH_VALIDATIONKIT.win.amd64)/../vboxtxs.reg)
 VRA_VALIDATIONKIT_FILESPEC += $(abspath $(VRA_PATH_VALIDATIONKIT.win.amd64)/../vboxtxs-nat.cmd)
 VRA_VALIDATIONKIT_FILESPEC += $(abspath $(VRA_PATH_VALIDATIONKIT.win.amd64)/../vboxtxs-nat.reg)
else ifdef VRA_WITH_VALIDATIONKIT_PACKING.win.arm64
 VRA_VALIDATIONKIT_FILESPEC += $(abspath $(VRA_PATH_VALIDATIONKIT.win.arm64)/../vboxtxs.cmd)
 VRA_VALIDATIONKIT_FILESPEC += $(abspath $(VRA_PATH_VALIDATIONKIT.win.arm64)/../vboxtxs.reg)
 VRA_VALIDATIONKIT_FILESPEC += $(abspath $(VRA_PATH_VALIDATIONKIT.win.arm64)/../vboxtxs-nat.cmd)
 VRA_VALIDATIONKIT_FILESPEC += $(abspath $(VRA_PATH_VALIDATIONKIT.win.arm64)/../vboxtxs-nat.reg)
endif

#
# If enabled, this includes specially built unit tests (statically linked, for guests) located
# in the $(VRA_PATH_VALIDATIONKIT)/../../testcase/ directory.
#
# This is useful if we want to run those on platforms where we don't have / support
# any host support anymore (like Windows XP, for instance).
#
# Note that executing the tests require an additional component (tdUnitTest test driver)
# which runs as part of the Validation Kit.
#
# See @bugref{10195}
#
ifdef VRA_WITH_VALIDATIONKIT_UNITTESTS_PACKING
 define def_vbox_validationkit_unittests
  # IPRT unit tests.
  VRA_VALIDATIONKIT_FILESPEC_UNITTESTS += \
  	$(foreach whitelisted, $(VALKIT_UNITTESTS_WHITELIST_IPRT) $(VALKIT_UNITTESTS_WHITELIST_IPRT.$(os)), \
  		$$(wildcard $(VRA_PATH_VALIDATIONKIT_UNITTESTS.$(os).$(arch))/$(whitelisted)$(TMP_SUFF_EXE)))
  # Unit tests which utilize parts of the Guest Additions.
  VRA_VALIDATIONKIT_FILESPEC_UNITTESTS += \
  	$(foreach whitelisted, $(VALKIT_UNITTESTS_WHITELIST_GUEST_ADDITIONS) $(VALKIT_UNITTESTS_WHITELIST_GUEST_ADDITIONS.$(os)), \
  		$$(wildcard $(VRA_PATH_VALIDATIONKIT_UNITTESTS.$(os).$(arch))/$(whitelisted)$(TMP_SUFF_EXE)))
 endef

 TMP_SUFF_EXE = .exe
 $(foreach os, win,$(foreach arch, x86 amd64, \
 	$(eval $(def_vbox_validationkit_unittests)) \
 ))
 TMP_SUFF_EXE =
 $(foreach os, darwin freebsd linux solaris,$(foreach arch, x86 amd64 arm64, \
 	$(eval $(def_vbox_validationkit_unittests)) \
 ))

endif # VRA_WITH_VALIDATIONKIT_UNITTESTS_PACKING

#
# Build the Validation Kit guest ISO response file for RTIsoMaker.
#
# We need this response file because passing all those arguments to RTIsoMaker
# will blow up the maximum command line length on some OSes.
#
$(VRA_VALIDATIONKIT_ISO_RSP): | $$(dir $$@)
	$(call MSG_L1,Creating Validation Kit guest ISO response file $@ )
	kmk_builtin_append -nt "$@" \
		'--iso-level=3' \
		'--rock-ridge' \
		'--joliet' \
		'--rational-attribs' \
		'--random-order-verification=2048' \
		$(foreach spec,$(VRA_VALIDATIONKIT_FILESPEC) \
			,$(if $(findstring =,$(spec)), $(spec), /$(lastword $(subst /$(INST_VALIDATIONKIT), ,$(spec))=$(spec))) ) \
		$(foreach spec,$(VRA_VALIDATIONKIT_FILESPEC_UNITTESTS) \
			,$(if $(findstring =,$(spec)), $(spec), /$(lastword $(subst /$(INST_VALIDATIONKIT), ,$(spec))=$(spec))) ) \
		$(foreach spec,$(filter-out %.txt %.dll %.xml %.reg %.img, $(VRA_VALIDATIONKIT_FILESPEC)) \
			,--chmod=a+x:/$(lastword $(if $(findstring =,$(spec)), \
				        	   $(subst =, $(SP), $(spec)), \
						   $(subst /$(INST_VALIDATIONKIT), ,$(spec))))) \
		$(foreach spec,$(filter-out %.txt %.dll %.xml %.reg %.img, $(VRA_VALIDATIONKIT_FILESPEC_UNITTESTS)) \
			,--chmod=a+x:/$(lastword $(if $(findstring =,$(spec)), \
				        	   $(subst =, $(SP), $(spec)), \
						   $(subst $(INST_VALIDATIONKIT), ,$(spec))))) \
		'--volume-id="VRAVALK_$(VRA_SVN_REV)_$(VRA_VERSION_STRING_RAW)"' \
		'--name-setup=joliet' \
		'--volume-id="VBoxValK $(VRA_SVN_REV)"'

#
# Build the Validation Kit guest ISO.
#
$(VRA_PATH_VALIDATIONKIT)/VBoxValidationKit.iso: \
		$(filter-out %=deleteme=, $(subst =,=deleteme= , $(VRA_VALIDATIONKIT_FILESPEC))) \
		$(VRA_SVN_REV_KMK) \
		$(VRA_PATH_VALIDATIONKIT_SRC)/Makefile.kmk \
		$(VRA_VALIDATIONKIT_ISO_RSP) \
		| $(if-expr defined(VRA_USE_RTISOMAKER),$(VRA_RTISOMAKER),)
	$(call MSG_TOOL,RTIsoMaker,,$@)
	$(QUIET)$(MKDIR) -p $(@D)
ifneq ($(KBUILD_TARGET),os2)
	$(QUIET)$(ECHO) VRA_VALIDATIONKIT_FILESPEC $(VRA_VALIDATIONKIT_FILESPEC)
endif
ifdef VRA_WITH_VALIDATIONKIT_UNITTESTS_PACKING
	$(foreach os, darwin linux solaris win,$(foreach arch, x86 amd64 arm64, \
		$(call MSG_L1, VRA_PATH_VALIDATIONKIT_UNITTESTS.$(os).$(arch): $(VRA_PATH_VALIDATIONKIT_UNITTESTS.$(os).$(arch))) \
	))
	$(call MSG_L1, VRA_VALIDATIONKIT_FILESPEC_UNITTESTS $(VRA_VALIDATIONKIT_FILESPEC_UNITTESTS))
endif
	$(VRA_RTISOMAKER) \
		@$(VRA_VALIDATIONKIT_ISO_RSP) \
		--output $@



# Alias for creating the iso.
.PHONY: validationkit-iso
validationkit-iso: $(VRA_PATH_VALIDATIONKIT)/VBoxValidationKit.iso
