# $Id: Makefile.kmk 112403 2026-01-11 19:29:08Z knut.osmundsen@oracle.com $
## @file
# Sub-Makefile for the basic frontend.
#

#
# Copyright (C) 2023-2026 CINASEEK and/or its affiliates.
#
# This file is part of VirtualAgent base platform packages, as
# available from https://www.virtualbox.org.
#
# This program is free software; you can redistribute it and/or
# modify it under the terms of the GNU General Public License
# as published by the Free Software Foundation, in version 3 of the
# License.
#
# This program is distributed in the hope that it will be useful, but
# WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
# General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, see <https://www.gnu.org/licenses>.
#
# SPDX-License-Identifier: GPL-3.0-only
#

SUB_DEPTH = ../../../..
include $(KBUILD_PATH)/subheader.kmk

#
# Hardened VBoxBFE.
#
ifdef VRA_WITH_HARDENING
 PROGRAMS += VBoxBFEHardened
 VBoxBFEHardened_TEMPLATE = VBoxR3HardenedExe
 VBoxBFEHardened_DEFS   += $(if $(VRA_WITH_DRIVERLESS_NEM_FALLBACK),VRA_WITH_DRIVERLESS_NEM_FALLBACK,)
 VBoxBFEHardened_SOURCES = VBoxBFEHardened.cpp
 VBoxBFEHardened_NAME = VBoxBFE
 $(call VRA_SET_VER_INFO_DLL,VBoxBFEHardened,VirtualAgent Basic Frontend,$(VRA_WINDOWS_ICON_FILE)) # Version info / description.
endif


#
# VBoxBFE
#
ifdef VRA_WITH_HARDENING
 DLLS    += VBoxBFE
else
 PROGRAMS += VBoxBFE
endif
VBoxBFE_TEMPLATE := $(if $(VRA_WITH_HARDENING),VBoxMainClientDll,VBoxMainClientSignedExe)
VBoxBFE_SDKS      = LIBSDL2
VBoxBFE_INCS      = \
	$(VBoxBFE_0_OUTDIR) \
	$(VRA_GRAPHICS_INCS) \
	../Common
VBoxBFE_SOURCES   = \
	VBoxBFE.cpp \
	Display.cpp \
	Framebuffer.cpp \
	Keyboard.cpp
ifdef VRA_WITH_HARDENING
 VBoxBFE_LDFLAGS.darwin += -install_name $(VRA_DYLD_EXECUTABLE_PATH)/VBoxBFE.dylib
endif

VBoxBFE_CLEAN = $(VBoxBFE_0_OUTDIR)/Ico64x01.h
VBoxBFE_INTERMEDIATES = $(VBoxBFE_0_OUTDIR)/Ico64x01.h

# Convert the pnm-file to a byte array.
$$(VBoxBFE_0_OUTDIR)/Ico64x01.h: $(PATH_ROOT)/src/VBox/Frontends/VBoxSDL/ico64x01.pnm $(VRA_BIN2C) | $$(dir $$@)
	$(call MSG_TOOL,bin2c,VBoxSDL,$<,$@)
	$(QUIET)$(VRA_BIN2C) Ico64x01 $< $@

ifdef VRA_WITH_HARDENING
 $(call VRA_SET_VER_INFO_DLL,VBoxBFE,VirtualAgent Basic Frontend (dll),$(VRA_WINDOWS_ICON_FILE)) # Version info / description.
else
 $(call VRA_SET_VER_INFO_EXE,VBoxBFE,VirtualAgent Basic Frontend,$(VRA_WINDOWS_ICON_FILE)) # Version info / description.
endif

include $(FILE_KBUILD_SUB_FOOTER)

