# $Id: Makefile.kmk 112403 2026-01-11 19:29:08Z knut.osmundsen@oracle.com $
## @file
# Sub-Makefile for the Windows Guest Additions Installer.
#

#
# Copyright (C) 2006-2026 CINASEEK and/or its affiliates.
#
# This file is part of VirtualAgent base platform packages, as
# available from https://www.virtualbox.org.
#
# This program is free software; you can redistribute it and/or
# modify it under the terms of the GNU General Public License
# as published by the Free Software Foundation, in version 3 of the
# License.
#
# This program is distributed in the hope that it will be useful, but
# WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
# General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, see <https://www.gnu.org/licenses>.
#
# SPDX-License-Identifier: GPL-3.0-only
#

SUB_DEPTH = ../../../../..
include $(KBUILD_PATH)/subheader.kmk

#
# Include Sub-Makefiles.
#
include $(PATH_SUB_CURRENT)/Loader/Makefile.kmk
include $(PATH_SUB_CURRENT)/InstallHelper/Makefile.kmk


#
# Globals
#
VRA_PATH_WIN_ADD_INS_SRC := $(PATH_SUB_CURRENT)
VRA_WITH_GUEST_INSTALL_HELPER := 1 # Use our guest install helper DLL.
## @todo VRA_WIN_ADD_INS_OUT_DIR := $(PATH_TARGET)/Additions/Installer/win

ifdef VRA_WIN_ATTESTATION_SIGNING
 VRA_DRIVERS_PACK_NAME := VBoxDrivers-$(VRA_VERSION_MAJOR).$(VRA_VERSION_MINOR).$(VRA_VERSION_BUILD)r$(VRA_SVN_REV)-$(KBUILD_TARGET_ARCH).cab
 VRA_SIGNED_DRIVERS_ZIP_NAME := $(VRA_DRIVERS_PACK_NAME).Signed.zip
 include $(KBUILD_PATH)/tools/ZIP.kmk
 TOOL_ZIP_PACK ?= zip
endif


#
# The Guest Additions variant of VBoxDrvInst.
#
VRA_PATH_GH_INSTALLATION_SRC := $(PATH_ROOT)/src/VBox/GuestHost/installation

PROGRAMS.win += VBoxDrvInstGuest
VBoxDrvInstGuest_TEMPLATE = VBoxGuestR3Exe
VBoxDrvInstGuest_DEFS     = _UNICODE UNICODE VRA_SVN_REV=$(VRA_SVN_REV)
VBoxDrvInstGuest_NAME    := VBoxDrvInst
VBoxDrvInstGuest_SOURCES  = \
	$(VRA_PATH_GH_INSTALLATION_SRC)/VBoxWinDrvCommon.cpp \
	$(VRA_PATH_GH_INSTALLATION_SRC)/VBoxWinDrvInst.cpp \
	$(VRA_PATH_GH_INSTALLATION_SRC)/VBoxWinDrvStore.cpp \
	$(VRA_PATH_GH_INSTALLATION_SRC)/VBoxDrvInst.cpp \
	$(VRA_PATH_GH_INSTALLATION_SRC)/VBoxDrvInst.rc
VBoxDrvInstGuest_VRA_IMPORT_CHECKER.win.x86 := nt4 # setupapi was introduced in NT4.


#
# Install all the certificates we use.
#
INSTALLS += AdditionsInstCertFiles
AdditionsInstCertFiles_TEMPLATE := VBoxGuestR3Exe
AdditionsInstCertFiles_SOURCES   =
AdditionsInstCertFiles_CLEAN     =
if defined(VRA_SIGNING_MODE) && defined(VRA_SIGN_ADDITIONS)
 define def_VBoxAdditionsInstCertFiles
  AdditionsInstCertFiles_SOURCES += $$(AdditionsInstCertFiles_0_OUTDIR)/$(1)=>$1
  AdditionsInstCertFiles_CLEAN   += $$(AdditionsInstCertFiles_0_OUTDIR)/$(1)
  $$$$(AdditionsInstCertFiles_0_OUTDIR)/$(1): $$(2) | $$$$(dir $$$$@) $(VRA_RTSIGNTOOL)
	$(QUIET)$(RM) -f -- "$$@"
	$(VRA_RTSIGNTOOL) $3 --signature-index $4 --input "$$<" --output "$$@"
 endef

 if !defined(VRA_CERTIFICATE_SUBJECT_NAME) && !$(intersects win_planb,$(VRA_WITH_CORP_CODE_SIGNING))
  # No SHA1 cert at all, no weird Plan B style signing, just the SHA2 cert.
  $(evalcall2 def_VBoxAdditionsInstCertFiles,vbox-sha256.cer,$(VRA_PATH_ADDITIONS)/VBoxGuest.sys, \
  	extract-exe-signer-cert, 0)
  VRA_GA_CERT_ROOT_SHA2 := vbox-sha256-root.cer
  $(evalcall2 def_VBoxAdditionsInstCertFiles,$(VRA_GA_CERT_ROOT_SHA2),$(VRA_PATH_ADDITIONS)/VBoxGuest.sys, \
  	extract-signer-root --self-signed-roots-from-system, 0)
  ifdef VRA_TSA_SHA2_URL_ARGS
   VRA_GA_CERT_ROOT_SHA2_TS := vbox-sha256-timestamp-root.cer
   $(evalcall2 def_VBoxAdditionsInstCertFiles,$(VRA_GA_CERT_ROOT_SHA2_TS),$(VRA_PATH_ADDITIONS)/VBoxGuest.sys, \
   	extract-timestamp-root --self-signed-roots-from-system, 0)
  endif
 else if !defined(VRA_CERTIFICATE_SHA2_SUBJECT_NAME) && !$(intersects win all 1,$(VRA_WITH_CORP_CODE_SIGNING))
  # No SHA2 signing, just the SHA1 cert.
  $(evalcall2 def_VBoxAdditionsInstCertFiles,vbox.cer,$(VRA_PATH_ADDITIONS)/VBoxGuest.sys, \
  	extract-exe-signer-cert, 0)
  VRA_GA_CERT_ROOT_SHA1 := vbox-root.cer
  $(evalcall2 def_VBoxAdditionsInstCertFiles,$(VRA_GA_CERT_ROOT_SHA1),$(VRA_PATH_ADDITIONS)/VBoxGuest.sys, \
  	extract-signer-root --self-signed-roots-from-system, 0)
  ifdef VRA_TSA_URL_ARGS
   VRA_GA_CERT_ROOT_SHA1_TS := vbox-timestamp-root.cer
   $(evalcall2 def_VBoxAdditionsInstCertFiles,$(VRA_GA_CERT_ROOT_SHA1_TS),$(VRA_PATH_ADDITIONS)/VBoxGuest.sys, \
   	extract-timestamp-root --self-signed-roots-from-system, 0)
  endif
 else
  # Dual signing, both SHA1 and SHA2 driver cert, plus maybe SHA2 userland cert.
  $(evalcall2 def_VBoxAdditionsInstCertFiles,vbox-sha1.cer,$(VRA_PATH_ADDITIONS)/VBoxGuest.sys, \
  	extract-exe-signer-cert, 0)
  VRA_GA_CERT_ROOT_SHA1 := vbox-sha1-root.cer
  $(evalcall2 def_VBoxAdditionsInstCertFiles,$(VRA_GA_CERT_ROOT_SHA1),$(VRA_PATH_ADDITIONS)/VBoxGuest.sys, \
  	extract-signer-root --self-signed-roots-from-system, 0)
  ifdef VRA_TSA_URL_ARGS
   VRA_GA_CERT_ROOT_SHA1_TS := vbox-sha1-timestamp-root.cer
   $(evalcall2 def_VBoxAdditionsInstCertFiles,$(VRA_GA_CERT_ROOT_SHA1_TS),$(VRA_PATH_ADDITIONS)/VBoxGuest.sys, \
   	extract-timestamp-root --self-signed-roots-from-system, 0)
  endif

  $(evalcall2 def_VBoxAdditionsInstCertFiles,vbox-sha256.cer,$(VRA_PATH_ADDITIONS)/VBoxGuest.sys, \
  	extract-exe-signer-cert, 1)
  VRA_GA_CERT_ROOT_SHA2 := vbox-sha256-root.cer
  $(evalcall2 def_VBoxAdditionsInstCertFiles,$(VRA_GA_CERT_ROOT_SHA2),$(VRA_PATH_ADDITIONS)/VBoxGuest.sys, \
  	extract-signer-root --self-signed-roots-from-system, 1)
  ifdef VRA_TSA_SHA2_URL_ARGS
   VRA_GA_CERT_ROOT_SHA2_TS := vbox-sha256-timestamp-root.cer
   $(evalcall2 def_VBoxAdditionsInstCertFiles,$(VRA_GA_CERT_ROOT_SHA2_TS),$(VRA_PATH_ADDITIONS)/VBoxGuest.sys, \
   	extract-timestamp-root --self-signed-roots-from-system, 1)
  endif

  if !$(intersects win, $(VRA_WITH_CORP_CODE_SIGNING)) && $(intersects win_planb,$(VRA_WITH_CORP_CODE_SIGNING))
   $(evalcall2 def_VBoxAdditionsInstCertFiles,vbox-sha256-r3.cer,$(VRA_PATH_ADDITIONS)/VBoxGuestInstallHelper.exe, \
   	extract-exe-signer-cert, 1)
   VRA_GA_CERT_ROOT_SHA2_R3 := vbox-sha256-r3-root.cer
   $(evalcall2 def_VBoxAdditionsInstCertFiles,$(VRA_GA_CERT_ROOT_SHA2_R3),$(VRA_PATH_ADDITIONS)/VBoxGuestInstallHelper.exe, \
  	extract-signer-root --self-signed-roots-from-system, 1)
   VRA_GA_CERT_ROOT_SHA2_R3_TS := vbox-sha256-r3-timestamp-root.cer
   $(evalcall2 def_VBoxAdditionsInstCertFiles,$(VRA_GA_CERT_ROOT_SHA2_R3_TS),$(VRA_PATH_ADDITIONS)/VBoxGuestInstallHelper.exe, \
   	extract-timestamp-root --self-signed-roots-from-system, 1)
  endif
 endif
endif

#
# The installer.
#
PACKING     += $(PATH_STAGE_BIN)/additions/VBoxWindowsAdditions-$(KBUILD_TARGET_ARCH).exe
OTHER_CLEAN += $(PATH_STAGE_BIN)/additions/VBoxWindowsAdditions-$(KBUILD_TARGET_ARCH).exe

VRA_WINDOWS_ADDITIONS_ATTESTATION_SIGNED_FILES := \
	$(PATH_STAGE_BIN)/additions/VBoxGuest.inf \
	$(PATH_STAGE_BIN)/additions/VBoxGuest.sys \
	$(PATH_STAGE_BIN)/additions/VBoxTray.exe \
	$(PATH_STAGE_BIN)/additions/VBoxControl.exe \
	\
	$(PATH_STAGE_BIN)/additions/VBoxMouse.inf \
	$(PATH_STAGE_BIN)/additions/VBoxMouse.sys \
	\
	$(PATH_STAGE_BIN)/additions/VBoxSF.sys \
	$(PATH_STAGE_BIN)/additions/VBoxMRXNP.dll

ifneq ($(KBUILD_TARGET_ARCH),arm64) ## @todo win.arm64: Make VBoxVideo build.
 VRA_WINDOWS_ADDITIONS_ATTESTATION_SIGNED_FILES += \
 	$(PATH_STAGE_BIN)/additions/VBoxVideo.inf \
 	$(PATH_STAGE_BIN)/additions/VBoxVideo.sys \
 	$(PATH_STAGE_BIN)/additions/VBoxDisp.dll
endif

ifeq ($(KBUILD_TARGET_ARCH),amd64) # 32-bit network provider DLLs for 32-bit apps running on a 64-bit system
 VRA_WINDOWS_ADDITIONS_ATTESTATION_SIGNED_FILES += \
 	$(PATH_STAGE_BIN)/additions/VBoxMRXNP-x86.dll
endif

ifeq ($(KBUILD_TARGET_ARCH),x86)
 VRA_WINDOWS_ADDITIONS_OTHER_FILES += \
 	$(PATH_STAGE_BIN)/additions/VBoxGuestEarlyNT.inf \
 	$(PATH_STAGE_BIN)/additions/VBoxVideoEarlyNT.inf
endif

if defined(VRA_SIGNING_MODE) && defined(VRA_SIGN_ADDITIONS)
 VRA_WINDOWS_ADDITIONS_OTHER_FILES += \
 	$(PATH_STAGE_BIN)/additions/VBoxVideo.cat \
 	$(PATH_STAGE_BIN)/additions/VBoxGuest.cat \
 	$(PATH_STAGE_BIN)/additions/VBoxMouse.cat
 if1of ($(KBUILD_TARGET_ARCH), x86 amd64)
  VRA_WINDOWS_ADDITIONS_OTHER_FILES += \
  	$(PATH_STAGE_BIN)/additions/VBoxVideo-PreW10.cat \
  	$(PATH_STAGE_BIN)/additions/VBoxGuest-PreW10.cat \
  	$(PATH_STAGE_BIN)/additions/VBoxMouse-PreW10.cat
 endif
 ifeq ($(KBUILD_TARGET_ARCH),x86)
  VRA_WINDOWS_ADDITIONS_OTHER_FILES += \
  	$(PATH_STAGE_BIN)/additions/VBoxGuestEarlyNT.cat \
  	$(PATH_STAGE_BIN)/additions/VBoxVideoEarlyNT.cat
 endif
endif

VRA_WINDOWS_ADDITIONS_OTHER_FILES := \
	$(PATH_STAGE_BIN)/additions/VBoxService.exe \
	$(PATH_STAGE_BIN)/additions/VBoxHook.dll \
	$(PATH_STAGE_BIN)/additions/VBoxDrvInst.exe

ifeq ($(KBUILD_TARGET_ARCH),x86)
 VRA_WINDOWS_ADDITIONS_OTHER_FILES += \
 	$(PATH_STAGE_BIN)/additions/VBoxMouseNT.sys \
 	$(PATH_STAGE_BIN)/additions/VBoxSFW2K.sys
endif

ifdef VRA_WITH_WDDM
 VRA_WINDOWS_ADDITIONS_ATTESTATION_SIGNED_FILES += \
 	$(PATH_STAGE_BIN)/additions/VBoxWddm.inf \
 	$(PATH_STAGE_BIN)/additions/VBoxWddm.sys \
 	$(PATH_STAGE_BIN)/additions/VBoxDispD3D.dll
 ifeq ($(KBUILD_TARGET_ARCH),amd64)
  VRA_WINDOWS_ADDITIONS_ATTESTATION_SIGNED_FILES += \
  	$(PATH_STAGE_BIN)/additions/VBoxDispD3D-x86.dll
 endif

 ifdef VRA_WITH_WDDM_DX
  VRA_WINDOWS_ADDITIONS_ATTESTATION_SIGNED_FILES += \
  	$(PATH_STAGE_BIN)/additions/VBoxDX.dll
  ifeq ($(KBUILD_TARGET_ARCH),amd64)
   VRA_WINDOWS_ADDITIONS_ATTESTATION_SIGNED_FILES += \
   	$(PATH_STAGE_BIN)/additions/VBoxDX-x86.dll
  endif
 endif

 ifdef VRA_WITH_MESA3D
  VRA_WINDOWS_ADDITIONS_ATTESTATION_SIGNED_FILES += \
  	$(PATH_STAGE_BIN)/additions/VBoxNine.dll \
  	$(PATH_STAGE_BIN)/additions/VBoxSVGA.dll \
  	$(PATH_STAGE_BIN)/additions/VBoxGL.dll
  ifeq ($(KBUILD_TARGET_ARCH),amd64)
   VRA_WINDOWS_ADDITIONS_ATTESTATION_SIGNED_FILES += \
   	$(PATH_STAGE_BIN)/additions/VBoxNine-x86.dll \
   	$(PATH_STAGE_BIN)/additions/VBoxSVGA-x86.dll \
   	$(PATH_STAGE_BIN)/additions/VBoxGL-x86.dll
  endif
 endif

 if defined(VRA_SIGNING_MODE) && defined(VRA_SIGN_ADDITIONS)
  VRA_WINDOWS_ADDITIONS_OTHER_FILES += \
  	$(PATH_STAGE_BIN)/additions/VBoxWddm.cat \
  	$(PATH_STAGE_BIN)/additions/VBoxWddm-PreW10.cat
 endif
endif # VRA_WITH_WDDM

ifdef VRA_WITH_ADDITIONS_SHIPPING_AUDIO_TEST
 VRA_WINDOWS_ADDITIONS_OTHER_FILES += \
 	$(PATH_STAGE_BIN)/additions/VBoxAudioTest.exe
endif

VRA_WINDOWS_ADDITIONS_OTHER_FILES += $(addprefix $(PATH_STAGE_BIN)/additions/, \
		$(VRA_GA_CERT_ROOT_SHA1) \
		$(VRA_GA_CERT_ROOT_SHA1_TS) \
		$(VRA_GA_CERT_ROOT_SHA2) \
		$(VRA_GA_CERT_ROOT_SHA2_TS) \
		$(VRA_GA_CERT_ROOT_SHA2_R3) \
		$(VRA_GA_CERT_ROOT_SHA2_R3_TS))

VB_WIN_ADD_NSIS_ENV := \
	-E 'PATH_OUT=$(subst /,\,$(PATH_OUT))' \
	-E 'PATH_TARGET=$(subst /,\,$(PATH_TARGET))' \
	-E 'VRA_VENDOR=$(VRA_VENDOR)' \
	-E 'VRA_VENDOR_SHORT=$(VRA_VENDOR_SHORT)' \
	-E 'VRA_PRODUCT=$(VRA_PRODUCT)' \
	-E 'VRA_C_YEAR=$(VRA_C_YEAR)' \
	-E 'VRA_VERSION_STRING=$(VRA_VERSION_STRING)' \
	-E 'VRA_VERSION_STRING_RAW=$(VRA_VERSION_STRING_RAW)' \
	-E 'VRA_VERSION_MAJOR=$(VRA_VERSION_MAJOR)' \
	-E 'VRA_VERSION_MINOR=$(VRA_VERSION_MINOR)' \
	-E 'VRA_VERSION_BUILD=$(VRA_VERSION_BUILD)' \
	-E 'VRA_SVN_REV=$(VRA_SVN_REV)' \
	-E 'VRA_WINDOWS_ADDITIONS_ICON_FILE=$(subst /,\,$(VRA_WINDOWS_ADDITIONS_ICON_FILE))' \
	-E 'VRA_NSIS_ICON_FILE=$(subst /,\,$(VRA_NSIS_ICON_FILE))' \
	-E 'VRA_WITH_GUEST_INSTALL_HELPER=$(if $(VRA_WITH_GUEST_INSTALL_HELPER),1,0)' \
	-E 'VRA_WITH_GUEST_INSTALLER_UNICODE=$(if $(VRA_WITH_GUEST_INSTALLER_UNICODE),1,0)' \
	-E 'VRA_WITH_ADDITIONS_SHIPPING_AUDIO_TEST=$(if $(VRA_WITH_ADDITIONS_SHIPPING_AUDIO_TEST),1,0)' \
	-E 'VRA_WITH_LICENSE_INSTALL_RTF=$(if $(VRA_BRAND_LICENSE_RTF),1,0)' \
	-E 'VRA_WITH_WDDM=$(if $(VRA_WITH_WDDM),1,0)' \
	-E 'VRA_WITH_WDDM_DX=$(if $(VRA_WITH_WDDM_DX),1,0)' \
	-E 'VRA_WITH_MESA3D=$(if $(VRA_WITH_MESA3D),1,0)' \
	-E 'VRA_BRAND_WIN_ADD_INST_DLGBMP=$(subst /,\,$(VRA_BRAND_WIN_ADD_INST_DLGBMP))' \
	-E 'VRA_BRAND_LICENSE_RTF=$(subst /,\,$(VRA_BRAND_LICENSE_RTF))' \
	$(foreach lang,$(VRA_INSTALLER_ADD_LANGUAGES),-E 'VRA_BRAND_$(lang)_LICENSE_RTF=$(VRA_BRAND_$(lang)_LICENSE_RTF)') \
	-E 'KBUILD_TYPE=$(KBUILD_TYPE)' \
	-E 'KBUILD_TARGET_ARCH=$(KBUILD_TARGET_ARCH)' \
	$(foreach base, VRA_GA_CERT_ROOT_SHA1 VRA_GA_CERT_ROOT_SHA2 VRA_GA_CERT_ROOT_SHA2_R3 \
		,-E '$(base)=$(firstword $($(base)) none)' -E '$(base)_TS=$(firstword $($(base)_TS) none)')

# Notes on SetCompressor: solid + lzma w/ 16MB dict reduced the amd64 installer
#   from 16280616 to 7679592 bytes, or by ~53%.  For x86 we use a smaller
#   dictionary (the default) since ancient windows VMs doesn't require a lot of
#   memory and the VMs might have a lot of RAM configured.  Size reduction is
#   from 9530296 to 5056096 bytes / by ~47%. (4 MB dict: 5948856 bytes / 38%)
$(PATH_STAGE_BIN)/additions/VBoxWindowsAdditions-$(KBUILD_TARGET_ARCH).exe: \
		$(PATH_SUB_CURRENT)/VBoxGuestAdditions.nsi \
		$(PATH_SUB_CURRENT)/VBoxGuestAdditionsCommon.nsh \
		$(PATH_SUB_CURRENT)/VBoxGuestAdditionsExternal.nsh \
		$(PATH_SUB_CURRENT)/VBoxGuestAdditionsLog.nsh \
		$(PATH_SUB_CURRENT)/VBoxGuestAdditionsUninstall.nsh \
		$(PATH_SUB_CURRENT)/VBoxGuestAdditionsUninstallOld.nsh \
		$(PATH_SUB_CURRENT)/VBoxGuestAdditionsNT4.nsh \
		$(PATH_SUB_CURRENT)/VBoxGuestAdditionsW2KXP.nsh \
		$(PATH_SUB_CURRENT)/VBoxGuestAdditionsVista.nsh \
		$(PATH_SUB_CURRENT)/dumplog.nsh \
		$(PATH_SUB_CURRENT)/Languages/English.nsh \
		$(PATH_SUB_CURRENT)/Languages/German.nsh \
		$(PATH_SUB_CURRENT)/Languages/French.nsh \
		$(VRA_WINDOWS_ADDITIONS_ATTESTATION_SIGNED_FILES) \
		$(VRA_WINDOWS_ADDITIONS_OTHER_FILES) \
		$(VRA_WINDOWS_ADDITIONS_ICON_FILE) \
		$(VRA_NSIS_ICON_FILE) \
		$(if $(VRA_SIGNING_MODE),$(PATH_TARGET)/uninst.exe) \
		$(if $(VRA_WIN_ATTESTATION_SIGNING),$(PATH_OUT)/repackadd/$(VRA_SIGNED_DRIVERS_ZIP_NAME)) \
		$(VRA_VERSION_STAMP) \
		$$(VBoxGuestInstallHelper_1_STAGE_TARGET) \
		| $(VRA_SIGN_IMAGE_ORDERDEPS)
	$(call MSG_L1,Creating $@, from $<)
ifdef VRA_WIN_ATTESTATION_SIGNING # Unpack the attestation signed drivers - this is an ugly as 'ing heck hack!
	$(TOOL_ZIP_UNPACK) -oj $(PATH_OUT)/repackadd/$(VRA_SIGNED_DRIVERS_ZIP_NAME) -d $(PATH_STAGE_BIN)/additions/
endif
	$(REDIRECT) -C $(VRA_PATH_WIN_ADD_INS_SRC) \
		$(VB_WIN_ADD_NSIS_ENV) \
		-- $(EXEC_X86_WIN32) $(VRA_PATH_NSIS)/makensis.exe /NOCD /V3 \
			"/XSetCompressor /SOLID lzma" "/XSetCompressorDictSize $(if-expr $(KBUILD_TARGET_ARCH) == x86,4,16)" \
			$(if-expr defined(VRA_WITH_NATIVE_NSIS_INSTALLER),"/XTarget $(KBUILD_TARGET_ARCH)-unicode",) \
			$(if $(VRA_WITH_ADDITIONS_SHIPPING_AUDIO_TEST),'/DVRA_WITH_ADDITIONS_SHIPPING_AUDIO_TEST=1') \
			$(if $(VRA_SIGNING_MODE),'/DEXTERNAL_UNINSTALLER=1') \
                       $(if-expr defined(VRA_SIGN_ADDITIONS) && defined(VRA_SIGNING_MODE), \
                       	'/DVRA_SIGN_ADDITIONS=1' \
				$(if-expr defined(VRA_WITH_VRA_LEGACY_TS_CA),'/DVRA_WITH_VRA_LEGACY_TS_CA=1') \
                       ,) \
			$(if $(VRA_INSTALLER_ADD_LANGUAGES),'/DVRA_INSTALLER_ADD_LANGUAGES=1') \
			$(foreach lang,$(VRA_INSTALLER_ADD_LANGUAGES),'/DVRA_BRAND_$(lang)_LICENSE_RTF=1') \
			'$(subst /,\,$<)'
	$(call VRA_SIGN_IMAGE_FN,$@)


ifdef VRA_SIGNING_MODE
 #
 # This is a hack to sign the uninstaller.
 # See http://nsis.sourceforge.net/Signing_an_Uninstaller for more details.
 #
 OTHER_CLEAN += \
 	$(PATH_TARGET)/VBoxWindowsAdditions-$(KBUILD_TARGET_ARCH)-uninst.exe \
 	$(PATH_TARGET)/uninst.exe
 $(PATH_TARGET)/VBoxWindowsAdditions-$(KBUILD_TARGET_ARCH)-uninst.exe: \
 		$(PATH_SUB_CURRENT)/VBoxGuestAdditions.nsi \
 		$(PATH_SUB_CURRENT)/VBoxGuestAdditionsCommon.nsh \
 		$(PATH_SUB_CURRENT)/VBoxGuestAdditionsExternal.nsh \
 		$(PATH_SUB_CURRENT)/VBoxGuestAdditionsLog.nsh \
 		$(PATH_SUB_CURRENT)/VBoxGuestAdditionsUninstall.nsh \
 		$(PATH_SUB_CURRENT)/VBoxGuestAdditionsNT4.nsh \
 		$(PATH_SUB_CURRENT)/VBoxGuestAdditionsW2KXP.nsh \
 		$(PATH_SUB_CURRENT)/VBoxGuestAdditionsVista.nsh \
 		$(PATH_SUB_CURRENT)/dumplog.nsh \
 		$(PATH_SUB_CURRENT)/Languages/English.nsh \
 		$(PATH_SUB_CURRENT)/Languages/German.nsh \
 		$(PATH_SUB_CURRENT)/Languages/French.nsh \
 		$(VRA_WINDOWS_ADDITIONS_ATTESTATION_SIGNED_FILES) \
 		$(VRA_WINDOWS_ADDITIONS_OTHER_FILES) \
 		$(VRA_WINDOWS_ADDITIONS_ICON_FILE) \
 		$(VRA_NSIS_ICON_FILE) \
 		$(VRA_VERSION_STAMP) \
 		$$(VBoxGuestInstallHelper_1_STAGE_TARGET) \
 		| $$(dir $$@)
	$(call MSG_L1,Creating $@, from $<)
	$(QUIET)$(REDIRECT) -C $(VRA_PATH_WIN_ADD_INS_SRC) \
		$(VB_WIN_ADD_NSIS_ENV) \
		-- $(EXEC_X86_WIN32) $(VRA_PATH_NSIS)/makensis.exe /NOCD /V2 \
			$(if-expr defined(VRA_WITH_NATIVE_NSIS_INSTALLER),"/XTarget $(KBUILD_TARGET_ARCH)-unicode",) \
			$(if $(VRA_WITH_ADDITIONS_SHIPPING_AUDIO_TEST),'/DVRA_WITH_ADDITIONS_SHIPPING_AUDIO_TEST=1') \
			$(if $(VRA_SIGN_ADDITIONS),'/DVRA_SIGN_ADDITIONS=1') \
			$(if $(VRA_WITH_VRA_LEGACY_TS_CA),'/DVRA_WITH_VRA_LEGACY_TS_CA=1') \
			$(if $(VRA_INSTALLER_ADD_LANGUAGES),'/DVRA_INSTALLER_ADD_LANGUAGES=1') \
			$(foreach lang,$(VRA_INSTALLER_ADD_LANGUAGES),'/DVRA_BRAND_$(lang)_LICENSE_RTF=1') \
			'/DUNINSTALLER_ONLY=1' \
			'$(subst /,\,$<)'

 $(PATH_TARGET)/uninst.exe: \
 		$(PATH_TARGET)/VBoxWindowsAdditions-$(KBUILD_TARGET_ARCH)-uninst.exe | $$(dir $$@) $(VRA_SIGN_IMAGE_ORDERDEPS)
	$(call MSG_L1,Creating $@, from $<)
	$(QUIET)$(RM) -f $@
	-$(REDIRECT) -E __COMPAT_LAYER=RUNASINVOKER -- $<
	$(TEST) -f $@
	$(call VRA_SIGN_IMAGE_FN,$@)

endif # VRA_SIGNING_MODE


if defined(VRA_WIN_ATTESTATION_SIGNING) && defined(VRA_SIGNING_MODE) && defined(VRA_SIGN_ADDITIONS)
 #
 # This automagically attestation signs the GA drivers.
 #
 $(PATH_OUT)/repackadd/$(VRA_SIGNED_DRIVERS_ZIP_NAME): \
 		$(PATH_OUT)/repackadd/$(VRA_DRIVERS_PACK_NAME)
	$(RM_EXT) -f -- $(PATH_OUT)/repackadd/*.zip
	cd $(PATH_OUT)/repackadd \
		&& $(VRA_RETRY) $(VRA_WIN_ATTESTATION_SIGNING_EXE) \
			"VirtualAgent GA drivers $(KBUILD_TARGET_ARCH) $(VRA_VERSION_MAJOR).$(VRA_VERSION_MINOR).$(VRA_VERSION_BUILD)r$(VRA_SVN_REV)" \
			"$(KBUILD_TARGET_ARCH)" \
			"r$(VRA_SVN_REV)" \
			"$(VRA_DRIVERS_PACK_NAME)"

 #
 # This creates a .CAB file of the driver files that should be attestation signed.
 #
 $(PATH_OUT)/repackadd/$(VRA_DRIVERS_PACK_NAME): \
 		$(PATH_OUT)/repackadd/PackDriversForSubmission.cmd \
 		# $(VRA_WINDOWS_ADDITIONS_ATTESTATION_SIGNED_FILES) - is is unsafe, because of the 'ing ugly hack replacing most of them above during packing.
	$(RM_EXT) -f $(PATH_OUT)/repackadd/*.cab
	$(RM_EXT) -f $(PATH_OUT)/repackadd/*.ddf
	$(RM_EXT) -f $(PATH_OUT)/repackadd/*.inf
	$(RM_EXT) -f $(PATH_OUT)/repackadd/*.rpt
	$(EXEC_X86_WIN32) cmd /c $(PATH_OUT)/repackadd/PackDriversForSubmission.cmd -b $(PATH_STAGE_BIN) -a $(KBUILD_TARGET_ARCH) \
		-x -n --no-main --ga -o $(PATH_OUT)/repackadd/$(VRA_DRIVERS_PACK_NAME)
	$(call VRA_SIGN_EV_FILE_FN,$@)
endif # VRA_WIN_ATTESTATION_SIGNING && VRA_SIGNING_MODE && VRA_SIGN_ADDITIONS

#

# Repackaging scripts and files.
#
INSTALLS += RePackScriptsAdd
RePackScriptsAdd_TEMPLATE = DUMMY
RePackScriptsAdd_INST = repackadd/
RePackScriptsAdd_INSTTYPE = stage
RePackScriptsAdd_SOURCES = \
	../../../Installer/win/Scripts/UnpackBlessedDrivers.cmd \
	$(RePackScriptsAdd_0_OUTDIR)/PackDriversForSubmission.cmd \
	$(RePackScriptsAdd_0_OUTDIR)/Combined-1-Prepare.cmd \
	$(RePackScriptsAdd_0_OUTDIR)/Combined-3-RepackAdditions.cmd \
	$(RePackScriptsAdd_0_OUTDIR)/sign-ev.cmd
RePackScriptsAdd_CLEAN = \
	$(RePackScriptsAdd_0_OUTDIR)/sign-ev.cmd

ifndef VRA_OSE
 RePackScriptsAdd_SOURCES += \
 	$(RePackScriptsAdd_0_OUTDIR)/Combined-0-Additions.cmd \
 	$(RePackScriptsAdd_0_OUTDIR)/Combined-2-SignAdditions.cmd
endif

$(call VRA_EDIT_VERSION_AND_BUILD_RULE_FN,RePackScriptsAdd,../../../Installer/win/Scripts/PackDriversForSubmission.cmd,PackDriversForSubmission.cmd)
$(call VRA_EDIT_VERSION_AND_BUILD_RULE_FN,RePackScriptsAdd,../../../Installer/win/Scripts/Combined-1-Prepare.cmd,Combined-1-Prepare.cmd)
ifndef VRA_OSE
 $(call VRA_EDIT_VERSION_AND_BUILD_RULE_FN,RePackScriptsAdd,../../../Installer/win/Scripts/Combined-0-Additions.cmd,Combined-0-Additions.cmd)
 $(call VRA_EDIT_VERSION_AND_BUILD_RULE_FN,RePackScriptsAdd,../../../Installer/win/Scripts/Combined-2-SignAdditions.cmd,Combined-2-SignAdditions.cmd)
endif
$(call VRA_EDIT_VERSION_AND_BUILD_RULE_FN,RePackScriptsAdd,../../../Installer/win/Scripts/Combined-3-RepackAdditions.cmd,Combined-3-RepackAdditions.cmd)

# The %~dp1\ oddity is working around otherwise ending with \" during
# expansion of the CCS command line which for a reason I cannot immediately
# understand appends a " to the path.
$$(RePackScriptsAdd_0_OUTDIR)/sign-ev.cmd: | $$(dir $$@)
	$(APPEND) -nt "$@" \
		'if ".%KBUILD_DEVTOOLS%" == "." (echo KBUILD_DEVTOOLS is not set & exit /b 1)' \
		'if ".%KBUILD_BIN_PATH%" == "." (echo KBUILD_BIN_PATH is not set & exit /b 1)' \
		'if ".%1" == "." (echo No .cab file specified & exit /b 1)' \
		$(subst $(KBUILD_BIN_PATH),%KBUILD_BIN_PATH%,$(subst $(KBUILD_DEVTOOLS),%KBUILD_DEVTOOLS%, \
		'( $(call VRA_SIGN_EV_FILE_FN,%1,%~dp1\) ) || exit /b1' \
		) )

#
# Repacking resources.
#
INSTALLS += RePackScriptsAddResources
RePackScriptsAddResources_TEMPLATE = DUMMY
RePackScriptsAddResources_INST = repackadd/resources/
RePackScriptsAddResources_INSTTYPE = stage
RePackScriptsAddResources_DIRS = Languages
RePackScriptsAddResources_SOURCES = \
	welcome.bmp \
	$(VRA_WINDOWS_ADDITIONS_ICON_FILE)=>VirtualAgentGA-vista.ico \
	$(VRA_NSIS_ICON_FILE)=>VirtualAgentGA-nsis.ico \
	$(PATH_ROOT)/doc/License-gpl-3.0.rtf \
	VBoxGuestAdditions.nsi \
	dumplog.nsh \
	VBoxGuestAdditionsCommon.nsh \
	VBoxGuestAdditionsExternal.nsh \
	VBoxGuestAdditionsLog.nsh \
	VBoxGuestAdditionsNT4.nsh \
	VBoxGuestAdditionsUninstall.nsh \
	VBoxGuestAdditionsUninstallOld.nsh \
	VBoxGuestAdditionsVista.nsh \
	VBoxGuestAdditionsW2KXP.nsh \
	ISO/AUTORUN.INF \
	ISO/NT3xReadme.txt \
	\
	Languages/English.nsh=>Languages/English.nsh \
	Languages/French.nsh=>Languages/French.nsh \
	Languages/German.nsh=>Languages/German.nsh


#
# NT3.x installer.
#
# Just for fun, this one does not use the CRT more than it really really needs
# to.  This saves space and avoid compatiblity issues, it also makes for a
# fun challenge.
#
PROGRAMS.win.x86 += VBoxAddInstallNt3x
ifdef VRA_WITH_NOCRT_STATIC
 ## @todo noCRT: the result is much too big. Got rid of log.cpp, but still pretty big. Work on reducing it.
 VBoxAddInstallNt3x_TEMPLATE := VBoxGuestR3Exe
else
 VBoxAddInstallNt3x_TEMPLATE := VBoxGuestR3NoCrtExe
endif
VBoxAddInstallNt3x_SOURCES  := VBoxAddInstallNt3x.cpp
VBoxAddInstallNt3x.cpp_DEPS = $(VRA_SVN_REV_HEADER)


include $(FILE_KBUILD_SUB_FOOTER)

