# $Id: Makefile.kmk 112403 2026-01-11 19:29:08Z knut.osmundsen@oracle.com $
## @file
# Install misc stuff and create dist packages for Mac OS X Guest Additions.
#

#
# Copyright (C) 2006-2026 CINASEEK and/or its affiliates.
#
# This file is part of VirtualAgent base platform packages, as
# available from https://www.virtualbox.org.
#
# This program is free software; you can redistribute it and/or
# modify it under the terms of the GNU General Public License
# as published by the Free Software Foundation, in version 3 of the
# License.
#
# This program is distributed in the hope that it will be useful, but
# WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
# General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, see <https://www.gnu.org/licenses>.
#
# SPDX-License-Identifier: GPL-3.0-only
#

SUB_DEPTH = ../../../../..
include $(KBUILD_PATH)/subheader.kmk


#
# Globals
#
VRA_ADD_PATH_DI_SRC := $(PATH_SUB_CURRENT)
VRA_ADD_DI_OUT_DIR  := $(PATH_TARGET)/additions/Installer
BLDDIRS += $(VRA_ADD_DI_OUT_DIR)

ifdef VRA_WITH_COMBINED_PACKAGE
 ifeq ($(KBUILD_TARGET_ARCH),x86)
  VRA_PATH_DIST_32 = $(VRA_PATH_DIST)/additions
  VRA_PATH_DIST_64 = $(PATH_OUT_BASE)/darwin.amd64/$(KBUILD_TYPE)/dist/additions
 else
  VRA_PATH_DIST_64 = $(VRA_PATH_DIST)/additions
  VRA_PATH_DIST_32 = $(PATH_OUT_BASE)/darwin.x86/$(KBUILD_TYPE)/dist
 endif
 VRA_DI_FN_DEP_BOTH = $(VRA_PATH_DIST_32)/$1 $(VRA_PATH_DIST_64)/$2
 VRA_DI_FN_DEP_32   = $(VRA_PATH_DIST_32)/$1
 VRA_DI_FN_DEP_64   = $(VRA_PATH_DIST_64)/$1
 VRA_DI_LIPO = lipo
else
 VRA_DI_FN_DEP_BOTH = $(VRA_PATH_DIST)/additions/$1
 ifeq ($(KBUILD_TARGET_ARCH),x86)
  VRA_DI_FN_DEP_32  = $(VRA_PATH_DIST)/additions/$1
  VRA_DI_FN_DEP_64  =
 else
  VRA_DI_FN_DEP_64  = $(VRA_PATH_DIST)/additions/$1
  VRA_DI_FN_DEP_32  =
 endif
endif

# Unset this to speed up things during makefile hacking.
VRA_DARWIN_INST_DEP_ON_MAKEFILE := $(MAKEFILE_CURRENT)

# The location of the pkgbuild program.
ifndef VRA_PKGBUILD
 VRA_PKGBUILD := pkgbuild
endif

# The location of the productbuild program.
ifndef VRA_PRODUCTBUILD
 VRA_PRODUCTBUILD := productbuild
endif

# Where we do the packing (override this in LocalConfig.kmk if building on smbfs).
ifndef VRA_PATH_PACK_TMP
 VRA_PATH_PACK_TMP := $(VRA_ADD_DI_OUT_DIR)
endif


#
# The packing.
#
PACKING += \
	$(PATH_STAGE)/$(INST_ADDITIONS)VBoxGuestAdditions.pkg \
	$(PATH_STAGE)/$(INST_ADDITIONS)VBoxDarwinAdditionsUninstall.tool

#OTHER_CLEAN = TODO


include $(FILE_KBUILD_SUB_FOOTER)


#
# We're running commands as root here, take some care and assertion
# a sane environment.
#
ifeq ($(strip $(VRA_PATH_DIST)),)
 $(error VRA_PATH_DIST=$(VRA_PATH_DIST))
endif
ifeq ($(strip $(VRA_PATH_DIST)),/)
 $(error VRA_PATH_DIST=$(VRA_PATH_DIST))
endif
ifeq ($(strip $(VRA_PATH_PACK_TMP)),)
 $(error VRA_PATH_PACK_TMP=$(VRA_PATH_PACK_TMP))
endif
ifeq ($(strip $(VRA_PATH_PACK_TMP)),/)
 $(error VRA_PATH_PACK_TMP=$(VRA_PATH_PACK_TMP))
endif

#
# The packing targets.
#
$(PATH_STAGE)/$(INST_ADDITIONS)VBoxGuestAdditions.pkg: $(VRA_PATH_PACK_TMP)/VBoxGuestAdditions.pkg
	$(MKDIR) -p "$(@D)"
	$(INSTALL) -m 0644 -- "$<" "$@"

$(PATH_STAGE)/$(INST_ADDITIONS)VBoxDarwinAdditionsUninstall.tool: $(VRA_ADD_PATH_DI_SRC)/DiskImage/Uninstall.tool
	$(MKDIR) -p "$(@D)"
	$(INSTALL) -m 0755 -- "$<" "$@"


#
# The meta-package.
#
$(VRA_PATH_PACK_TMP)/VBoxGuestAdditions.pkg: \
		$(VRA_PATH_PACK_TMP)/Packages/VBoxGuestAdditionsKEXTs.pkg \
		$(VRA_PATH_PACK_TMP)/Packages/VBoxGuestAdditionsToolsAndServices.pkg \
		$$(wildcard $(VRA_ADD_PATH_DI_SRC)/VBoxGuestAdditions_mpkg/* \
			$(VRA_ADD_PATH_DI_SRC)/VBoxGuestAdditions_mpkg/*.lproj/*) \
		$(foreach f,$(VRA_INSTALLER_ADD_LANGUAGES), $(VRA_BRAND_$(f)_VIRTUALBOX_WELCOME_RTF)) \
		$(VRA_ADD_PATH_DI_SRC)/VBoxGuestAdditions_mpkg/Welcome.rtf \
		$(VRA_ADD_PATH_DI_SRC)/VBoxGuestAdditions_mpkg/Conclusion.rtf \
		$(VRA_ADD_PATH_DI_SRC)/VBoxGuestAdditions_mpkg/distribution-$(KBUILD_TARGET_ARCH).dist \
		$(VRA_DARWIN_INST_DEP_ON_MAKEFILE)
	$(call MSG_TOOL,productbuild,,,$@)
	@# Cleanup any previously failed attempts.
	sudo rm -Rf \
		$@ \
		$(VRA_PATH_PACK_TMP)/VBoxDarwinAdditions.dist.root \
		$(VRA_PATH_PACK_TMP)/VBoxDarwinAdditions.dist.desc \
		$(VRA_PATH_PACK_TMP)/VBoxDarwinAdditions.dist.res
	@# Correct directory permissions are important.
	$(MKDIR) -p \
		$(@D) \
		$(VRA_PATH_PACK_TMP)/VBoxDarwinAdditions.dist.desc \
		$(VRA_PATH_PACK_TMP)/VBoxDarwinAdditions.dist.res \
		$(VRA_PATH_PACK_TMP)/VBoxDarwinAdditions.dist.res/English.lproj

	@# Do keyword replacement in the package info and description files.
	$(SED) \
		-e 's+@VRA_VERSION_STRING@+$(VRA_VERSION_STRING)+g' \
		-e 's+@VRA_VERSION_MAJOR@+$(VRA_VERSION_MAJOR)+g' \
		-e 's+@VRA_VERSION_MINOR@+$(VRA_VERSION_MINOR)+g' \
		-e 's+@VRA_VERSION_BUILD@+$(VRA_VERSION_BUILD)+g' \
		-e 's+@VRA_VENDOR@+$(VRA_VENDOR)+g' \
		-e 's+@VRA_PRODUCT@+$(VRA_PRODUCT)+g' \
		-e 's+@VRA_C_YEAR@+$(VRA_C_YEAR)+g' \
		--output $(VRA_PATH_PACK_TMP)/VBoxDarwinAdditions.dist.res/English.lproj/Welcome.rtf \
		$(VRA_ADD_PATH_DI_SRC)/VBoxGuestAdditions_mpkg/Welcome.rtf
	@# Copy the resources.
	$(INSTALL) -m 0644 $(VRA_ADD_PATH_DI_SRC)/VBoxGuestAdditions_mpkg/Conclusion.rtf $(VRA_PATH_PACK_TMP)/VBoxDarwinAdditions.dist.res/English.lproj/Conclusion.rtf

	$(SED) \
		-e 's+@VRA_VENDOR@+$(VRA_VENDOR)+g' \
		-e 's+@VRA_PRODUCT@+$(VRA_PRODUCT)+g' \
		-e 's+@VRA_C_YEAR@+$(VRA_C_YEAR)+g' \
		--output $(VRA_PATH_PACK_TMP)/VBoxDarwinAdditions.dist.res/English.lproj/Localizable.strings \
		$(VRA_ADD_PATH_DI_SRC)/VBoxGuestAdditions_mpkg/Localizable.strings
	$(INSTALL) -m 0644 $(VRA_BRAND_DARWIN_INSTALLER_BG)                          $(VRA_PATH_PACK_TMP)/VBoxDarwinAdditions.dist.res/background.tiff

	$(foreach f,$(VRA_INSTALLER_ADD_LANGUAGES), \
		$(MKDIR) -p \
			$(VRA_PATH_PACK_TMP)/VBoxDarwinAdditions.dist.res/$(VRA_INSTALLER_$(f)_DARWIN_TARGET).lproj$(NLTAB) \
		$(SED) \
			-e 's+@VRA_VERSION_STRING@+$(VRA_VERSION_STRING)+g' \
			-e 's+@VRA_VERSION_MAJOR@+$(VRA_VERSION_MAJOR)+g' \
			-e 's+@VRA_VERSION_MINOR@+$(VRA_VERSION_MINOR)+g' \
			-e 's+@VRA_VERSION_BUILD@+$(VRA_VERSION_BUILD)+g' \
			--output $(VRA_PATH_PACK_TMP)/VBoxDarwinAdditions.dist.res/$(VRA_INSTALLER_$(f)_DARWIN_TARGET).lproj/Welcome.rtf \
			$(VRA_BRAND_$(f)_VIRTUALBOX_WELCOME_RTF)$(NLTAB) \
		$(INSTALL) -m 0644 $(VRA_BRAND_$(f)_VIRTUALBOX_CONCLUSION_RTF)           $(VRA_PATH_PACK_TMP)/VBoxDarwinAdditions.dist.res/$(VRA_INSTALLER_$(f)_DARWIN_TARGET).lproj/Conclusion.rtf$(NLTAB) \
		$(SED) \
			-e 's+@VRA_VENDOR@+$(VRA_VENDOR)+g' \
			-e 's+@VRA_PRODUCT@+$(VRA_PRODUCT)+g' \
			-e 's+@VRA_C_YEAR@+$(VRA_C_YEAR)+g' \
			--output $(VRA_PATH_PACK_TMP)/VBoxDarwinAdditions.dist.res/$(VRA_INSTALLER_$(f)_DARWIN_TARGET).lproj/Localizable.strings \
			$(VRA_BRAND_$(f)_VIRTUALBOX_LOCALIZABLE_STRINGS)$(NLTAB) \
	)

	@# Build the package.
	$(VRA_PRODUCTBUILD) \
		--distribution $(VRA_ADD_PATH_DI_SRC)/VBoxGuestAdditions_mpkg/distribution-$(KBUILD_TARGET_ARCH).dist \
		--package-path $(VRA_PATH_PACK_TMP)/Packages \
		--resources $(VRA_PATH_PACK_TMP)/VBoxDarwinAdditions.dist.res \
		--identifier org.VirtualAgent.mpkg.GuestAdditions \
		--version $(VRA_VERSION_MAJOR).$(VRA_VERSION_MINOR).$(VRA_VERSION_BUILD) \
		$(if-expr defined(VRA_MACOSX_INSTALLER_SIGN) && $(intersects darwin all 1,$(VRA_WITH_CORP_CODE_SIGNING)) == "",--sign "$(VRA_MACOSX_INSTALLER_SIGN)",) \
		$@
ifdef VRA_SIGNING_MODE
 if $(intersects darwin all 1,$(VRA_WITH_CORP_CODE_SIGNING))
	@# Sign the created pkg.
	$(call VRA_SIGN_PKG_FN,$@,org.VirtualAgent.mpkg.GuestAdditions)
  if $(intersects darwin all 1,$(VRA_WITH_CORP_CODE_SIGNING))
	@# Notarize the signed pkg (includes stapling).
	$(call VRA_NOTARIZE_FILE_FN,$@,org.virtualbox.VBoxGuestAdditions.$(VRA_VERSION_MAJOR).$(VRA_VERSION_MINOR).$(VRA_VERSION_BUILD).$(VRA_SVN_REV))
  endif
 endif
endif

	@# Cleanup.
	sudo rm -Rf \
		$(VRA_PATH_PACK_TMP)/VBoxDarwinAdditions.dist.root \
		$(VRA_PATH_PACK_TMP)/VBoxDarwinAdditions.dist.desc \
		$(VRA_PATH_PACK_TMP)/VBoxDarwinAdditions.dist.res

VBoxDarwinAdditions.pkg:: $(VRA_PATH_PACK_TMP)/VBoxDarwinAdditions.pkg

#
# The VirtualAgent Kernel extensions.
#
VRA_ADD_DI_KEXTS_UNIVERSAL = VBoxGuest
VRA_ADD_DI_KEXTS = $(VRA_ADD_DI_KEXTS_UNIVERSAL)

$(VRA_PATH_PACK_TMP)/Packages/VBoxGuestAdditionsKEXTs.pkg: \
		$(foreach kext,$(VRA_ADD_DI_KEXTS_UNIVERSAL), $(call VRA_DI_FN_DEP_BOTH,$(kext).kext/Contents/MacOS/$(kext))) \
		$(foreach kext,$(VRA_ADD_DI_KEXTS), $(VRA_PATH_DIST)/additions/$(kext).kext/Contents/Info.plist) \
		$$(wildcard $(VRA_ADD_PATH_DI_SRC)/VBoxGuestAdditionsKEXTs/* \
			$(VRA_ADD_PATH_DI_SRC)/VBoxGuestAdditionsKEXTs/*.lproj/*) \
		$(foreach f,$(VRA_INSTALLER_ADD_LANGUAGES), \
			$(VRA_BRAND_$(f)_VRAKEXTS_DESCRIPTION_PLIST) \
			$(VRA_BRAND_$(f)_VRAKEXTS_README_HTML) \
			$(VRA_BRAND_$(f)_VRAKEXTS_INSTALLATIONCHECK_STRINGS)) \
		$(VRA_ADD_PATH_DI_SRC)/VBoxGuestAdditionsKEXTs/postflight \
		$(VRA_ADD_PATH_DI_SRC)/VBoxGuestAdditionsKEXTs/PkgBuildComponent.plist \
		$(VRA_DARWIN_INST_DEP_ON_MAKEFILE)
	$(call MSG_TOOL,pkgbuild,,,$@)
	@# Cleanup any previously failed attempts.
	sudo rm -Rf \
		$@ \
		$(VRA_PATH_PACK_TMP)/VBoxGuestAdditionsKEXTs.pkg.root \
		$(VRA_PATH_PACK_TMP)/VBoxGuestAdditionsKEXTs.pkg.desc \
		$(VRA_PATH_PACK_TMP)/VBoxGuestAdditionsKEXTs.pkg.res
	@# Correct directory permissions are important.
	$(MKDIR) -p \
		$(@D) \
		$(VRA_PATH_PACK_TMP)/VBoxGuestAdditionsKEXTs.pkg.desc \
		$(VRA_PATH_PACK_TMP)/VBoxGuestAdditionsKEXTs.pkg.res \
		$(VRA_PATH_PACK_TMP)/VBoxGuestAdditionsKEXTs.pkg.res/English.lproj
	$(MKDIR) -p -m 1775 $(VRA_PATH_PACK_TMP)/VBoxGuestAdditionsKEXTs.pkg.root/Library
	$(MKDIR) -p -m 0755 \
		$(VRA_PATH_PACK_TMP)/VBoxGuestAdditionsKEXTs.pkg.root/Library/Extensions \
		$(foreach kext,$(VRA_ADD_DI_KEXTS), \
			$(VRA_PATH_PACK_TMP)/VBoxGuestAdditionsKEXTs.pkg.root/Library/Extensions/$(kext).kext \
			$(VRA_PATH_PACK_TMP)/VBoxGuestAdditionsKEXTs.pkg.root/Library/Extensions/$(kext).kext/Contents \
			$(VRA_PATH_PACK_TMP)/VBoxGuestAdditionsKEXTs.pkg.root/Library/Extensions/$(kext).kext/Contents/MacOS )
	@# Copy the common files (Info.plist).
	$(foreach kext,$(VRA_ADD_DI_KEXTS), \
		$(NLTAB)$(INSTALL) -m 0644 $(VRA_PATH_DIST)/additions/$(kext).kext/Contents/Info.plist $(VRA_PATH_PACK_TMP)/VBoxGuestAdditionsKEXTs.pkg.root/Library/Extensions/$(kext).kext/Contents/)
	@# Copy the binaries and invoking lipo.
ifdef VRA_WITH_COMBINED_PACKAGE
	$(foreach kext,$(VRA_ADD_DI_KEXTS_UNIVERSAL), \
		$(NLTAB)$(VRA_DI_LIPO) -create \
			$(VRA_PATH_DIST_32)/additions/$(kext).kext/Contents/MacOS/$(kext) \
			$(VRA_PATH_DIST_64)/additions/$(kext).kext/Contents/MacOS/$(kext) \
			-output $(VRA_PATH_PACK_TMP)/VBoxGuestAdditionsKEXTs.pkg.root/Library/Extensions/$(kext).kext/Contents/MacOS/$(kext))
else
	$(foreach kext,$(VRA_ADD_DI_KEXTS), \
		$(NLTAB)$(INSTALL) -m 0755 $(VRA_PATH_DIST)/additions/$(kext).kext/Contents/MacOS/$(kext) $(VRA_PATH_PACK_TMP)/VBoxGuestAdditionsKEXTs.pkg.root/Library/Extensions/$(kext).kext/Contents/MacOS/)
endif
	@# Sign the kext bundles.
ifdef VRA_SIGNING_MODE
	$(foreach kext,$(VRA_ADD_DI_KEXTS), \
		$(NLTAB)$(call VRA_SIGN_BUNDLE_FN,$(VRA_PATH_PACK_TMP)/VBoxGuestAdditionsKEXTs.pkg.root/Library/Extensions/$(kext).kext,) \
		$(NLTAB)chmod a+r $(VRA_PATH_PACK_TMP)/VBoxGuestAdditionsKEXTs.pkg.root/Library/Extensions/$(kext).kext/Contents/_CodeSignature/* )
endif
	@# Set the correct owners.
	sudo chown    root:admin $(VRA_PATH_PACK_TMP)/VBoxGuestAdditionsKEXTs.pkg.root/Library
	sudo chown -R root:wheel $(VRA_PATH_PACK_TMP)/VBoxGuestAdditionsKEXTs.pkg.root/Library/Extensions

        # Copy package internal files
	$(INSTALL) $(VRA_ADD_PATH_DI_SRC)/VBoxGuestAdditionsKEXTs/PkgBuildComponent.plist $(VRA_PATH_PACK_TMP)/VBoxGuestAdditionsKEXTs.pkg.desc/PkgBuildComponent.plist

        # Copy installer scripts
	$(INSTALL) -m 0755 $(VRA_ADD_PATH_DI_SRC)/VBoxGuestAdditionsKEXTs/postflight $(VRA_PATH_PACK_TMP)/VBoxGuestAdditionsKEXTs.pkg.res

	@# Build the package.
	$(VRA_PKGBUILD) \
		--root   $(VRA_PATH_PACK_TMP)/VBoxGuestAdditionsKEXTs.pkg.root/Library/Extensions/ \
		--component-plist $(VRA_PATH_PACK_TMP)/VBoxGuestAdditionsKEXTs.pkg.desc/PkgBuildComponent.plist \
		--script $(VRA_PATH_PACK_TMP)/VBoxGuestAdditionsKEXTs.pkg.res \
		--identifier org.virtualbox.pkg.additions.kexts \
		--version $(VRA_VERSION_MAJOR).$(VRA_VERSION_MINOR).$(VRA_VERSION_BUILD) \
		--install-location /Library/Extensions/ \
		--ownership preserve \
		$(if-expr defined(VRA_MACOSX_INSTALLER_SIGN) && $(intersects darwin all 1,$(VRA_WITH_CORP_CODE_SIGNING)) == "",--sign "$(VRA_MACOSX_INSTALLER_SIGN)",) \
		$@
ifdef VRA_SIGNING_MODE
 if $(intersects darwin all 1,$(VRA_WITH_CORP_CODE_SIGNING))
	@# Sign the created pkg.
	$(call VRA_SIGN_PKG_FN,$@,org.virtualbox.pkg.vboxguestadditionskexts)
 endif
endif
	@# Cleanup
	sudo rm -Rf \
		$(VRA_PATH_PACK_TMP)/VBoxGuestAdditionsKEXTs.pkg.root \
		$(VRA_PATH_PACK_TMP)/VBoxGuestAdditionsKEXTs.pkg.desc \
		$(VRA_PATH_PACK_TMP)/VBoxGuestAdditionsKEXTs.pkg.res

#
# The VirtualAgent Guest Additions Tools & Services.
#

VRA_GA_PKG = VBoxGuestAdditionsToolsAndServices.pkg
VRA_DI_VB_GA_BINARIES = VBoxClient VBoxControl VBoxService
$(VRA_PATH_PACK_TMP)/Packages/$(VRA_GA_PKG): \
		$(foreach f, $(VRA_DI_VB_GA_BINARIES) \
			,$(call VRA_DI_FN_DEP_BOTH,$(f)) ) \
		$(VRA_ADD_PATH_DI_SRC)/VBoxGuestAdditionsToolsAndServices/org.virtualbox.additions.vboxclient.plist \
		$(VRA_ADD_PATH_DI_SRC)/VBoxGuestAdditionsToolsAndServices/org.virtualbox.additions.vboxservice.plist \
		$(VRA_ADD_PATH_DI_SRC)/VBoxGuestAdditionsToolsAndServices/VBoxServiceWrapper \
		$(VRA_ADD_PATH_DI_SRC)/DiskImage/Uninstall.tool \
		$(VRA_DARWIN_INST_DEP_ON_MAKEFILE)
	$(call MSG_TOOL,pkgbuild,,,$@)
	@# Cleanup any previously failed attempts.
	sudo rm -Rf \
		$@ \
		$(VRA_PATH_PACK_TMP)/$(VRA_GA_PKG).root \
		$(VRA_PATH_PACK_TMP)/$(VRA_GA_PKG).desc \
		$(VRA_PATH_PACK_TMP)/$(VRA_GA_PKG).res
	@# Correct directory permissions are important.
	$(MKDIR) -p \
		$(@D) \
		$(VRA_PATH_PACK_TMP)/$(VRA_GA_PKG).desc \
		$(VRA_PATH_PACK_TMP)/$(VRA_GA_PKG).res \
		$(VRA_PATH_PACK_TMP)/$(VRA_GA_PKG).res/English.lproj

	@# Create directory structure within a package w/ proper permittions
	$(MKDIR) -p -m 0775 \
	    "$(VRA_PATH_PACK_TMP)/$(VRA_GA_PKG).root/Library/Application Support/VirtualAgent Guest Additions" \
	    "$(VRA_PATH_PACK_TMP)/$(VRA_GA_PKG).root/Library/LaunchAgents" \
	    "$(VRA_PATH_PACK_TMP)/$(VRA_GA_PKG).root/Library/LaunchDaemons"

	@# Install binaries
ifdef VRA_WITH_COMBINED_PACKAGE
	$(foreach binary, $(VRA_DI_VB_GA_BINARIES) \
		,$(VRA_DI_LIPO) -create \
			$(VRA_PATH_DIST_32)/additions/$(binary) \
			$(VRA_PATH_DIST_64)/additions/$(binary) \
			-output "$(VRA_PATH_PACK_TMP)/$(VRA_GA_PKG).root/Library/Application Support/VirtualAgent Guest Additions/$(binary)"$(NLTAB))
	$(foreach binary, $(VRA_DI_VB_GA_BINARIES), \
		$(NLTAB)$(INSTALL) -m 0755 $(VRA_PATH_DIST_32)/additions/$(binary) "$(VRA_PATH_PACK_TMP)/$(VRA_GA_PKG).root/Library/Application Support/VirtualAgent Guest Additions/$(binary)-x86" \
		$(NLTAB)$(INSTALL) -m 0755 $(VRA_PATH_DIST_64)/additions/$(binary) "$(VRA_PATH_PACK_TMP)/$(VRA_GA_PKG).root/Library/Application Support/VirtualAgent Guest Additions/$(binary)-amd64" )
else
	$(foreach binary, $(VRA_DI_VB_GA_BINARIES) \
		,$(INSTALL) -m 0755 $(VRA_PATH_DIST)/additions/$(binary)           "$(VRA_PATH_PACK_TMP)/$(VRA_GA_PKG).root/Library/Application Support/VirtualAgent Guest Additions/$(binary)"$(NLTAB))
	$(foreach binary, $(VRA_DI_VB_GA_BINARIES) \
		,$(INSTALL) -m 0755 $(VRA_PATH_DIST)/additions/$(binary)           "$(VRA_PATH_PACK_TMP)/$(VRA_GA_PKG).root/Library/Application Support/VirtualAgent Guest Additions/$(binary)-$(KBUILD_TARGET_ARCH)"$(NLTAB))
endif
        # Add Uninstall.tool
	$(INSTALL) -m 0755 $(VRA_ADD_PATH_DI_SRC)/DiskImage/Uninstall.tool  "$(VRA_PATH_PACK_TMP)/$(VRA_GA_PKG).root/Library/Application Support/VirtualAgent Guest Additions/"
ifdef VRA_SIGNING_MODE
	$(call VRA_SIGN_FILE_FN,$(VRA_PATH_PACK_TMP)/$(VRA_GA_PKG).root/Library/Application Support/VirtualAgent Guest Additions/Uninstall.tool,org.virtualbox.app.guestadditions.uninstaller)
endif

	@# Install launchd stuff
	$(INSTALL) -m 0755 $(VRA_ADD_PATH_DI_SRC)/VBoxGuestAdditionsToolsAndServices/VBoxServiceWrapper \
	                                                                         "$(VRA_PATH_PACK_TMP)/$(VRA_GA_PKG).root/Library/Application Support/VirtualAgent Guest Additions/"
	$(INSTALL) -m 644 $(VRA_ADD_PATH_DI_SRC)/VBoxGuestAdditionsToolsAndServices/org.virtualbox.additions.vboxclient.plist \
	                                                                         "$(VRA_PATH_PACK_TMP)/$(VRA_GA_PKG).root/Library/LaunchAgents/"
	$(INSTALL) -m 644 $(VRA_ADD_PATH_DI_SRC)/VBoxGuestAdditionsToolsAndServices/org.virtualbox.additions.vboxservice.plist \
	                                                                         "$(VRA_PATH_PACK_TMP)/$(VRA_GA_PKG).root/Library/LaunchDaemons/"

	@# Sign the binaries.
ifdef VRA_SIGNING_MODE
 ifdef VRA_WITH_COMBINED_PACKAGE
	$(foreach binary, $(VRA_DI_VB_GA_BINARIES) \
		,$(NLTAB)$(call VRA_SIGN_MACHO_FN,$(VRA_PATH_PACK_TMP)/$(VRA_GA_PKG).root/Library/Application Support/VirtualAgent Guest Additions/$(binary),org.virtualbox.app.guestadditions.$(notdir $(binary))) )
	$(foreach binary, $(VRA_DI_VB_GA_BINARIES) \
		,$(NLTAB)$(call VRA_SIGN_MACHO_FN,$(VRA_PATH_PACK_TMP)/$(VRA_GA_PKG).root/Library/Application Support/VirtualAgent Guest Additions/$(binary)-x86,org.virtualbox.app.guestadditions.$(notdir $(binary))-x86) )
	$(foreach binary, $(VRA_DI_VB_GA_BINARIES) \
		,$(NLTAB)$(call VRA_SIGN_MACHO_FN,$(VRA_PATH_PACK_TMP)/$(VRA_GA_PKG).root/Library/Application Support/VirtualAgent Guest Additions/$(binary)-amd64,org.virtualbox.app.guestadditions.$(notdir $(binary))-amd64) )
 else
	$(foreach binary, $(VRA_DI_VB_GA_BINARIES) \
		,$(NLTAB)$(call VRA_SIGN_MACHO_FN,$(VRA_PATH_PACK_TMP)/$(VRA_GA_PKG).root/Library/Application Support/VirtualAgent Guest Additions/$(binary),org.virtualbox.app.guestadditions.$(notdir $(binary))) )
	$(foreach binary, $(VRA_DI_VB_GA_BINARIES) \
		,$(NLTAB)$(call VRA_SIGN_MACHO_FN,$(VRA_PATH_PACK_TMP)/$(VRA_GA_PKG).root/Library/Application Support/VirtualAgent Guest Additions/$(binary)-$(KBUILD_TARGET_ARCH),org.virtualbox.app.guestadditions.$(notdir $(binary))-$(KBUILD_TARGET_ARCH)) )
 endif
endif

	@# Correct ownership
	sudo chown -R root:wheel "$(VRA_PATH_PACK_TMP)/$(VRA_GA_PKG).root/Library/"

	@# Build the package.
	$(VRA_PKGBUILD) \
		--root   "$(VRA_PATH_PACK_TMP)/$(VRA_GA_PKG).root/Library/" \
		--script $(VRA_PATH_PACK_TMP)/$(VRA_GA_PKG).res \
		--identifier org.virtualbox.pkg.additions.tools-and-services \
		--version $(VRA_VERSION_MAJOR).$(VRA_VERSION_MINOR).$(VRA_VERSION_BUILD) \
		--install-location "/Library/" \
		--ownership preserve \
		$(if-expr defined(VRA_MACOSX_INSTALLER_SIGN) && $(intersects darwin all 1,$(VRA_WITH_CORP_CODE_SIGNING)) == "",--sign "$(VRA_MACOSX_INSTALLER_SIGN)",) \
		$@
ifdef VRA_SIGNING_MODE
 if $(intersects darwin all 1,$(VRA_WITH_CORP_CODE_SIGNING))
	@# Sign the created pkg.
	$(call VRA_SIGN_PKG_FN,$@,org.virtualbox.pkg.vboxguestadditions)
 endif
endif
	@# Cleanup
	sudo rm -Rf \
		$(VRA_PATH_PACK_TMP)/$(VRA_GA_PKG).root \
		$(VRA_PATH_PACK_TMP)/$(VRA_GA_PKG).desc \
		$(VRA_PATH_PACK_TMP)/$(VRA_GA_PKG).res
