# $Id: Makefile.kmk 113056 2026-02-17 10:38:41Z alexander.eichner@oracle.com $
## @file
# Sub-Makefile for the device testcases.
#

#
# Copyright (C) 2006-2026 CINASEEK and/or its affiliates.
#
# This file is part of VirtualAgent base platform packages, as
# available from https://www.virtualbox.org.
#
# This program is free software; you can redistribute it and/or
# modify it under the terms of the GNU General Public License
# as published by the Free Software Foundation, in version 3 of the
# License.
#
# This program is distributed in the hope that it will be useful, but
# WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
# General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, see <https://www.gnu.org/licenses>.
#
# SPDX-License-Identifier: GPL-3.0-only
#

SUB_DEPTH = ../../../..
include $(KBUILD_PATH)/subheader.kmk

#
# Globals
#
VRA_PATH_DEVICES_SRC ?= $(PATH_ROOT)/src/VBox/Devices
VRA_PATH_VMM_DEVICES_SRC ?= $(PATH_ROOT)/src/VBox/VMM/include
VRA_DEVICES_TEST_OUT_DIR := $(PATH_TARGET)/Devices/testcase
BLDDIRS += $(VRA_DEVICES_TEST_OUT_DIR)

VRA_DEVICES_TESTS_FEATURES = \
	$(if $(VRA_WITH_AHCI),VRA_WITH_AHCI,) \
	$(if $(VRA_WITH_BUSLOGIC),VRA_WITH_BUSLOGIC,) \
	$(if $(VRA_WITH_E1000),VRA_WITH_E1000,) \
	$(if $(VRA_WITH_EHCI_IMPL),VRA_WITH_EHCI_IMPL,) \
	$(if $(VRA_WITH_HGSMI),VRA_WITH_HGSMI,) \
	$(if $(VRA_WITH_HP_HDA),VRA_WITH_HP_HDA,) \
	$(if $(VRA_WITH_INTEL_HDA),VRA_WITH_INTEL_HDA,) \
	$(if $(VRA_WITH_NVIDIA_HDA),VRA_WITH_NVIDIA_HDA,) \
	$(if $(VRA_WITH_LSILOGIC),VRA_WITH_LSILOGIC,) \
	$(if $(VRA_WITH_NVME_IMPL),VRA_WITH_NVME_IMPL,) \
	$(if $(VRA_WITH_RAW_MODE),VRA_WITH_RAW_MODE,) \
	$(if $(VRA_WITH_SCSI),VRA_WITH_SCSI,) \
	$(if $(VRA_WITH_USB),VRA_WITH_USB,) \
	$(if $(VRA_WITH_VDMA),VRA_WITH_VDMA,) \
	$(if $(VRA_WITH_VIRTIO),VRA_WITH_VIRTIO,) \
	$(if $(VRA_WITH_VMSVGA),VRA_WITH_VMSVGA,) \
	$(if $(VRA_WITH_WDDM),VRA_WITH_WDDM,) \
	$(if $(VRA_WITH_XHCI_IMPL),VRA_WITH_XHCI_IMPL,) \
	$(if $(VRA_WITH_IOMMU_AMD),VRA_WITH_IOMMU_AMD,) \
	$(if $(VRA_WITH_IOMMU_INTEL),VRA_WITH_IOMMU_INTEL,) \
	$(VRA_AUDIO_DEFS) \
	$(VMM_COMMON_DEFS)

#
# We setup one 'other' target for executing the structure & alignment
# validation testcases. Perhaps a bit hackish, but extremely useful.
#
ifeq ($(KBUILD_TARGET),$(KBUILD_HOST))
 ifeq ($(filter-out x86.x86 amd64.amd64 x86.amd64, $(KBUILD_TARGET_ARCH).$(KBUILD_HOST_ARCH)),)
  OTHERS += \
  	$(VRA_DEVICES_TEST_OUT_DIR)/tstDeviceStructSize.run
 endif
endif

# The normal testing pass.
TESTING += \
	$(VRA_DEVICES_TEST_OUT_DIR)/tstDeviceStructSize.run

ifdef VRA_WITH_RAW_MODE
 #
 # The testcase generator.
 #
 PROGRAMS += tstDeviceStructSizeRC
 tstDeviceStructSizeRC_TEMPLATE  = VBoxRcExe
 tstDeviceStructSizeRC_DEFS      = $(VRA_DEVICES_TESTS_FEATURES)
 tstDeviceStructSizeRC_SOURCES   = tstDeviceStructSizeRC.cpp
 tstDeviceStructSizeRC_INCS      = \
 	$(VRA_PATH_DEVICES_SRC)/build \
 	$(VRA_PATH_DEVICES_SRC)/Bus \
 	$(VRA_DEVICES_TEST_OUT_DIR) \
 	$(VRA_GRAPHICS_INCS)
 tstDeviceStructSizeRC_INCS     += $(VRA_PATH_VMM_DEVICES_SRC)
endif # VRA_WITH_RAW_MODE

#
# The testcase it self.
#
PROGRAMS += tstDeviceStructSize
if "$(KBUILD_TARGET)" != "win" && $(VRA_GCC_VERSION_CXX) < 40600
 #
 # Disable "ISO C++ prohibits anonymous structs [-Werror=pedantic]" caused by Mesa VMSVGA driver headers
 # For GCC >= 4.6.0 the warning is disabled in DevVGA_SVGA.h
 #
 # Template used for gcc older than 4.6.  (Strips away compiler options.)
 #
 TEMPLATE_tstDeviceStructSizeOldGCC         := tstDeviceStructSizeOldGCC
 TEMPLATE_tstDeviceStructSizeOldGCC_EXTENDS := VBoxR3AutoTest
 TEMPLATE_tstDeviceStructSizeOldGCC_CXXFLAGS = $(filter-out -pedantic,$(TEMPLATE_$(TEMPLATE_tstDeviceStructSizeOldGCC_EXTENDS)_CXXFLAGS))

 tstDeviceStructSize_TEMPLATE = tstDeviceStructSizeOldGCC
else
 tstDeviceStructSize_TEMPLATE = VBoxR3AutoTest
endif
tstDeviceStructSize_DEFS     = $(VRA_DEVICES_TESTS_FEATURES)
tstDeviceStructSize_INCS     = \
	$(VRA_PATH_DEVICES_SRC)/build \
	$(VRA_PATH_DEVICES_SRC)/Bus \
	$(VRA_DEVICES_TEST_OUT_DIR) \
	$(VRA_GRAPHICS_INCS) \
	$(VRA_PATH_VMSVGA_DEVICE_INC)
tstDeviceStructSize_SOURCES  = tstDeviceStructSize.cpp
tstDeviceStructSize_CLEAN    = \
	$(VRA_DEVICES_TEST_OUT_DIR)/tstDeviceStructSizeRC.h \
	$(VRA_DEVICES_TEST_OUT_DIR)/tstDeviceStructSize.run
ifdef VRA_WITH_RAW_MODE
 tstDeviceStructSize.cpp_DEPS = $(VRA_DEVICES_TEST_OUT_DIR)/tstDeviceStructSizeRC.h
endif
tstDeviceStructSize_INCS      += $(VRA_PATH_VMM_DEVICES_SRC)

#
# Run rule for tstDeviceStructSize.
#

# 1. Dump selected structure in the VMMRC.rc debug info.
# 2. Generate a testcase from the dump
## future

ifdef VRA_WITH_RAW_MODE
 # 1&2. Manually dump selected structures and members.
 $(VRA_DEVICES_TEST_OUT_DIR)/tstDeviceStructSizeRC.h: $$(tstDeviceStructSizeRC_1_STAGE_TARGET) | $$(dir $$@)
	$(call MSG_GENERATE,,$@)
	$(QUIET)$(REDIRECT) -wo $@ -- $^
endif

# 3. run it.
$(VRA_DEVICES_TEST_OUT_DIR)/tstDeviceStructSize.run: \
		$$(tstDeviceStructSize_1_STAGE_TARGET) \
		| $$(dir $$@) $$(VRA_RUN_TARGET_ORDER_DEPS)
	$(QUIET)$(RM) -f $@
	$^
	$(QUIET)$(APPEND) "$@" "done"

# alias for the struct test.
run-struct-tests: $(VRA_DEVICES_TEST_OUT_DIR)/tstDeviceStructSize.run


include $(FILE_KBUILD_SUB_FOOTER)

