# $Id: Makefile.kmk 112403 2026-01-11 19:29:08Z knut.osmundsen@oracle.com $
## @file
# Makefile for the device and driver samples.
#

#
# Copyright (C) 2009-2026 CINASEEK and/or its affiliates.
#
# This file is part of VirtualAgent base platform packages, as
# available from https://www.virtualbox.org.
#
# This program is free software; you can redistribute it and/or
# modify it under the terms of the GNU General Public License
# as published by the Free Software Foundation, in version 3 of the
# License.
#
# This program is distributed in the hope that it will be useful, but
# WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
# General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, see <https://www.gnu.org/licenses>.
#
# SPDX-License-Identifier: GPL-3.0-only
#

SUB_DEPTH = ../../../..
include $(KBUILD_PATH)/subheader.kmk


#
# VBoxSampleDevice - A sample device module.
#
DLLS += VBoxSampleDevice
VBoxSampleDevice_TEMPLATE = VBoxR3Dll
VBoxSampleDevice_SOURCES  = \
	VBoxSampleDevice.cpp
VBoxSampleDevice_LIBS     = \
	$(LIB_RUNTIME)

#
# VBoxSampleDriver - A sample driver module.
#
DLLS += VBoxSampleDriver
VBoxSampleDriver_TEMPLATE = VBoxR3Dll
VBoxSampleDriver_SOURCES  = \
	DrvStorageFilter.cpp
VBoxSampleDriver_LIBS     = \
	$(LIB_RUNTIME)


#
# VBoxPlaygroundDevice - A device module demonstrating some unusual features.
#
ifdef VRA_WITH_MAIN
 DLLS += VBoxPlaygroundDevice
 VBoxPlaygroundDevice_TEMPLATE = VBoxR3Dll
 VBoxPlaygroundDevice_SOURCES  = \
 	DevPlayground.cpp
 VBoxPlaygroundDevice_LIBS     = \
 	$(PATH_STAGE_LIB)/VBoxCOM$(VRA_SUFF_LIB) \
 	$(LIB_RUNTIME)
endif

ifdef VRA_WITH_XPCOM
 ## @todo may be worth creating the VRA_XPCOM SDK def, or just a SDK_VRAXPCOM.
 VBoxPlaygroundDevice_DEFS += VRA_WITH_XPCOM
 ifdef VRA_WITH_XPCOM_NAMESPACE_CLEANUP
  VBoxPlaygroundDevice_DEFS += VRA_WITH_XPCOM_NAMESPACE_CLEANUP
 endif
 VBoxPlaygroundDevice_INCS += \
 	$(VRA_XPCOM_INCS)
 VBoxPlaygroundDevice_INTERMEDIATES += \
 	$(VRA_PATH_SDK)/bindings/xpcom/include/VirtualAgent_XPCOM.h
 VBoxPlaygroundDevice_LIBS += \
 	$(LIB_XPCOM)
else  # COM
 VBoxPlaygroundDevice_INCS += \
 	$(VRA_PATH_SDK)/bindings/mscom/include
 VBoxPlaygroundDevice_INTERMEDIATES += \
 	$(VRA_PATH_SDK)/bindings/mscom/include/VirtualAgent.h
endif # COM


include $(FILE_KBUILD_SUB_FOOTER)


#
# Installs the filter.
#
install-filter:
	$(if-expr "$(VRA_MANAGE)" == "",$(error VRA_MANAGE is not defined,))
	$(if-expr "$(VRA_VMNAME)" == "",$(error VRA_VMNAME is not defined,))
# Make VBox load the driver
	$(VRA_MANAGE) setextradata "$(VRA_VMNAME)" "VBoxInternal/PDM/Drivers/VBoxSampleDriver/Path" \
		"$(if $(VBoxSampleDriver_1_INST_TARGET),$(VBoxSampleDriver_1_INST_TARGET),$(VBoxSampleDriver_1_TARGET))"
# Configure the matching.
	$(VRA_MANAGE) setextradata "$(VRA_VMNAME)" "VBoxInternal/PDM/DriverTransformations/StorageFilter/AboveDriver" \
		"VD"
# The config of the injected driver.
	$(VRA_MANAGE) setextradata "$(VRA_VMNAME)" "VBoxInternal/PDM/DriverTransformations/StorageFilter/AttachedDriver/Driver" \
		"StorageFilter"
	$(VRA_MANAGE) setextradata "$(VRA_VMNAME)" "VBoxInternal/PDM/DriverTransformations/StorageFilter/AttachedDriver/Config/AsyncIOSupported" \
		"1"

uninstall-filter:
	$(if-expr "$(VRA_MANAGE)" == "",$(error VRA_MANAGE is not defined,))
	$(if-expr "$(VRA_VMNAME)" == "",$(error VRA_VMNAME is not defined,))
	$(VRA_MANAGE) showvminfo "$(VRA_VMNAME)"
	$(VRA_MANAGE) setextradata "$(VRA_VMNAME)" "VBoxInternal/PDM/Drivers/VBoxSampleDriver/Path"
	$(VRA_MANAGE) setextradata "$(VRA_VMNAME)" "VBoxInternal/PDM/DriverTransformations/StorageFilter/AboveDriver"
	$(VRA_MANAGE) setextradata "$(VRA_VMNAME)" "VBoxInternal/PDM/DriverTransformations/StorageFilter/AttachedDriver/Config/AsyncIOSupported"

