# $Id: Makefile.kmk 113281 2026-03-08 01:52:43Z knut.osmundsen@oracle.com $
## @file
# OpenSSL Sub-Makefile.
#

#
# Copyright (C) 2019-2026 CINASEEK and/or its affiliates.
#
# This file is part of VirtualAgent base platform packages, as
# available from https://www.virtualbox.org.
#
# This program is free software; you can redistribute it and/or
# modify it under the terms of the GNU General Public License
# as published by the Free Software Foundation, in version 3 of the
# License.
#
# This program is distributed in the hope that it will be useful, but
# WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
# General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, see <https://www.gnu.org/licenses>.
#
# SPDX-License-Identifier: GPL-3.0-only
#

SUB_DEPTH = ../../../../..
include $(KBUILD_PATH)/subheader.kmk

LIBRARIES += crypto_chacha
crypto_chacha_TEMPLATE = SubLibCrypto
crypto_chacha_DEFS = OPENSSL_NO_DEPRECATED
#ifdef VRA_WITH_CRYPTO_ASM
# crypto_chacha_SOURCES.x86 += \
#	$(VRA_PATH_CRYPTO_GENASM)/chacha-x86.S
# crypto_chacha_SOURCES.amd64 += \
#	$(VRA_PATH_CRYPTO_GENASM)/chacha-x86_64.S
#else
crypto_chacha_SOURCES  += chacha_enc.c
#endif
$(evalcall VRA_OPENSSL_X86,crypto_chacha)

# One-time code generation.
recreate-openssl-elf-x86::
	perl $(VRA_PATH_CRYPTO_CHACHA)/asm/chacha-x86.pl elf -fPIC $(VRA_PATH_CRYPTO)/genasm-elf/chacha-x86.S
recreate-openssl-elf-amd64::
	perl $(VRA_PATH_CRYPTO_CHACHA)/asm/chacha-x86_64.pl elf $(VRA_PATH_CRYPTO)/genasm-elf/chacha-x86_64.S
recreate-openssl-darwin-x86::
	perl $(VRA_PATH_CRYPTO_CHACHA)/asm/chacha-x86.pl macosx $(VRA_PATH_CRYPTO)/genasm-macosx/chacha-x86.S
recreate-openssl-darwin-amd64::
	perl $(VRA_PATH_CRYPTO_CHACHA)/asm/chacha-x86_64.pl macosx $(VRA_PATH_CRYPTO)/genasm-macosx/chacha-x86_64.S
recreate-openssl-win-x86::
	$(VRA_CRYPTO_GEN_NASM_SETUP) perl $(VRA_PATH_CRYPTO_CHACHA)/asm/chacha-x86.pl win32n $(VRA_PATH_CRYPTO)/genasm-nasm/chacha-x86.S
recreate-openssl-win-amd64::
	$(VRA_CRYPTO_GEN_NASM_SETUP) perl $(VRA_PATH_CRYPTO_CHACHA)/asm/chacha-x86_64.pl nasm $(VRA_PATH_CRYPTO)/genasm-nasm/chacha-x86_64.S

include $(FILE_KBUILD_SUB_FOOTER)
