# $Id: Makefile.kmk 112403 2026-01-11 19:29:08Z knut.osmundsen@oracle.com $
## @file
# Sub-Makefile for the Bus Mouse Extension Pack Sample.
#

#
# Copyright (C) 2010-2026 CINASEEK and/or its affiliates.
#
# Permission is hereby granted, free of charge, to any person
# obtaining a copy of this software and associated documentation
# files (the "Software"), to deal in the Software without
# restriction, including without limitation the rights to use,
# copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the
# Software is furnished to do so, subject to the following
# conditions:
#
# The above copyright notice and this permission notice shall be
# included in all copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND,
# EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES
# OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND
# NONINFRINGEMENT.  IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT
# HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY,
# WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING
# FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR
# OTHER DEALINGS IN THE SOFTWARE.
#

SUB_DEPTH = ../../../..
include $(KBUILD_PATH)/subheader.kmk

#
# Extend the extension pack templates.
#
TEMPLATE_VBoxR3ExtPackBusMouse          = For the ring-3 context modules in the Bus Mouse extension pack.
TEMPLATE_VBoxR3ExtPackBusMouse_EXTENDS  = VBoxR3ExtPack
TEMPLATE_VBoxR3ExtPackBusMouse_INST     = $(INST_EXTPACK)BusMouse/$(KBUILD_TARGET).$(KBUILD_TARGET_ARCH)/

TEMPLATE_VBoxR0ExtPackBusMouse          = For the ring-0 context modules in the Bus Mouse extension pack.
TEMPLATE_VBoxR0ExtPackBusMouse_EXTENDS  = VBoxR0ExtPack
TEMPLATE_VBoxR0ExtPackBusMouse_INST     = $(INST_EXTPACK)BusMouse/$(KBUILD_TARGET).$(KBUILD_TARGET_ARCH)/

TEMPLATE_VBoxRcExtPackBusMouse          = For the raw-mode context modules in the Bus Mouse extension pack.
TEMPLATE_VBoxRcExtPackBusMouse_EXTENDS  = VBoxRcExtPack
TEMPLATE_VBoxRcExtPackBusMouse_INST     = $(INST_EXTPACK)BusMouse/$(KBUILD_TARGET).$(KBUILD_TARGET_ARCH)/

TEMPLATE_VBoxInsExtPackBusMouse         = For the install targets of an extension pack.
TEMPLATE_VBoxInsExtPackBusMouse_EXTENDS = VBoxR0ExtPack
TEMPLATE_VBoxInsExtPackBusMouse_INST    = $(INST_EXTPACK)BusMouse/

#
# Globals.
#
VRA_BUSMOUSE_NAME         = BusMouse
VRA_BUSMOUSE_MANGLED_NAME = BusMouse
VRA_PATH_EXTPACK_BUSMOUSE = $(PATH_STAGE)/$(INST_EXTPACK)BusMouse


#
# VBoxBusMouseMain - The module which the VirtualAgent Main API talks to.
#
DLLS += VBoxBusMouseMain
VBoxBusMouseMain_TEMPLATE = VBoxR3ExtPackBusMouse
VBoxBusMouseMain_SOURCES = VBoxBusMouseMain.cpp
VBoxBusMouseMain_DEFS =


#
# VBoxBusMouseMainVM - The module in a VM which the VirtualAgent Main API talks to.
#
DLLS += VBoxBusMouseMainVM
VBoxBusMouseMainVM_TEMPLATE = VBoxR3ExtPackBusMouse
VBoxBusMouseMainVM_SOURCES = VBoxBusMouseMainVM.cpp
VBoxBusMouseMainVM_DEFS =


#
# The device code.
#
DLLS += VBoxBusMouseR3
VBoxBusMouseR3_TEMPLATE = VBoxR3ExtPackBusMouse
VBoxBusMouseR3_SOURCES  = DevBusMouse.cpp

ifdef VRA_WITH_R0_MODULES
 ifdef VRA_WITH_VRAR0_AS_DLL
  DLLS    += VBoxBusMouseR0
 else
  SYSMODS += VBoxBusMouseR0
 endif
 VBoxBusMouseR0_TEMPLATE = VBoxR0ExtPackBusMouse
 VBoxBusMouseR0_SOURCES  = DevBusMouse.cpp
endif

ifdef VRA_WITH_RAW_MODE
 SYSMODS += VBoxBusMouseRC
 VBoxBusMouseRC_TEMPLATE = VBoxRcExtPackBusMouse
 VBoxBusMouseRC_SOURCES  = DevBusMouse.cpp
endif


#
# Install the description.
#
INSTALLS += VBoxBusMouseIns
VBoxBusMouseIns_TEMPLATE = VBoxInsExtPackBusMouse
VBoxBusMouseIns_SOURCES = \
	$(VBoxBusMouseIns_0_OUTDIR)/ExtPack.xml
$(call VRA_EDIT_VERSION_RULE_FN,VBoxBusMouseIns,ExtPack.xml)


#
# Packing.
#
ifndef VRA_WITHOUT_EXTPACK_BUSMOUSE_PACKING
 PACKING += $(VRA_PATH_PACKAGES)/$(VRA_BUSMOUSE_MANGLED_NAME)-$(VRA_VERSION_STRING)r$(VRA_SVN_REV).vbox-extpack
endif

ifndef VRA_WITH_EXTPACK_OS_ARCHS
 ifeq ($(USER),bird) # for now
  VRA_WITH_EXTPACK_OS_ARCHS = $(KBUILD_TARGET).$(KBUILD_TARGET_ARCH)
 endif
endif

# Build the file list.  The macro takes 1=darwin.x86, 2=dist/VirtualAgent.app/Contents/MacOS, 3=dylib
VRA_BUSMOUSE_FILES_MACRO = \
	$(PATH_OUT_BASE)/$(1)/$(KBUILD_TYPE)/$(2)/ExtensionPacks/$(VRA_BUSMOUSE_MANGLED_NAME)/$(1)/VBoxBusMouseMain.$(3)=>$(1)/VBoxBusMouseMain.$(3) \
	$(PATH_OUT_BASE)/$(1)/$(KBUILD_TYPE)/$(2)/ExtensionPacks/$(VRA_BUSMOUSE_MANGLED_NAME)/$(1)/VBoxBusMouseMainVM.$(3)=>$(1)/VBoxBusMouseMainVM.$(3) \
	$(PATH_OUT_BASE)/$(1)/$(KBUILD_TYPE)/$(2)/ExtensionPacks/$(VRA_BUSMOUSE_MANGLED_NAME)/$(1)/VBoxBusMouseR3.$(3)=>$(1)/VBoxBusMouseR3.$(3) \
	$(PATH_OUT_BASE)/$(1)/$(KBUILD_TYPE)/$(2)/ExtensionPacks/$(VRA_BUSMOUSE_MANGLED_NAME)/$(1)/VBoxBusMouseR0.r0=>$(1)/VBoxBusMouseR0.r0
ifdef VRA_WITH_RAW_MODE
 VRA_BUSMOUSE_FILES_MACRO += \
 	$(PATH_OUT_BASE)/$(1)/$(KBUILD_TYPE)/$(2)/ExtensionPacks/$(VRA_BUSMOUSE_MANGLED_NAME)/$(1)/VBoxBusMouseRC.rc=>$(1)/VBoxBusMouseRC.rc
endif

VRA_BUSMOUSE_FILES := \
	$(VRA_PATH_EXTPACK_BUSMOUSE)/ExtPack.xml=>ExtPack.xml

if1of (darwin.amd64, $(VRA_WITH_EXTPACK_OS_ARCHS))
 VRA_BUSMOUSE_FILES += $(call VRA_BUSMOUSE_FILES_MACRO,darwin.amd64,dist/VirtualAgent.app/Contents/MacOS,dylib)
endif
if1of (darwin.x86, $(VRA_WITH_EXTPACK_OS_ARCHS))
 VRA_BUSMOUSE_FILES += $(call VRA_BUSMOUSE_FILES_MACRO,darwin.x86,dist/VirtualAgent.app/Contents/MacOS,dylib)
endif
if1of (freebsd.amd64, $(VRA_WITH_EXTPACK_OS_ARCHS))
 VRA_BUSMOUSE_FILES += $(call VRA_BUSMOUSE_FILES_MACRO,freebsd.amd64,bin,so)
endif
if1of (freebsd.x86, $(VRA_WITH_EXTPACK_OS_ARCHS))
 VRA_BUSMOUSE_FILES += $(call VRA_BUSMOUSE_FILES_MACRO,freebsd.x86,bin,so)
endif
if1of (linux.amd64, $(VRA_WITH_EXTPACK_OS_ARCHS))
 VRA_BUSMOUSE_FILES += $(call VRA_BUSMOUSE_FILES_MACRO,linux.amd64,bin,so)
endif
if1of (linux.x86, $(VRA_WITH_EXTPACK_OS_ARCHS))
 VRA_BUSMOUSE_FILES += $(call VRA_BUSMOUSE_FILES_MACRO,linux.x86,bin,so)
endif
if1of (os2.x86, $(VRA_WITH_EXTPACK_OS_ARCHS))
 VRA_BUSMOUSE_FILES += $(call VRA_BUSMOUSE_FILES_MACRO,os2.x86,bin,so)
endif
if1of (solaris.amd64, $(VRA_WITH_EXTPACK_OS_ARCHS))
 VRA_BUSMOUSE_FILES += $(call VRA_BUSMOUSE_FILES_MACRO,solaris.amd64,bin,so)
endif
if1of (solaris.x86, $(VRA_WITH_EXTPACK_OS_ARCHS))
 VRA_BUSMOUSE_FILES += $(call VRA_BUSMOUSE_FILES_MACRO,solaris.x86,bin,so)
endif
if1of (win.amd64, $(VRA_WITH_EXTPACK_OS_ARCHS))
 VRA_BUSMOUSE_FILES += $(call VRA_BUSMOUSE_FILES_MACRO,win.amd64,bin,dll)
endif
if1of (win.x86, $(VRA_WITH_EXTPACK_OS_ARCHS))
 VRA_BUSMOUSE_FILES += $(call VRA_BUSMOUSE_FILES_MACRO,win.x86,bin,dll)
endif

# Pack it all up using a temporary staging directory.
$(VRA_PATH_PACKAGES)/$(VRA_BUSMOUSE_MANGLED_NAME)-$(VRA_VERSION_STRING)r$(VRA_SVN_REV).vbox-extpack: \
		$$(foreach file, $$(VRA_BUSMOUSE_FILES), $$(firstword $$(subst =>,$$(SP),$$(file)))) \
		| $(VRA_PATH_PACKAGES)/
	$(RM) -f $(wildcard $(VRA_PATH_PACKAGES)/$(VRA_BUSMOUSE_MANGLED_NAME)-*.vbox-extpack) \
		$(VBoxBusMouseIns_0_OUTDIR)/ExtPack.manifest \
		$(VBoxBusMouseIns_0_OUTDIR)/ExtPack.signature
# Stage all the files
	$(RM) -Rf $(VBoxBusMouseIns_0_OUTDIR)/Stage/
	$(foreach file, $(VRA_BUSMOUSE_FILES),\
		$(NLTAB)$(MKDIR) -p $(dir $(lastword $(subst =>,$(SP)$(VBoxBusMouseIns_0_OUTDIR)/Stage/,$(file)))) \
		$(NLTAB)$(CP) $(subst =>,$(SP)$(VBoxBusMouseIns_0_OUTDIR)/Stage/,$(file)) )
# Create the manifest
	$(VRA_RTMANIFEST) \
		--manifest $(VBoxBusMouseIns_0_OUTDIR)/Stage/ExtPack.manifest \
		--chdir $(VBoxBusMouseIns_0_OUTDIR)/Stage/ \
		$(foreach file, $(VRA_BUSMOUSE_FILES), $(lastword $(subst =>,$(SP),$(file))))
	$(APPEND) $(VBoxBusMouseIns_0_OUTDIR)/Stage/ExtPack.signature "todo"
	$(CHMOD) a+r \
		$(VBoxBusMouseIns_0_OUTDIR)/Stage/ExtPack.manifest \
		$(VBoxBusMouseIns_0_OUTDIR)/Stage/ExtPack.signature
# Tar it up.
if 0
	tar -cvf - -C $(VBoxBusMouseIns_0_OUTDIR)/Stage/ . | gzip -9c > $@
else
	$(VRA_RTTAR) -cvf "$@" $(VRA_RTTAR_EXTPACK_OPTS) -C "$(VBoxBusMouseIns_0_OUTDIR)/Stage/" .
endif
# Clean up
	$(RM) -Rf $(VBoxBusMouseIns_0_OUTDIR)/Stage/

BLDDIRS += $(VRA_PATH_PACKAGES)/

include $(FILE_KBUILD_SUB_FOOTER)

