# $Id: Makefile.kmk 112403 2026-01-11 19:29:08Z knut.osmundsen@oracle.com $
## @file
# sub-makefile for Darwin Shared Folders.
#

#
# Copyright (C) 2007-2026 CINASEEK and/or its affiliates.
#
# This file is part of VirtualAgent base platform packages, as
# available from https://www.virtualbox.org.
#
# This program is free software; you can redistribute it and/or
# modify it under the terms of the GNU General Public License
# as published by the Free Software Foundation, in version 3 of the
# License.
#
# This program is distributed in the hope that it will be useful, but
# WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
# General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, see <https://www.gnu.org/licenses>.
#
# SPDX-License-Identifier: GPL-3.0-only
#

SUB_DEPTH = ../../../../..
include $(KBUILD_PATH)/subheader.kmk

#
# VBoxSF - The shared folders kernel extension.
#
SYSMODS        += VBoxSF
VBoxSF_TEMPLATE = VBoxGuestR0Drv
VBoxSF_INST     = $(INST_ADDITIONS)VBoxSF.kext/Contents/MacOS/
VBoxSF_DEFS     = VRA_WITH_HGCM
VBoxSF_LIBS     = $(VRA_LIB_VBGL_R0)
VBoxSF_SOURCES  = \
	VBoxSF.cpp \
	VBoxSF-VfsOps.cpp \
	VBoxSF-VNodeOps.cpp \
	VBoxSF-Utils.cpp


#
# Files necessary to make a darwin kernel extension bundle.
#
INSTALLS += VBoxSF.kext
VBoxSF.kext_INST     = $(INST_ADDITIONS)VBoxSF.kext/Contents/
VBoxSF.kext_SOURCES  = $(VBoxSF.kext_0_OUTDIR)/Info.plist
VBoxSF.kext_CLEAN    = $(VBoxSF.kext_0_OUTDIR)/Info.plist

$$(VBoxSF.kext_0_OUTDIR)/Info.plist: \
		$(PATH_SUB_CURRENT)/Info.plist \
		$(VRA_VERSION_MK) | $$(dir $$@)
	$(call MSG_GENERATE,VBoxSF,$@,$<)
	$(QUIET)$(RM) -f $@
	$(QUIET)$(SED) \
		-e 's+@VRA_VERSION_STRING@+$(VRA_VERSION_STRING)+g' \
		-e 's+@VRA_VERSION_MAJOR@+$(VRA_VERSION_MAJOR)+g' \
		-e 's+@VRA_VERSION_MINOR@+$(VRA_VERSION_MINOR)+g' \
		-e 's+@VRA_VERSION_BUILD@+$(VRA_VERSION_BUILD)+g' \
		-e 's+@VRA_VENDOR@+$(VRA_VENDOR)+g' \
		-e 's+@VRA_PRODUCT@+$(VRA_PRODUCT)+g' \
		-e 's+@VRA_C_YEAR@+$(VRA_C_YEAR)+g' \
		--output $@ \
		$<

#
# mount.vboxsf - The Shared Folders mounting tool.
#
PROGRAMS += mount.vboxsf
mount.vboxsf_TEMPLATE = VBoxGuestR3Exe
mount.vboxsf_SOURCES  = mount.vboxsf.cpp
mount.vboxsf_INST     = $(INST_ADDITIONS)VBoxSF.kext/Contents/MacOS/


include $(FILE_KBUILD_SUB_FOOTER)

