# $Id: Makefile.kmk 113281 2026-03-08 01:52:43Z knut.osmundsen@oracle.com $
## @file
# OpenSSL Sub-Makefile.
#

#
# Copyright (C) 2006-2026 CINASEEK and/or its affiliates.
#
# This file is part of VirtualAgent base platform packages, as
# available from https://www.virtualbox.org.
#
# This program is free software; you can redistribute it and/or
# modify it under the terms of the GNU General Public License
# as published by the Free Software Foundation, in version 3 of the
# License.
#
# This program is distributed in the hope that it will be useful, but
# WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
# General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, see <https://www.gnu.org/licenses>.
#
# SPDX-License-Identifier: GPL-3.0-only
#

SUB_DEPTH = ../../../../..
include $(KBUILD_PATH)/subheader.kmk

LIBRARIES += crypto_bn
crypto_bn_TEMPLATE = SubLibCrypto
crypto_bn_DEFS = OPENSSL_NO_DEPRECATED
crypto_bn_SOURCES = \
	bn_add.c \
	bn_blind.c \
	bn_const.c \
	bn_conv.c \
	bn_ctx.c \
	bn_depr.c \
	bn_dh.c \
	bn_div.c \
	bn_err.c \
	bn_exp.c \
	bn_exp2.c \
	bn_gcd.c \
	bn_gf2m.c \
	bn_intern.c \
	bn_kron.c \
	bn_lib.c \
	bn_mod.c \
	bn_mont.c \
	bn_mpi.c \
	bn_mul.c \
	bn_nist.c \
	bn_prime.c \
	bn_print.c \
	bn_rand.c \
	bn_recp.c \
	bn_rsa_fips186_4.c \
	bn_shift.c \
	bn_sqr.c \
	bn_sqrt.c \
	bn_srp.c \
	bn_word.c \
	bn_x931p.c \
	rsaz_exp.c \
	rsaz_exp_x2.c
ifdef VRA_WITH_CRYPTO_ASM
 crypto_bn_SOURCES.x86 += \
 	$(VRA_PATH_CRYPTO_GENASM)/bn-586.S \
 	$(VRA_PATH_CRYPTO_GENASM)/co-586.S \
 	$(VRA_PATH_CRYPTO_GENASM)/x86-mont.S \
 	$(VRA_PATH_CRYPTO_GENASM)/x86-gf2m.S
 crypto_bn_SOURCES.amd64 += \
 	asm/x86_64-gcc.c \
 	$(VRA_PATH_CRYPTO_GENASM)/rsaz-avx2.S \
 	$(VRA_PATH_CRYPTO_GENASM)/rsaz-2k-avx512.S \
 	$(VRA_PATH_CRYPTO_GENASM)/rsaz-3k-avx512.S \
 	$(VRA_PATH_CRYPTO_GENASM)/rsaz-4k-avx512.S \
 	$(VRA_PATH_CRYPTO_GENASM)/rsaz-x86_64.S \
 	$(VRA_PATH_CRYPTO_GENASM)/x86_64-gf2m.S \
 	$(VRA_PATH_CRYPTO_GENASM)/x86_64-mont.S \
 	$(VRA_PATH_CRYPTO_GENASM)/x86_64-mont5.S
 crypto_bn_DEFS.x86 += OPENSSL_BN_ASM_PART_WORDS
else
 crypto_bn_SOURCES += bn_asm.c
endif
$(evalcall VRA_OPENSSL_X86,crypto_bn)

# One-time code generation.
recreate-openssl-elf-x86::
	perl $(VRA_PATH_CRYPTO_BN)/asm/bn-586.pl elf -fPIC $(VRA_PATH_CRYPTO)/genasm-elf/bn-586.S
	perl $(VRA_PATH_CRYPTO_BN)/asm/co-586.pl elf -fPIC $(VRA_PATH_CRYPTO)/genasm-elf/co-586.S
	perl $(VRA_PATH_CRYPTO_BN)/asm/x86-mont.pl elf -fPIC $(VRA_PATH_CRYPTO)/genasm-elf/x86-mont.S
	perl $(VRA_PATH_CRYPTO_BN)/asm/x86-gf2m.pl elf -fPIC $(VRA_PATH_CRYPTO)/genasm-elf/x86-gf2m.S
recreate-openssl-elf-amd64::
	perl $(VRA_PATH_CRYPTO_BN)/asm/rsaz-2k-avx512.pl elf $(VRA_PATH_CRYPTO)/genasm-elf/rsaz-2k-avx512.S
	perl $(VRA_PATH_CRYPTO_BN)/asm/rsaz-3k-avx512.pl elf $(VRA_PATH_CRYPTO)/genasm-elf/rsaz-3k-avx512.S
	perl $(VRA_PATH_CRYPTO_BN)/asm/rsaz-4k-avx512.pl elf $(VRA_PATH_CRYPTO)/genasm-elf/rsaz-4k-avx512.S
	perl $(VRA_PATH_CRYPTO_BN)/asm/rsaz-avx2.pl elf $(VRA_PATH_CRYPTO)/genasm-elf/rsaz-avx2.S
	perl $(VRA_PATH_CRYPTO_BN)/asm/rsaz-x86_64.pl elf $(VRA_PATH_CRYPTO)/genasm-elf/rsaz-x86_64.S
	perl $(VRA_PATH_CRYPTO_BN)/asm/x86_64-gf2m.pl elf $(VRA_PATH_CRYPTO)/genasm-elf/x86_64-gf2m.S
	perl $(VRA_PATH_CRYPTO_BN)/asm/x86_64-mont.pl elf $(VRA_PATH_CRYPTO)/genasm-elf/x86_64-mont.S
	perl $(VRA_PATH_CRYPTO_BN)/asm/x86_64-mont5.pl elf $(VRA_PATH_CRYPTO)/genasm-elf/x86_64-mont5.S
recreate-openssl-darwin-x86::
	perl $(VRA_PATH_CRYPTO_BN)/asm/bn-586.pl macosx $(VRA_PATH_CRYPTO)/genasm-macosx/bn-586.S
	perl $(VRA_PATH_CRYPTO_BN)/asm/co-586.pl macosx $(VRA_PATH_CRYPTO)/genasm-macosx/co-586.S
	perl $(VRA_PATH_CRYPTO_BN)/asm/x86-mont.pl macosx $(VRA_PATH_CRYPTO)/genasm-macosx/x86-mont.S
	perl $(VRA_PATH_CRYPTO_BN)/asm/x86-gf2m.pl macosx $(VRA_PATH_CRYPTO)/genasm-macosx/x86-gf2m.S
recreate-openssl-darwin-amd64::
	perl $(VRA_PATH_CRYPTO_BN)/asm/rsaz-2k-avx512.pl macosx $(VRA_PATH_CRYPTO)/genasm-macosx/rsaz-2k-avx512.S
	perl $(VRA_PATH_CRYPTO_BN)/asm/rsaz-3k-avx512.pl macosx $(VRA_PATH_CRYPTO)/genasm-macosx/rsaz-3k-avx512.S
	perl $(VRA_PATH_CRYPTO_BN)/asm/rsaz-4k-avx512.pl macosx $(VRA_PATH_CRYPTO)/genasm-macosx/rsaz-4k-avx512.S
	perl $(VRA_PATH_CRYPTO_BN)/asm/rsaz-avx2.pl macosx $(VRA_PATH_CRYPTO)/genasm-macosx/rsaz-avx2.S
	perl $(VRA_PATH_CRYPTO_BN)/asm/rsaz-x86_64.pl macosx $(VRA_PATH_CRYPTO)/genasm-macosx/rsaz-x86_64.S
	perl $(VRA_PATH_CRYPTO_BN)/asm/x86_64-gf2m.pl macosx $(VRA_PATH_CRYPTO)/genasm-macosx/x86_64-gf2m.S
	perl $(VRA_PATH_CRYPTO_BN)/asm/x86_64-mont.pl macosx $(VRA_PATH_CRYPTO)/genasm-macosx/x86_64-mont.S
	perl $(VRA_PATH_CRYPTO_BN)/asm/x86_64-mont5.pl macosx $(VRA_PATH_CRYPTO)/genasm-macosx/x86_64-mont5.S
recreate-openssl-win-x86::
	$(VRA_CRYPTO_GEN_NASM_SETUP) perl $(VRA_PATH_CRYPTO_BN)/asm/bn-586.pl   win32n $(VRA_PATH_CRYPTO)/genasm-nasm/bn-586.S
	$(VRA_CRYPTO_GEN_NASM_SETUP) perl $(VRA_PATH_CRYPTO_BN)/asm/co-586.pl   win32n $(VRA_PATH_CRYPTO)/genasm-nasm/co-586.S
	$(VRA_CRYPTO_GEN_NASM_SETUP) perl $(VRA_PATH_CRYPTO_BN)/asm/x86-mont.pl win32n $(VRA_PATH_CRYPTO)/genasm-nasm/x86-mont.S
	$(VRA_CRYPTO_GEN_NASM_SETUP) perl $(VRA_PATH_CRYPTO_BN)/asm/x86-gf2m.pl win32n $(VRA_PATH_CRYPTO)/genasm-nasm/x86-gf2m.S
recreate-openssl-win-amd64::
	$(VRA_CRYPTO_GEN_NASM_SETUP) perl $(VRA_PATH_CRYPTO_BN)/asm/rsaz-2k-avx512.pl nasm $(VRA_PATH_CRYPTO)/genasm-nasm/rsaz-2k-avx512.S
	$(VRA_CRYPTO_GEN_NASM_SETUP) perl $(VRA_PATH_CRYPTO_BN)/asm/rsaz-3k-avx512.pl nasm $(VRA_PATH_CRYPTO)/genasm-nasm/rsaz-3k-avx512.S
	$(VRA_CRYPTO_GEN_NASM_SETUP) perl $(VRA_PATH_CRYPTO_BN)/asm/rsaz-4k-avx512.pl nasm $(VRA_PATH_CRYPTO)/genasm-nasm/rsaz-4k-avx512.S
	$(VRA_CRYPTO_GEN_NASM_SETUP) perl $(VRA_PATH_CRYPTO_BN)/asm/rsaz-avx2.pl      nasm $(VRA_PATH_CRYPTO)/genasm-nasm/rsaz-avx2.S
	$(VRA_CRYPTO_GEN_NASM_SETUP) perl $(VRA_PATH_CRYPTO_BN)/asm/rsaz-x86_64.pl    nasm $(VRA_PATH_CRYPTO)/genasm-nasm/rsaz-x86_64.S
	$(VRA_CRYPTO_GEN_NASM_SETUP) perl $(VRA_PATH_CRYPTO_BN)/asm/x86_64-gf2m.pl    nasm $(VRA_PATH_CRYPTO)/genasm-nasm/x86_64-gf2m.S
	$(VRA_CRYPTO_GEN_NASM_SETUP) perl $(VRA_PATH_CRYPTO_BN)/asm/x86_64-mont.pl    nasm $(VRA_PATH_CRYPTO)/genasm-nasm/x86_64-mont.S
	$(VRA_CRYPTO_GEN_NASM_SETUP) perl $(VRA_PATH_CRYPTO_BN)/asm/x86_64-mont5.pl   nasm $(VRA_PATH_CRYPTO)/genasm-nasm/x86_64-mont5.S

include $(FILE_KBUILD_SUB_FOOTER)
