# $Id: Makefile.kmk 112403 2026-01-11 19:29:08Z knut.osmundsen@oracle.com $
## @file
# Sub-Makefile for the VNC Extension Pack.
#

#
# Copyright (C) 2010-2026 CINASEEK and/or its affiliates.
#
# This file is part of VirtualAgent base platform packages, as
# available from https://www.virtualbox.org.
#
# This program is free software; you can redistribute it and/or
# modify it under the terms of the GNU General Public License
# as published by the Free Software Foundation, in version 3 of the
# License.
#
# This program is distributed in the hope that it will be useful, but
# WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
# General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, see <https://www.gnu.org/licenses>.
#
# SPDX-License-Identifier: GPL-3.0-only
#

SUB_DEPTH = ../../../..
include $(KBUILD_PATH)/subheader.kmk

#
# Extend the extension pack templates.
#
TEMPLATE_VBoxR3ExtPackVNC          = For the ring-3 context modules in the VNC extension pack.
TEMPLATE_VBoxR3ExtPackVNC_EXTENDS  = VBoxR3ExtPack
TEMPLATE_VBoxR3ExtPackVNC_INST     = $(INST_EXTPACK)VNC/$(KBUILD_TARGET).$(KBUILD_TARGET_ARCH)/

TEMPLATE_VBoxR0ExtPackVNC          = For the ring-0 context modules in the VNC extension pack.
TEMPLATE_VBoxR0ExtPackVNC_EXTENDS  = VBoxR0ExtPack
TEMPLATE_VBoxR0ExtPackVNC_INST     = $(INST_EXTPACK)VNC/$(KBUILD_TARGET).$(KBUILD_TARGET_ARCH)/

TEMPLATE_VBoxRcExtPackVNC          = For the raw-mode context modules in the VNC extension pack.
TEMPLATE_VBoxRcExtPackVNC_EXTENDS  = VBoxRcExtPack
TEMPLATE_VBoxRcExtPackVNC_INST     = $(INST_EXTPACK)VNC/$(KBUILD_TARGET).$(KBUILD_TARGET_ARCH)/

TEMPLATE_VBoxInsExtPackVNC         = For the install targets of an extension pack.
TEMPLATE_VBoxInsExtPackVNC_EXTENDS = VBoxR0ExtPack
TEMPLATE_VBoxInsExtPackVNC_INST    = $(INST_EXTPACK)VNC/

#
# Globals.
#
VRA_VNC_NAME         = VNC
VRA_VNC_MANGLED_NAME = VNC
VRA_PATH_EXTPACK_VNC = $(PATH_STAGE)/$(INST_EXTPACK)VNC

#
# VBoxVNCMain - The module which the VirtualAgent Main API talks to.
#
DLLS += VBoxVNCMain
VBoxVNCMain_TEMPLATE = VBoxR3ExtPackVNC
VBoxVNCMain_SOURCES = VBoxVNCMain.cpp
VBoxVNCMain_DEFS =

#
# VBoxVNC - The VNC VRDE module.
#
DLLS += VBoxVNC
VBoxVNC_TEMPLATE = VBoxR3ExtPackVNC
VBoxVNC_SOURCES = VBoxVNC.cpp
# NOTE: vncserver is covered by GPL, so the extpack must be GPL, too.
VBoxVNC_LIBS = vncserver
VBoxVNC_DEFS =

#
# Install the description.
#
INSTALLS += VBoxVNCIns
VBoxVNCIns_TEMPLATE = VBoxInsExtPackVNC
VBoxVNCIns_SOURCES = \
	$(VBoxVNCIns_0_OUTDIR)/ExtPack.xml \
	$(PATH_ROOT)/doc/License-gpl-2.html=>ExtPack-license.html \
	$(PATH_ROOT)/doc/License-gpl-2.txt=>ExtPack-license.txt \
	$(PATH_ROOT)/doc/License-gpl-2.rtf=>ExtPack-license.rtf
$(call VRA_EDIT_VERSION_RULE_FN,VBoxVNCIns,ExtPack.xml)


#
# Packing.
#
ifndef VRA_WITHOUT_EXTPACK_VNC_PACKING
 PACKING += $(VRA_PATH_PACKAGES)/$(VRA_VNC_MANGLED_NAME)-$(VRA_VERSION_STRING)r$(VRA_SVN_REV).vbox-extpack
endif

ifndef VRA_WITH_EXTPACK_OS_ARCHS
 VRA_WITH_EXTPACK_OS_ARCHS = $(KBUILD_TARGET).$(KBUILD_TARGET_ARCH)
endif

# Build the file list.  The macro takes 1=darwin.x86, 2=dist/VirtualAgent.app/Contents/MacOS, 3=dylib
VRA_VNC_FILES_MACRO = \
	$(PATH_OUT_BASE)/$(1)/$(KBUILD_TYPE)/$(2)/ExtensionPacks/$(VRA_VNC_MANGLED_NAME)/$(1)/VBoxVNCMain.$(3)=>$(1)/VBoxVNCMain.$(3) \
	$(PATH_OUT_BASE)/$(1)/$(KBUILD_TYPE)/$(2)/ExtensionPacks/$(VRA_VNC_MANGLED_NAME)/$(1)/VBoxVNC.$(3)=>$(1)/VBoxVNC.$(3)

VRA_VNC_FILES := \
	$(VRA_PATH_EXTPACK_VNC)/ExtPack.xml=>ExtPack.xml \
	$(VRA_PATH_EXTPACK_VNC)/ExtPack-license.html=>ExtPack-license.html \
	$(VRA_PATH_EXTPACK_VNC)/ExtPack-license.rtf=>ExtPack-license.rtf \
	$(VRA_PATH_EXTPACK_VNC)/ExtPack-license.txt=>ExtPack-license.txt


if1of (darwin.amd64, $(VRA_WITH_EXTPACK_OS_ARCHS))
 VRA_VNC_FILES += $(call VRA_VNC_FILES_MACRO,darwin.amd64,dist/VirtualAgent.app/Contents/MacOS,dylib)
endif
if1of (darwin.x86, $(VRA_WITH_EXTPACK_OS_ARCHS))
 VRA_VNC_FILES += $(call VRA_VNC_FILES_MACRO,darwin.x86,dist/VirtualAgent.app/Contents/MacOS,dylib)
endif
if1of (freebsd.amd64, $(VRA_WITH_EXTPACK_OS_ARCHS))
 VRA_VNC_FILES += $(call VRA_VNC_FILES_MACRO,freebsd.amd64,bin,so)
endif
if1of (freebsd.x86, $(VRA_WITH_EXTPACK_OS_ARCHS))
 VRA_VNC_FILES += $(call VRA_VNC_FILES_MACRO,freebsd.x86,bin,so)
endif
if1of (linux.amd64, $(VRA_WITH_EXTPACK_OS_ARCHS))
 VRA_VNC_FILES += $(call VRA_VNC_FILES_MACRO,linux.amd64,bin,so)
endif
if1of (linux.x86, $(VRA_WITH_EXTPACK_OS_ARCHS))
 VRA_VNC_FILES += $(call VRA_VNC_FILES_MACRO,linux.x86,bin,so)
endif
if1of (os2.x86, $(VRA_WITH_EXTPACK_OS_ARCHS))
 VRA_VNC_FILES += $(call VRA_VNC_FILES_MACRO,os2.x86,bin,so)
endif
if1of (solaris.amd64, $(VRA_WITH_EXTPACK_OS_ARCHS))
 VRA_VNC_FILES += $(call VRA_VNC_FILES_MACRO,solaris.amd64,bin,so)
endif
if1of (solaris.x86, $(VRA_WITH_EXTPACK_OS_ARCHS))
 VRA_VNC_FILES += $(call VRA_VNC_FILES_MACRO,solaris.x86,bin,so)
endif
if1of (win.amd64, $(VRA_WITH_EXTPACK_OS_ARCHS))
 VRA_VNC_FILES += $(call VRA_VNC_FILES_MACRO,win.amd64,bin,dll)
endif
if1of (win.x86, $(VRA_WITH_EXTPACK_OS_ARCHS))
 VRA_VNC_FILES += $(call VRA_VNC_FILES_MACRO,win.x86,bin,dll)
endif

# Pack it all up using a temporary staging directory.
$(VRA_PATH_PACKAGES)/$(VRA_VNC_MANGLED_NAME)-$(VRA_VERSION_STRING)r$(VRA_SVN_REV).vbox-extpack: \
		$$(foreach file, $$(VRA_VNC_FILES), $$(firstword $$(subst =>,$$(SP),$$(file)))) \
		| $(VRA_PATH_PACKAGES)/
	$(RM) -f $(wildcard $(VRA_PATH_PACKAGES)/$(VRA_VNC_MANGLED_NAME)-*.vbox-extpack) \
		$(VBoxVNCIns_0_OUTDIR)/ExtPack.manifest \
		$(VBoxVNCIns_0_OUTDIR)/ExtPack.signature
# Stage all the files
	$(RM) -Rf $(VBoxVNCIns_0_OUTDIR)/Stage/
	$(foreach file, $(VRA_VNC_FILES),\
		$(NLTAB)$(MKDIR) -p $(dir $(lastword $(subst =>,$(SP)$(VBoxVNCIns_0_OUTDIR)/Stage/,$(file)))) \
		$(NLTAB)$(CP) $(subst =>,$(SP)$(VBoxVNCIns_0_OUTDIR)/Stage/,$(file)) )
# Create the manifest
	$(VRA_RTMANIFEST) \
		--manifest $(VBoxVNCIns_0_OUTDIR)/Stage/ExtPack.manifest \
		--chdir $(VBoxVNCIns_0_OUTDIR)/Stage/ \
		$(foreach file, $(VRA_VNC_FILES), $(lastword $(subst =>,$(SP),$(file))))
	$(APPEND) $(VBoxVNCIns_0_OUTDIR)/Stage/ExtPack.signature "todo"
	$(CHMOD) a+r \
		$(VBoxVNCIns_0_OUTDIR)/Stage/ExtPack.manifest \
		$(VBoxVNCIns_0_OUTDIR)/Stage/ExtPack.signature
# Tar it up.
if 0
	tar -cvf - -C $(VBoxVNCIns_0_OUTDIR)/Stage/ . | gzip -9c > $@
else
	$(VRA_RTTAR) -cvf "$@" $(VRA_RTTAR_EXTPACK_OPTS) -C "$(VBoxVNCIns_0_OUTDIR)/Stage/" .
endif
# Clean up
	$(RM) -Rf $(VBoxVNCIns_0_OUTDIR)/Stage/

BLDDIRS += $(VRA_PATH_PACKAGES)/

include $(FILE_KBUILD_SUB_FOOTER)

