# $Id: Makefile.kmk 112403 2026-01-11 19:29:08Z knut.osmundsen@oracle.com $
## @file
# Sub-Makefile for Java bindings
#

#
# Copyright (C) 2010-2026 CINASEEK and/or its affiliates.
#
# This file is part of VirtualAgent base platform packages, as
# available from https://www.virtualbox.org.
#
# This program is free software; you can redistribute it and/or
# modify it under the terms of the GNU General Public License
# as published by the Free Software Foundation, in version 3 of the
# License.
#
# This program is distributed in the hope that it will be useful, but
# WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
# General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, see <https://www.gnu.org/licenses>.
#
# SPDX-License-Identifier: GPL-3.0-only
#

SUB_DEPTH = ../../../..
include $(KBUILD_PATH)/subheader.kmk

#
# Globals
#
VRA_JXPCOM_SRC := $(PATH_SUB_CURRENT)

VRA_JXPCOM_TARGET := $(PATH_TARGET)/vboxjxpcom-gen
VRA_JXPCOM_JDEST  := $(VRA_JXPCOM_TARGET)/jdest

VRA_GLUE_XSLT_DIR := $(PATH_ROOT)/src/VBox/Main/glue

ifndef VRA_ONLY_SDK
 #
 # VBoxJXpcom - Java<->XPCOM native library
 #
 DLLS += VBoxJXpcom

 VBoxJXpcom_TEMPLATE = XPComDll
 VBoxJXpcom_CXXFLAGS = -Wno-write-strings
 VBoxJXpcom_DEFS    = \
 	EXPORT_XPTI_API \
 	EXPORT_XPT_API \
 	VRA_WITH_XPCOM
 VBoxJXpcom_NAME    = libvboxjxpcom
 VBoxJXpcom_DLLSUFF.darwin = .jnilib
 VBoxJXpcom_INCS    = \
 	src \
 	$(VRA_JAVA_INC) \
 	$(VRA_PATH_XPCOM_SRC)/xpcom/glue \
 	$(VRA_PATH_XPCOM_SRC)/xpcom/build \
 	$(VRA_JXPCOM_JDEST)
 VBoxJXpcom_INCS.darwin += \
 	$(VRA_JAVA_INC)/darwin
 VBoxJXpcom_SOURCES = \
 	src/nsAppFileLocProviderProxy.cpp \
 	src/nsJavaWrapper.cpp \
 	src/nsJavaXPCOMBindingUtils.cpp \
 	src/nsJavaXPTCStub.cpp \
 	src/nsJavaXPTCStubWeakRef.cpp \
 	src/nsJavaXPCOMGlue.cpp \
 	src/nsJavaInterfaces.cpp
 VBoxJXpcom_LIBS    = \
 	$(PATH_STAGE_LIB)/VBoxCOM$(VRA_SUFF_LIB) \
 	$(PATH_STAGE_BIN)/VBoxXPCOM$(VRA_SUFF_DLL)

 #VBoxJXpcom_ORDERDEPS = $(VRA_JXPCOM_GENH)
 #VBoxJXpcom_CLEAN     = $(VRA_JXPCOM_GENH)
 VRA_JXPCOM_GENH = \
 	$(VRA_JXPCOM_JDEST)/org_mozilla_xpcom_internal_XPCOMImpl.h \
 	$(VRA_JXPCOM_JDEST)/org_mozilla_xpcom_internal_GREImpl.h \
 	$(VRA_JXPCOM_JDEST)/org_mozilla_xpcom_internal_MozillaImpl.h \
 	$(VRA_JXPCOM_JDEST)/org_mozilla_xpcom_internal_XPCOMJavaProxy.h \
 	$(VRA_JXPCOM_JDEST)/org_mozilla_xpcom_internal_JavaXPCOMMethods.h \
 	$(VRA_JXPCOM_JDEST)/org_mozilla_xpcom_ProfileLock.h

endif # !VRA_ONLY_SDK

#
# Install JAR files
#
INSTALLS += VBoxJXpcom-inst-jar

VRA_JXPCOM_JAR     = $(VBoxJXpcom-inst-jar_0_OUTDIR)/vboxjxpcom.jar
VRA_JXPCOM_NSERROR = $(VRA_JXPCOM_GEN)/java/XPCOMError.java
VRA_JXPCOM_GEN     = $(VRA_JXPCOM_TARGET)/jxpcomgen

VBoxJXpcom-inst-jar_INST = $(INST_SDK)bindings/xpcom/java/
VBoxJXpcom-inst-jar_MODE = a+r,u+w
VBoxJXpcom-inst-jar_SOURCES = \
	$(VRA_JXPCOM_JAR)
VBoxJXpcom-inst-jar_CLEAN = \
	$(VRA_JXPCOM_JAR) \
	$(VRA_JXPCOM_NSERROR) \
	$(VRA_JXPCOM_GEN)/jxpcomgen.list \
	$(VRA_JXPCOM_GEN)/jxpcomglue.list \
	$(wildcard \
		$(VRA_JXPCOM_GEN)/java/*.java \
		$(VRA_JXPCOM_GEN)/java/glue/*.java \
		$(VRA_JXPCOM_JDEST)/*.class \
		$(VRA_JXPCOM_JDEST)/*/*.class \
		$(VRA_JXPCOM_JDEST)/*/*/*.class \
		$(VRA_JXPCOM_JDEST)/*/*/*/*.class \
		$(VRA_JXPCOM_JDEST)/*/*/*/*/*.class \
		$(VRA_JXPCOM_JDEST)/*/*/*/*/*/*.class \
		)
VBoxJXpcom-inst-jar_BLDDIRS += $(VRA_JXPCOM_GEN)/java $(VRA_JXPCOM_GEN)/java/glue $(VRA_JXPCOM_GEN)/java/interfaces

#
# For VBoxJXpcom, not currently used.
#
$(VRA_JXPCOM_GENH): $$(VRA_JXPCOM_JAR)
	$(call MSG_L1,Generating $@ from $<)
	$(QUIET)$(VRA_JAVAH) -classpath $(VRA_JXPCOM_JDEST) -d $(VRA_JXPCOM_JDEST) \
		org.mozilla.xpcom.internal.XPCOMImpl \
		org.mozilla.xpcom.internal.GREImpl \
		org.mozilla.xpcom.internal.MozillaImpl \
		org.mozilla.xpcom.internal.XPCOMJavaProxy \
		org.mozilla.xpcom.ProfileLock \
		org.mozilla.xpcom.internal.JavaXPCOMMethods

#
# Generate error constants.
#
$(VRA_JXPCOM_NSERROR): $(VRA_PATH_XPCOM_SRC)/xpcom/base/nsError.h $(VRA_JXPCOM_SRC)/tools/gen-nsError.pl | $(VRA_JXPCOM_GEN)/java/
	$(call MSG_L1,Generating $@)
	$(QUIET)perl $(VRA_JXPCOM_SRC)/tools/gen-nsError.pl < $< > $@

#
# Generate .java interface files from .xidl
#
$(VRA_JXPCOM_GEN)/jxpcomgen.list: \
		$(VRA_XIDL_FILE) \
		$(VRA_FILESPLIT) \
		$(VRA_JXPCOM_SRC)/tools/genjifaces.xsl \
		| $(VRA_JXPCOM_GEN)/java/interfaces/
	$(call MSG_L1,Generating Java interface files)
	$(QUIET)$(RM) -f $(wildcard $(VRA_JXPCOM_GEN)/java/interfaces/*.java)
	$(QUIET)$(VRA_XSLTPROC)   \
             -o $(VRA_JXPCOM_GEN)/java/interfaces/merged.file $(VRA_JXPCOM_SRC)/tools/genjifaces.xsl $<
	$(QUIET)$(VRA_FILESPLIT) $(VRA_JXPCOM_GEN)/java/interfaces/merged.file $(VRA_JXPCOM_GEN)/java/interfaces
	$(QUIET)echo $(VRA_JXPCOM_GEN)/java/interfaces/*.java > $@


$(VRA_JXPCOM_GEN)/jxpcomglue.list: \
		$(VRA_XIDL_FILE) \
		$(VRA_GLUE_XSLT_DIR)/glue-java.xsl \
		$(VRA_FILESPLIT) \
		| $(VRA_JXPCOM_GEN)/java/glue/
	$(call MSG_L1,Generating Java glue files from XIDL)
	$(QUIET)$(RM) -f $(wildcard $(VRA_JXPCOM_GEN)/java/glue/*.java)
	$(QUIET)$(VRA_XSLTPROC)   \
              --stringparam filelistonly ""                    \
              --stringparam G_vboxApiSuffix $(VRA_API_SUFFIX) \
              --stringparam G_vboxGlueStyle xpcom              \
              --stringparam G_vboxDirPrefix ""                 \
              -o $(VRA_JXPCOM_GEN)/java/glue/merged.file $(VRA_GLUE_XSLT_DIR)/glue-java.xsl $<
	$(QUIET)$(VRA_FILESPLIT) $(VRA_JXPCOM_GEN)/java/glue/merged.file $(VRA_JXPCOM_GEN)/java/glue/
	$(QUIET)echo $(VRA_JXPCOM_GEN)/java/glue/*.java > $@

#
# Compile the all java code into a JAR file.
#
VRA_JXPCOM_JSRC = $(VRA_JXPCOM_SRC)/src/org/mozilla/xpcom
VRA_JXPCOM_JAR_SRC = \
	$(VRA_JXPCOM_JSRC)/IXPCOM.java \
	$(VRA_JXPCOM_JSRC)/Mozilla.java \
	$(VRA_JXPCOM_JSRC)/VersionComparator.java \
	$(VRA_JXPCOM_JSRC)/GREVersionRange.java \
	$(VRA_JXPCOM_JSRC)/IAppFileLocProvider.java \
	$(VRA_JXPCOM_JSRC)/ProfileLock.java \
	$(VRA_JXPCOM_JSRC)/IGRE.java \
	$(VRA_JXPCOM_JSRC)/IJavaXPCOMUtils.java \
	$(VRA_JXPCOM_JSRC)/XPCOMException.java \
	$(VRA_JXPCOM_JSRC)/IMozilla.java \
	$(VRA_JXPCOM_JSRC)/XPCOMInitializationException.java \
	$(VRA_JXPCOM_JSRC)/INIParser.java \
	$(VRA_JXPCOM_JSRC)/internal/GREImpl.java \
	$(VRA_JXPCOM_JSRC)/internal/JavaXPCOMMethods.java \
	$(VRA_JXPCOM_JSRC)/internal/MozillaImpl.java \
	$(VRA_JXPCOM_JSRC)/internal/XPCOMImpl.java \
	$(VRA_JXPCOM_JSRC)/internal/XPCOMJavaProxyBase.java \
	$(VRA_JXPCOM_JSRC)/internal/XPCOMJavaProxy.java

$$(VRA_JXPCOM_JAR): $(VRA_JXPCOM_JAR_SRC) $(VRA_JXPCOM_GEN)/jxpcomgen.list $(VRA_JXPCOM_GEN)/jxpcomglue.list $(VRA_JXPCOM_NSERROR) $(VRA_JXPCOM_MGR) | $$(dir $$@)
	$(call MSG_TOOL,javac,$(notdir $@),jxpcomgen.list,)
	$(QUIET)$(RM) -Rf $(VRA_JXPCOM_JDEST)
	$(QUIET)$(MKDIR) -p $(VRA_JXPCOM_JDEST)
	$(QUIET)$(VRA_JAVAC) $(VRA_JAVAC_OPTS) @$(VRA_JXPCOM_GEN)/jxpcomgen.list \
		-d $(VRA_JXPCOM_JDEST) -classpath $(VRA_JXPCOM_JDEST)
	$(call MSG_TOOL,javac,$(notdir $@),...,)
	$(QUIET)$(VRA_JAVAC) $(VRA_JAVAC_OPTS) \
		$(VRA_JXPCOM_JAR_SRC) \
		$(VRA_JXPCOM_NSERROR) \
                @$(VRA_JXPCOM_GEN)/jxpcomglue.list \
		-d $(VRA_JXPCOM_JDEST) -classpath $(VRA_JXPCOM_JDEST)
	$(call MSG_LINK,$(notdir $@),$@)
	$(QUIET)$(VRA_JAR) cf $@ -C $(VRA_JXPCOM_JDEST) .

include $(FILE_KBUILD_SUB_FOOTER)
