# $Id: Makefile.kmk 112403 2026-01-11 19:29:08Z knut.osmundsen@oracle.com $
## @file
# Makefile for the FreeBSD installer.
#

#
# Copyright (C) 2006-2026 CINASEEK and/or its affiliates.
#
# This file is part of VirtualAgent base platform packages, as
# available from https://www.virtualbox.org.
#
# This program is free software; you can redistribute it and/or
# modify it under the terms of the GNU General Public License
# as published by the Free Software Foundation, in version 3 of the
# License.
#
# This program is distributed in the hope that it will be useful, but
# WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
# General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, see <https://www.gnu.org/licenses>.
#
# SPDX-License-Identifier: GPL-3.0-only
#

SUB_DEPTH = ../../../..
include $(KBUILD_PATH)/subheader.kmk

ifneq ($(KBUILD_HOST),freebsd)
 $(error "The FreeBSD installer can only be built on FreeBSD!")
endif

#
# Globals and targets.
#
VRA_PATH_FBSD_INST_SRC      := $(PATH_SUB_CURRENT)
VRA_FBSD_INST_OUT_DIR       := $(PATH_TARGET)/Installer/freebsd
VRA_FBSD_INST_STAGE_DIR     := $(PATH_TARGET)/Installer/freebsd/install
VRA_FBSD_DBG_PATH           := usr/lib/debug/opt/VirtualAgent
VRA_FBSD_PACKAGE_NAME        = VirtualAgent-$(VRA_VERSION_STRING)-r$(VRA_SVN_REV).tbz
VRA_FBSD_INST_LIB_DIR       := $(VRA_FBSD_INST_STAGE_DIR)/lib
VRA_FBSD_INST_BIN_DIR       := $(VRA_FBSD_INST_STAGE_DIR)/bin
VRA_FBSD_INST_LIBVRA_DIR   := $(VRA_FBSD_INST_LIB_DIR)/virtualbox
VRA_FBSD_INST_SHARE_DIR     := $(VRA_FBSD_INST_STAGE_DIR)/share
VRA_FBSD_INST_SHAREAPP_DIR  := $(VRA_FBSD_INST_SHARE_DIR)/applications
VRA_FBSD_INST_SHAREICON_DIR := $(VRA_FBSD_INST_SHARE_DIR)/pixmaps
VRA_FBSD_INST_SHAREVRA_DIR := $(VRA_FBSD_INST_SHARE_DIR)/virtualbox

# Unset this to speed up things during makefile hacking.
VRA_FBSD_INST_DEP_ON_MAKEFILE := $(MAKEFILE_CURRENT)

BLDDIRS  += $(VRA_FBSD_INST_OUT_DIR) $(VRA_FBSD_INST_STAGE_DIR)
PACKING  += $(PATH_STAGE_BIN)/$(VRA_FBSD_PACKAGE_NAME)

OTHER_CLEAN   += \
	$(addprefix $(VRA_FBSD_INST_STAGE_DIR)/, \
		pkg_plist \
		LICENSE) \
	$(wildcard $(VRA_FBSD_INST_OUT_DIR)/VirtualAgent-*)

#
# FreeBSD installs.
#
INSTALLS += freebsd-misc
freebsd-misc_INST = bin/
freebsd-misc_MODE = a+r,u+w
freebsd-misc_SOURCES = \
	$(PATH_ROOT)/src/VBox/Frontends/VirtualAgent/images/$(if $(VRA_OSE),OSE,NonOSE)/VirtualAgent_32px.png=>VBox.png \
	$(if $(VRA_OSE),,$(VRA_BRAND_LICENSE_TXT)=>LICENSE) \
	$(if $(VRA_WITH_QTGUI),$(freebsd-misc_0_OUTDIR)/virtualbox.desktop,) \
	$(if $(VRA_WITH_QTGUI),$(freebsd-misc_0_OUTDIR)/virtualboxvm.desktop,)
freebsd-misc_CLEAN = $(freebsd-misc_0_OUTDIR)/virtualbox.desktop
freebsd-misc_CLEAN += $(freebsd-misc_0_OUTDIR)/virtualboxvm.desktop

$$(PATH_freebsd-misc)/virtualbox.desktop: $(VRA_PATH_INST_COMMON_SRC)/virtualbox.desktop.in $(VRA_VERSION_STAMP) | $$(dir $$@)
	$(call MSG_GENERATE,,$@,$<)
	$(QUIET)$(SED) -e "s+@VRA_PRODUCT@+$(VRA_PRODUCT)+" \
		--output $@ $<

$$(PATH_freebsd-misc)/virtualboxvm.desktop: $(VRA_PATH_INST_COMMON_SRC)/virtualboxvm.desktop.in $(VRA_VERSION_STAMP) | $$(dir $$@)
	$(call MSG_GENERATE,,$@,$<)
	$(QUIET)$(SED) -e "s+@VRA_PRODUCT@+$(VRA_PRODUCT)+" \
		--output $@ $<
#
# The files residing in bin/ that we'll ship.
#

# Strip these binaries
VRA_FBSD_STRIP_BIN = \
	VBoxDD.so \
	VBoxDD2.so \
	VBoxDDU.so \
	VBoxVMM.so \
	$(if $(VRA_WITH_VIRT_ARMV8),VBoxVMMArm.so,) \
	VBoxRT.so \
	$(if $(VRA_WITH_VRASDL),VBoxSDL $(if $(VRA_WITH_HARDENING),VBoxSDL.so),) \
	$(if $(VRA_WITH_SHARED_CLIPBOARD), VBoxSharedClipboard.so,) \
	$(if $(VRA_WITH_SHARED_FOLDERS), VBoxSharedFolders.so,) \
	$(if $(VRA_WITH_GUEST_PROPS),VBoxGuestPropSvc.so,) \
	$(if $(VRA_WITH_GUEST_CONTROL),VBoxGuestControlSvc.so,) \
	VBoxHostChannel.so \
	$(if $(VRA_WITH_MAIN), \
		VBoxManage \
		VBoxNetDHCP $(if $(VRA_WITH_HARDENING),VBoxNetDHCP.so,) \
		VBoxNetAdpCtl \
		VBoxSVC \
		VBoxXPCOM.so \
		VBoxXPCOMC.so \
		VBoxXPCOMICPD.so \
		components/VBoxXPCOMIPCC.so \
		components/VBoxSVCM.so \
		components/VBoxC.so,) \
	$(if $(VRA_WITH_PYTHON),VBoxPython.so,) \
	$(if $(VRA_WITH_DTRACE),VBoxDTrace,) \
	$(if $(VRA_WITH_HOST_SHIPPING_AUDIO_TEST),VBoxAudioTest,)

# Do not remove relocation information of these binaries
VRA_FBSD_STRIP_OBJ = \
	VBoxDDRC.rc \
	VBoxDDR0.r0 \
	VMMRC.rc \
	VMMR0.r0

# Do not strip anything of these files
VRA_FBSD_NO_STRIP = \
	$(if $(VRA_OSE),,LICENSE) \
	$(if $(VRA_WITH_MAIN), \
		components/VBoxXPCOMBase.xpt \
		components/VirtualAgent_XPCOM.xpt) \
	vboxdrv.tar.gz

# EFI firmware
ifdef VRA_WITH_EFIFW_PACKING
 VRA_FBSD_NO_STRIP += \
 	VBoxEFI-x86.fd \
 	VBoxEFI-amd64.fd
 ifdef VRA_WITH_VIRT_ARMV8
  VRA_FBSD_NO_STRIP += \
  	VBoxEFI-arm32.fd \
  	VBoxEFI-arm64.fd
 endif
endif

# Symlinks residing in bin/
VRA_FBSD_SYMLINKS = \
	$(if $(VRA_WITH_MAIN), \
		VBoxManage \
		VBoxSVC) \
	$(if $(VRA_WITH_VRASDL),VBoxSDL,) \
	$(if $(VRA_WITH_DTRACE),VBoxDTrace,) \
	$(if $(VRA_WITH_HOST_SHIPPING_AUDIO_TEST),VBoxAudioTest,)

# Qt GUI
ifdef VRA_WITH_QTGUI
 include $(PATH_ROOT)/src/VBox/Frontends/VirtualAgent/nls/ApprovedLanguages.kmk
 VRA_FBSD_STRIP_BIN += \
 	VBoxKeyboard.so \
 	VirtualAgent \
 	$(if $(VRA_WITH_HARDENING),VirtualAgent.so) \
 	$(if $(VRA_WITH_DEBUGGER_GUI),VBoxDbg.so DbgPlugInDiggers.so,)
 VRA_FBSD_SYMLINKS += \
 	VirtualAgent
 VRA_FBSD_NO_STRIP += \
 	$(VRA_LICENSE_FILES) \
 	$(if $(VRA_WITH_ORACLE_QT),$(notdir $(wildcard $(PATH_STAGE_BIN)/lib*VBox*)),) \
 	$(if $(VRA_WITH_ORACLE_QT),accessible/libqtaccessiblewidgets.so,) \
 	$(foreach f,$(VRA_APPROVED_GUI_LANGUAGES),nls/VirtualAgent_$(f).qm nls/qt_$(f).qm)
 VRA_FBSD_DESKTOP_FILE = \
 	virtualbox.desktop \
 	virtualboxvm.desktop
 VRA_FBSD_ICON_FILE = \
 	VBox.png
endif

# Guest Additions
ifdef VRA_WITH_ADDITIONS_PACKING
 VRA_FBSD_NO_STRIP += \
 	additions/VBoxGuestAdditions.iso
endif

# Documentation
ifdef VRA_WITH_DOCS_PACKING
 VRA_FBSD_NO_STRIP += \
 	VirtualAgent.chm UserManual.pdf \
 	$(foreach f,$(VRA_MANUAL_ADD_LANGUAGES),VirtualAgent_$(f).chm UserManual_$(f).pdf)
endif

# VRDP
ifdef VRA_WITH_VRDP
 VRA_FBSD_STRIP_BIN += \
 	VBoxVRDP.so \
 	VBoxAuth.so
endif

# Headless
ifdef VRA_WITH_HEADLESS
 VRA_FBSD_STRIP_BIN += \
 	VBoxHeadless \
 	$(if $(VRA_WITH_HARDENING),VBoxHeadless.so)
 VRA_FBSD_SYMLINKS += \
 	VBoxHeadless
endif

# Webservices
ifdef VRA_WITH_WEBSERVICES
 VRA_FBSD_STRIP_BIN += \
 	vboxwebsrv
 VRA_FBSD_SYMLINKS += \
 	vboxwebsrv
endif

# DTrace library, testcase and scripts (as the rest of this file, this makes bold
# ASSUMPTIONS about VBPX_INST_XXX variable values).
ifdef VRA_WITH_DTRACE
 VRA_FBSD_NO_STRIP += \
 	$(addprefix dtrace/lib/$(KBUILD_TARGET_ARCH)/,$(VRAINST_DTRACE_LIB_ARCH_FILES)) \
 	$(addprefix dtrace/testcase/$(KBUILD_TARGET_ARCH)/,$(VRAINST_DTRACE_TESTCASE_ARCH_FILES)) \
 	$(addprefix dtrace/scripts/,$(VRAINST_DTRACE_SCRIPTS_FILES))
endif

#
# All the bin files that goes into the archives.
#
VRA_FBSD_ARCH_FILES := $(VRA_FBSD_STRIP_BIN) $(VRA_FBSD_STRIP_OBJ) $(VRA_FBSD_NO_STRIP)

# Cleanup of the files we copy/symlink from bin.
OTHER_CLEAN += $(addprefix $(VRA_FBSD_INST_LIBVRA_DIR)/,$(VRA_FBSD_ARCH_FILES))

#
# The module source archive
#
$(PATH_STAGE_BIN)/vboxdrv.tar.gz: \
		src
	$(call MSG_TOOL, export_modules.sh,,$@)
	$(QUIET)$(PATH_STAGE_BIN)/export_modules.sh $@

#
# The generic installer.
## @todo r=aeichner: Create pkg_plist dynamically based on the available features
#
$(PATH_STAGE_BIN)/$(VRA_FBSD_PACKAGE_NAME): \
		$(VRA_VERSION_STAMP) \
		$(VRA_FBSD_INST_OUT_DIR)/pkg_plist \
		$(addprefix $(VRA_FBSD_INST_LIBVRA_DIR)/,$(VRA_FBSD_ARCH_FILES)) \
		$(addprefix $(VRA_FBSD_INST_BIN_DIR)/,$(VRA_FBSD_SYMLINKS)) \
		$(if $(VRA_OSE),,$(VRA_BRAND_LICENSE_TXT)) \
		$(if $(VRA_WITH_QTGUI),$(addprefix $(VRA_FBSD_INST_SHAREAPP_DIR)/,$(VRA_FBSD_DESKTOP_FILE)),) \
		$(if $(VRA_WITH_QTGUI),$(addprefix $(VRA_FBSD_INST_SHAREICON_DIR)/,$(VRA_FBSD_ICON_FILE)),) \
		$(VRA_PATH_FBSD_INST_SRC)/postinstall.sh \
		$(VRA_PATH_FBSD_INST_SRC)/postdeinstall.sh
	$(call MSG_TOOL,pkg_create,,$@)
	$(QUIET)$(RM) -f $@
	$(QUIET)pkg_create \
		-I $(VRA_PATH_FBSD_INST_SRC)/postinstall.sh \
		-K $(VRA_PATH_FBSD_INST_SRC)/postdeinstall.sh \
		-c $(VRA_PATH_FBSD_INST_SRC)/pkg-comment \
		-d $(VRA_PATH_FBSD_INST_SRC)/pkg-descr \
		-f $(VRA_FBSD_INST_OUT_DIR)/pkg_plist \
		-p /usr/local \
		-s $(VRA_FBSD_INST_STAGE_DIR) \
		$@
	$(QUIET)$(RM) -Rf $(VRA_FBSD_INST_STAGE_DIR)

$(addprefix $(VRA_FBSD_INST_LIBVRA_DIR)/,$(VRA_FBSD_STRIP_BIN)): \
		$(VRA_FBSD_INST_LIBVRA_DIR)/% : $(PATH_STAGE_BIN)/%
	$(call MSG_INST_FILE,$<,$@)
	$(QUIET)$(INSTALL) -d $(dir $@)
	$(QUIET)$(INSTALL) -m 0755 $(if $(VRA_DO_STRIP),-s,) $< $@

# pattern rule for striping and copying the VRA_FBSD_STRIP_OBJ files to install/lib/virtualbox
$(addprefix $(VRA_FBSD_INST_LIBVRA_DIR)/,$(VRA_FBSD_STRIP_OBJ)): \
		$(VRA_FBSD_INST_LIBVRA_DIR)/% : $(PATH_STAGE_BIN)/%
	$(call MSG_INST_FILE,$<,$@)
	$(QUIET)$(INSTALL) -d $(dir $@)
ifeq ($(VRA_DO_STRIP),)
	$(QUIET)$(INSTALL) -m 0644 $< $@
else # strip to temp file because of umask.
	$(QUIET)objcopy --strip-unneeded -R .comment $< $@.tmp
	$(QUIET)$(INSTALL) -m 0644 $@.tmp $@
	$(QUIET)$(RM) -f -- $@.tmp
endif

# pattern rule for linking the VRA_FBSD_NO_STRIP into lib/virtualbox/
$(addprefix $(VRA_FBSD_INST_LIBVRA_DIR)/,$(VRA_FBSD_NO_STRIP)): \
		$(VRA_FBSD_INST_LIBVRA_DIR)/% : $(PATH_STAGE_BIN)/%
	$(call MSG_INST_FILE,$<,$@)
	$(QUIET)$(INSTALL) -d $(dir $@)
	$(QUIET)$(RM) -f $@
	$(QUIET)$(INSTALL) -m 0644 $< $@

# pattern rule for symlinking the VRA_FBSD_SYMLINKS into bin/
$(addprefix $(VRA_FBSD_INST_BIN_DIR)/,$(VRA_FBSD_SYMLINKS)): \
		$(VRA_FBSD_INST_BIN_DIR)/% : $(PATH_STAGE_BIN)/%
	$(call MSG_INST_SYM,$<,$@)
	$(QUIET)$(INSTALL) -d $(dir $@)
	$(QUIET)$(RM) -f $@
	$(QUIET)$(LN_SYMLINK) ../lib/virtualbox/$(notdir $@) $@

# pattern rule for copying the VRA_FBSD_DESKTOP_FILE into share/applications/
$(addprefix $(VRA_FBSD_INST_SHAREAPP_DIR)/,$(VRA_FBSD_DESKTOP_FILE)): \
		$(VRA_FBSD_INST_SHAREAPP_DIR)/% : $(PATH_STAGE_BIN)/%
	$(call MSG_INST_FILE,$<,$@)
	$(QUIET)$(INSTALL) -d $(dir $@)
	$(QUIET)$(RM) -f $@
	$(QUIET)$(INSTALL) -m 0644 $< $@

# pattern rule for copying the VRA_FBSD_ICON_FILE into share/pixmaps/
$(addprefix $(VRA_FBSD_INST_SHAREICON_DIR)/,$(VRA_FBSD_ICON_FILE)): \
		$(VRA_FBSD_INST_SHAREICON_DIR)/% : $(PATH_STAGE_BIN)/%
	$(call MSG_INST_FILE,$<,$@)
	$(QUIET)$(INSTALL) -d $(dir $@)
	$(QUIET)$(RM) -f $@
	$(QUIET)$(INSTALL) -m 0644 $< $@

# Create pkg_plist
$(VRA_FBSD_INST_OUT_DIR)/pkg_plist: \
		$(VRA_PATH_FBSD_INST_SRC)/pkg_plist
	$(call MSG_INST_FILE,$<,$@)
	$(QUIET)$(INSTALL) -d $(dir $@)
	$(QUIET)$(CP) -- "$<" "$@"
ifdef VRA_WITH_DTRACE
	$(QUIET)$(APPEND) -n "$@" "@mode 644" \
		$(addprefix lib/virtualbox/dtrace/lib/$(KBUILD_TARGET_ARCH)/,$(VRAINST_DTRACE_LIB_ARCH_FILES)) \
		$(addprefix lib/virtualbox/dtrace/testcase/$(KBUILD_TARGET_ARCH)/,$(VRAINST_DTRACE_TESTCASE_ARCH_FILES)) \
		$(addprefix lib/virtualbox/dtrace/scripts/,$(VRAINST_DTRACE_SCRIPTS_FILES)) \
		"@mode 755" \
		"bin/VBoxDTrace"
endif

include $(FILE_KBUILD_SUB_FOOTER)

