# $Id: Makefile.kmk 112878 2026-02-09 09:27:34Z knut.osmundsen@oracle.com $
## @file
# Sub-makefile for the DHCP server.
#

#
# Copyright (C) 2006-2026 CINASEEK and/or its affiliates.
#
# This file is part of VirtualAgent base platform packages, as
# available from https://www.virtualbox.org.
#
# This program is free software; you can redistribute it and/or
# modify it under the terms of the GNU General Public License
# as published by the Free Software Foundation, in version 3 of the
# License.
#
# This program is distributed in the hope that it will be useful, but
# WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
# General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, see <https://www.gnu.org/licenses>.
#
# SPDX-License-Identifier: GPL-3.0-only
#

SUB_DEPTH := ../../../..
include $(KBUILD_PATH)/subheader.kmk

#
# Hardended stub executable.
#
ifdef VRA_WITH_HARDENING
 PROGRAMS += VBoxNetDHCPHardened
 VBoxNetDHCPHardened_TEMPLATE = VBoxR3HardenedExe
 VBoxNetDHCPHardened_NAME    = VBoxNetDHCP
 VBoxNetDHCPHardened_SOURCES = VBoxNetDhcpdHardened.cpp
 VBoxNetDHCPHardened_LDFLAGS.win = /SUBSYSTEM:windows
 $(call VRA_SET_VER_INFO_DLL,VBoxNetDHCPHardened,VirtualAgent DHCP Server,$(VRA_WINDOWS_ICON_FILE)) # Version info / description.
endif


#
# The DHCP server module (dll if hardended)
#
ifdef VRA_WITH_HARDENING
 DLLS    += VBoxNetDHCP
 VBoxNetDHCP_TEMPLATE := VBoxR3Dll
else
 PROGRAMS += VBoxNetDHCP
 VBoxNetDHCP_TEMPLATE := VBoxR3SignedExe
endif

ifdef VRA_WITH_AUTOMATIC_DEFS_QUOTING
 VBoxNetDHCP_DEFS     = KBUILD_TYPE="$(KBUILD_TYPE)"
else
 VBoxNetDHCP_DEFS     = KBUILD_TYPE=\"$(KBUILD_TYPE)\"
endif
VBoxNetDHCP_DEFS       += \
	$(if $(VRA_WITH_INTNET_SERVICE_IN_R3),VRA_WITH_INTNET_SERVICE_IN_R3,)

#VBoxNetDHCP_DEFS     += IPv6
#VBoxNetDHCP_DEFS.linux = WITH_VALGRIND
ifneq ($(KBUILD_TARGET),win)
 VBoxNetDHCP_DEFS    += VRA_WITH_XPCOM
 VBoxNetDHCP_INCS    += $(VRA_XPCOM_INCS)
endif
VBoxNetDHCP_SDKS += VBoxLwipDhcp
VBoxNetDHCP_INCS += \
	../NetLib
VBoxNetDHCP_SOURCES = \
	ClientId.cpp \
	Config.cpp \
	DHCPD.cpp \
	Db.cpp \
	DhcpMessage.cpp \
	DhcpOptions.cpp \
	IPv4Pool.cpp \
	Timestamp.cpp \
	VBoxNetDhcpd.cpp \
	../NetLib/IntNetIf.cpp \
	../../Main/glue/VBoxLogRelCreate.cpp \
	../../Main/glue/GetVBoxUserHomeDirectory.cpp

VBoxNetDHCP_LIBS = \
	$(LIB_RUNTIME)
VBoxNetDHCP_LIBS.solaris += socket nsl
VBoxNetDHCP_LDFLAGS.win = /SUBSYSTEM:windows

ifdef VRA_WITH_HARDENING
 $(call VRA_SET_VER_INFO_DLL,VBoxNetDHCP,VirtualAgent DHCP Server (dll),$(VRA_WINDOWS_ICON_FILE)) # Version info / description.
else
 $(call VRA_SET_VER_INFO_EXE,VBoxNetDHCP,VirtualAgent DHCP Server,$(VRA_WINDOWS_ICON_FILE))       # Version info / description.
endif

include $(FILE_KBUILD_SUB_FOOTER)

