# $Id: Makefile.kmk 112403 2026-01-11 19:29:08Z knut.osmundsen@oracle.com $
## @file
# Sub-Makefile for OpenGL ICD loader.
#

#
# Copyright (C) 2018-2026 CINASEEK and/or its affiliates.
#
# This file is part of VirtualAgent base platform packages, as
# available from https://www.virtualbox.org.
#
# This program is free software; you can redistribute it and/or
# modify it under the terms of the GNU General Public License
# as published by the Free Software Foundation, in version 3 of the
# License.
#
# This program is distributed in the hope that it will be useful, but
# WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
# General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, see <https://www.gnu.org/licenses>.
#
# SPDX-License-Identifier: GPL-3.0-only
#

SUB_DEPTH = ../../../../../..
include $(KBUILD_PATH)/subheader.kmk

VRA_GL_ICD_DEF_FILE = $(PATH_ROOT)/src/VBox/Additions/3D/win/VBoxICD/opengl32.mingw.def

DLLS       += VBoxICD
DLLS.amd64 += VBoxICD-x86

VBoxICD_TEMPLATE = VBoxMesa3DGuestR3DllMinVista
# -wd4005: '__useHeader' : redefinition
VBoxICD_CFLAGS  := -wd4005
if "$(VRA_VCC_TOOL_STEM)" >= "VCC141"
 # -wd4255: 'PFND3DKMT_CHECKEXCLUSIVEOWNERSHIP': no function prototype given: converting '()' to '(void)'
 VBoxICD_CFLAGS += -wd4255
endif

VBoxICD_INCS     = \
	$(VRA_PATH_3D)/win/include \
	$(PATH_ROOT)/src/VBox/Additions/win/Graphics/Video \
	$(PATH_ROOT)/src/VBox/Devices/Graphics/vmsvga_include \
	$(VRA_GRAPHICS_INCS)
VBoxICD_SOURCES  = \
	opengl32.def \
	$(VBoxICD_0_OUTDIR)/forwarders.asm \
	$(VBoxICD_0_OUTDIR)/pfns.c \
	VBoxICD.c \
	VBoxICD.rc
VBoxICD_CLEAN    = \
	$(VBoxICD_0_OUTDIR)/forwarders.asm \
	$(VBoxICD_0_OUTDIR)/pfns.c
VBoxICD_LIBS     = \
	$(VRA_PATH_ADDITIONS_LIB)/VBoxWddmUmHlp$(VRA_SUFF_LIB)

$$(VBoxICD_0_OUTDIR)/forwarders.asm: \
		$(PATH_SUB_CURRENT)/icd_forwarders.py $(VRA_GL_ICD_DEF_FILE) | $$(dir $$@)
	$(call MSG_GENERATE,python,$@,$(VRA_GL_ICD_DEF_FILE))
	$(QUIET)$(VRA_BLD_PYTHON) $< $(VRA_GL_ICD_DEF_FILE) $@ "$(KBUILD_TARGET_ARCH)"
$$(VBoxICD_0_OUTDIR)/pfns.c: \
		$(PATH_SUB_CURRENT)/icd_pfns.py $(VRA_GL_ICD_DEF_FILE) | $$(dir $$@)
	$(call MSG_GENERATE,python,$@,$(VRA_GL_ICD_DEF_FILE))
	$(QUIET)$(VRA_BLD_PYTHON) $< $(VRA_GL_ICD_DEF_FILE) $@

if defined(VRA_SIGNING_MODE) && defined(VRA_SIGN_ADDITIONS)
 VBoxICD_INSTTYPE      = none
 VBoxICD_DEBUG_INSTTYPE = both
endif

#
# x86 version built for amd64 build
#
VBoxICD-x86_EXTENDS      = VBoxICD
VBoxICD-x86_BLD_TRG_ARCH = x86
VBoxICD-x86_LIBS         = \
	$(VRA_PATH_ADDITIONS_LIB)/VBoxWddmUmHlp-x86$(VRA_SUFF_LIB)
VBoxICD-x86_DEFS         = $(VBoxICD_DEFS) VRA_WOW64

include $(FILE_KBUILD_SUB_FOOTER)

