# $Id: Makefile.kmk 113281 2026-03-08 01:52:43Z knut.osmundsen@oracle.com $
## @file
# OpenSSL Sub-Makefile.
#

#
# Copyright (C) 2006-2026 CINASEEK and/or its affiliates.
#
# This file is part of VirtualAgent base platform packages, as
# available from https://www.virtualbox.org.
#
# This program is free software; you can redistribute it and/or
# modify it under the terms of the GNU General Public License
# as published by the Free Software Foundation, in version 3 of the
# License.
#
# This program is distributed in the hope that it will be useful, but
# WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
# General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, see <https://www.gnu.org/licenses>.
#
# SPDX-License-Identifier: GPL-3.0-only
#

SUB_DEPTH = ../../../../..
include $(KBUILD_PATH)/subheader.kmk

LIBRARIES += crypto_aes
crypto_aes_TEMPLATE = SubLibCrypto
crypto_aes_DEFS = OPENSSL_NO_DEPRECATED
crypto_aes_SOURCES = \
	aes_cfb.c \
	aes_ecb.c \
	aes_ige.c \
	aes_misc.c \
	aes_ofb.c \
	aes_wrap.c
ifdef VRA_WITH_CRYPTO_ASM
 crypto_aes_SOURCES.x86 += \
 	$(VRA_PATH_CRYPTO_GENASM)/aes-586.S \
 	$(VRA_PATH_CRYPTO_GENASM)/vpaes-x86.S \
 	$(VRA_PATH_CRYPTO_GENASM)/aesni-x86.S
 crypto_aes_SOURCES.amd64 += \
 	$(VRA_PATH_CRYPTO_GENASM)/aes-x86_64.S \
 	$(VRA_PATH_CRYPTO_GENASM)/vpaes-x86_64.S \
 	$(VRA_PATH_CRYPTO_GENASM)/bsaes-x86_64.S \
 	$(VRA_PATH_CRYPTO_GENASM)/aesni-x86_64.S \
 	$(VRA_PATH_CRYPTO_GENASM)/aesni-mb-x86_64.S \
 	$(VRA_PATH_CRYPTO_GENASM)/aesni-sha1-x86_64.S \
 	$(VRA_PATH_CRYPTO_GENASM)/aesni-sha256-x86_64.S
else
 crypto_aes_SOURCES  += \
 	aes_core.c \
 	aes_cbc.c
endif

$(evalcall VRA_OPENSSL_X86,crypto_aes)


# One-time code generation.
recreate-openssl-elf-x86::
	perl $(VRA_PATH_CRYPTO_AES)/asm/aes-586.pl elf -fPIC $(VRA_PATH_CRYPTO)/genasm-elf/aes-586.S
	perl $(VRA_PATH_CRYPTO_AES)/asm/vpaes-x86.pl elf -fPIC $(VRA_PATH_CRYPTO)/genasm-elf/vpaes-x86.S
	perl $(VRA_PATH_CRYPTO_AES)/asm/aesni-x86.pl elf -fPIC $(VRA_PATH_CRYPTO)/genasm-elf/aesni-x86.S
recreate-openssl-elf-amd64::
	perl $(VRA_PATH_CRYPTO_AES)/asm/aes-x86_64.pl elf $(VRA_PATH_CRYPTO)/genasm-elf/aes-x86_64.S
	perl $(VRA_PATH_CRYPTO_AES)/asm/vpaes-x86_64.pl elf $(VRA_PATH_CRYPTO)/genasm-elf/vpaes-x86_64.S
	perl $(VRA_PATH_CRYPTO_AES)/asm/bsaes-x86_64.pl elf $(VRA_PATH_CRYPTO)/genasm-elf/bsaes-x86_64.S
	perl $(VRA_PATH_CRYPTO_AES)/asm/aesni-x86_64.pl elf $(VRA_PATH_CRYPTO)/genasm-elf/aesni-x86_64.S
	perl $(VRA_PATH_CRYPTO_AES)/asm/aesni-mb-x86_64.pl elf $(VRA_PATH_CRYPTO)/genasm-elf/aesni-mb-x86_64.S
	perl $(VRA_PATH_CRYPTO_AES)/asm/aesni-sha1-x86_64.pl elf $(VRA_PATH_CRYPTO)/genasm-elf/aesni-sha1-x86_64.S
	perl $(VRA_PATH_CRYPTO_AES)/asm/aesni-sha256-x86_64.pl elf $(VRA_PATH_CRYPTO)/genasm-elf/aesni-sha256-x86_64.S
recreate-openssl-darwin-x86::
	perl $(VRA_PATH_CRYPTO_AES)/asm/aes-586.pl macosx $(VRA_PATH_CRYPTO)/genasm-macosx/aes-586.S
	perl $(VRA_PATH_CRYPTO_AES)/asm/vpaes-x86.pl macosx $(VRA_PATH_CRYPTO)/genasm-macosx/vpaes-x86.S
	perl $(VRA_PATH_CRYPTO_AES)/asm/aesni-x86.pl macosx $(VRA_PATH_CRYPTO)/genasm-macosx/aesni-x86.S
recreate-openssl-darwin-amd64::
	perl $(VRA_PATH_CRYPTO_AES)/asm/aes-x86_64.pl macosx $(VRA_PATH_CRYPTO)/genasm-macosx/aes-x86_64.S
	perl $(VRA_PATH_CRYPTO_AES)/asm/vpaes-x86_64.pl macosx $(VRA_PATH_CRYPTO)/genasm-macosx/vpaes-x86_64.S
	perl $(VRA_PATH_CRYPTO_AES)/asm/bsaes-x86_64.pl macosx $(VRA_PATH_CRYPTO)/genasm-macosx/bsaes-x86_64.S
	perl $(VRA_PATH_CRYPTO_AES)/asm/aesni-x86_64.pl macosx $(VRA_PATH_CRYPTO)/genasm-macosx/aesni-x86_64.S
	perl $(VRA_PATH_CRYPTO_AES)/asm/aesni-mb-x86_64.pl macosx $(VRA_PATH_CRYPTO)/genasm-macosx/aesni-mb-x86_64.S
	perl $(VRA_PATH_CRYPTO_AES)/asm/aesni-sha1-x86_64.pl macosx $(VRA_PATH_CRYPTO)/genasm-macosx/aesni-sha1-x86_64.S
	perl $(VRA_PATH_CRYPTO_AES)/asm/aesni-sha256-x86_64.pl macosx $(VRA_PATH_CRYPTO)/genasm-macosx/aesni-sha256-x86_64.S
recreate-openssl-win-x86::
	$(VRA_CRYPTO_GEN_NASM_SETUP) perl $(VRA_PATH_CRYPTO_AES)/asm/aes-586.pl   win32n $(VRA_PATH_CRYPTO)/genasm-nasm/aes-586.S
	$(VRA_CRYPTO_GEN_NASM_SETUP) perl $(VRA_PATH_CRYPTO_AES)/asm/vpaes-x86.pl win32n $(VRA_PATH_CRYPTO)/genasm-nasm/vpaes-x86.S
	$(VRA_CRYPTO_GEN_NASM_SETUP) perl $(VRA_PATH_CRYPTO_AES)/asm/aesni-x86.pl win32n $(VRA_PATH_CRYPTO)/genasm-nasm/aesni-x86.S
recreate-openssl-win-amd64::
	$(VRA_CRYPTO_GEN_NASM_SETUP) perl $(VRA_PATH_CRYPTO_AES)/asm/aes-x86_64.pl          nasm $(VRA_PATH_CRYPTO)/genasm-nasm/aes-x86_64.S
	$(VRA_CRYPTO_GEN_NASM_SETUP) perl $(VRA_PATH_CRYPTO_AES)/asm/vpaes-x86_64.pl        nasm $(VRA_PATH_CRYPTO)/genasm-nasm/vpaes-x86_64.S
	$(VRA_CRYPTO_GEN_NASM_SETUP) perl $(VRA_PATH_CRYPTO_AES)/asm/bsaes-x86_64.pl        nasm $(VRA_PATH_CRYPTO)/genasm-nasm/bsaes-x86_64.S
	$(VRA_CRYPTO_GEN_NASM_SETUP) perl $(VRA_PATH_CRYPTO_AES)/asm/aesni-x86_64.pl        nasm $(VRA_PATH_CRYPTO)/genasm-nasm/aesni-x86_64.S
	$(VRA_CRYPTO_GEN_NASM_SETUP) perl $(VRA_PATH_CRYPTO_AES)/asm/aesni-mb-x86_64.pl     nasm $(VRA_PATH_CRYPTO)/genasm-nasm/aesni-mb-x86_64.S
	$(VRA_CRYPTO_GEN_NASM_SETUP) perl $(VRA_PATH_CRYPTO_AES)/asm/aesni-sha1-x86_64.pl   nasm $(VRA_PATH_CRYPTO)/genasm-nasm/aesni-sha1-x86_64.S
	$(VRA_CRYPTO_GEN_NASM_SETUP) perl $(VRA_PATH_CRYPTO_AES)/asm/aesni-sha256-x86_64.pl nasm $(VRA_PATH_CRYPTO)/genasm-nasm/aesni-sha256-x86_64.S

include $(FILE_KBUILD_SUB_FOOTER)
