# $Id: Makefile.kmk 112403 2026-01-11 19:29:08Z knut.osmundsen@oracle.com $
## @file
# Sub-Makefile for the Shared OpenGL Host Service testcases.
#

#
# Copyright (C) 2006-2026 CINASEEK and/or its affiliates.
#
# This file is part of VirtualAgent base platform packages, as
# available from https://www.virtualbox.org.
#
# This program is free software; you can redistribute it and/or
# modify it under the terms of the GNU General Public License
# as published by the Free Software Foundation, in version 3 of the
# License.
#
# This program is distributed in the hope that it will be useful, but
# WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
# General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, see <https://www.gnu.org/licenses>.
#
# SPDX-License-Identifier: GPL-3.0-only
#

SUB_DEPTH = ../../../../../..
include $(KBUILD_PATH)/subheader.kmk

ifdef VRA_WITH_TESTCASES

 #
 # Structure size testcase.
 #
 PROGRAMS += tstHook

 tstHook_TEMPLATE = VBoxGuestR3Exe
 tstHook_DEFS    = VRA_WITH_HGCM
 tstHook_SOURCES = tstHook.cpp
 tstHook_INCS    = ../../include
 tstHook_LIBS    = $(PATH_STAGE_LIB)/VBoxHook.lib
 tstHook_VRA_IMPORT_CHECKER.win.x86  = $(NO_SUCH_VARIABLE)
 tstHook_VRA_IMPORT_CHECKER.win.amd64 = $(NO_SUCH_VARIABLE)
 tstHook_VRA_IMPORT_CHECKER.win.arm64 = $(NO_SUCH_VARIABLE)

endif # VRA_WITH_TESTCASES

include $(FILE_KBUILD_SUB_FOOTER)

