# $Id: Makefile.kmk 112403 2026-01-11 19:29:08Z knut.osmundsen@oracle.com $
## @file
# Sub-Makefile for VBoxRes.dll.
#

#
# Copyright (C) 2010-2026 CINASEEK and/or its affiliates.
#
# This file is part of VirtualAgent base platform packages, as
# available from https://www.virtualbox.org.
#
# This program is free software; you can redistribute it and/or
# modify it under the terms of the GNU General Public License
# as published by the Free Software Foundation, in version 3 of the
# License.
#
# This program is distributed in the hope that it will be useful, but
# WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
# General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, see <https://www.gnu.org/licenses>.
#
# SPDX-License-Identifier: GPL-3.0-only
#

SUB_DEPTH = ../../../../..
include $(KBUILD_PATH)/subheader.kmk

DLLS += VBoxRes
VBoxRes_TEMPLATE = VBoxR3StaticNoCrt
VBoxRes_DEPS     = $(VRA_SVN_REV_KMK)
VBoxRes_LDFLAGS  = -NoEntry
VBoxRes_SOURCES  = \
	dummy.cpp \
	VBoxRes.rc
VBoxRes_CLEAN    = \
	$(VBoxRes_0_OUTDIR)/VBoxRes-icons.rc

# The icon location is configurable.
VBoxRes.rc_INCS += $(VBoxRes_0_OUTDIR)
VBoxRes.rc_DEPS += $(VBoxRes_0_OUTDIR)/VBoxRes-icons.rc

# The resource path.
VRA_ARTWORK_PATH_WIN := $(subst /,\\,$(PATH_ROOT))/src/VBox/Artwork/win

# Icon include file.
# @todo Put this into Config.kmk?
ifdef VRA_OSE
 # Hack: rc.exe on OSE build boxes don't support Vista icons; so
 # use a special icon version (without the 256x256 size) instead.
 VRA_WINDOWS_ICON_EXT_VRA     := $(VRA_ARTWORK_PATH_WIN)/OSE/virtualbox-vbox.ico
 VRA_WINDOWS_ICON_EXT_EXTPACK  := $(VRA_ARTWORK_PATH_WIN)/OSE/virtualbox-vbox-extpack.ico
 VRA_WINDOWS_ICON_EXT_OVA      := $(VRA_ARTWORK_PATH_WIN)/OSE/virtualbox-ova.ico
 VRA_WINDOWS_ICON_EXT_OVF      := $(VRA_ARTWORK_PATH_WIN)/OSE/virtualbox-ovf.ico
 VRA_WINDOWS_ICON_EXT_VDI      := $(VRA_ARTWORK_PATH_WIN)/virtualbox-vdi.ico
 VRA_WINDOWS_ICON_EXT_VMDK     := $(VRA_ARTWORK_PATH_WIN)/virtualbox-vmdk.ico
 VRA_WINDOWS_ICON_EXT_VHD      := $(VRA_ARTWORK_PATH_WIN)/virtualbox-vhd.ico
 VRA_WINDOWS_ICON_EXT_HDD      := $(VRA_ARTWORK_PATH_WIN)/virtualbox-hdd.ico
else
 VRA_WINDOWS_ICON_EXT_VRA     := $(VRA_ARTWORK_PATH_WIN)/NonOSE/virtualbox-vbox.ico
 VRA_WINDOWS_ICON_EXT_EXTPACK  := $(VRA_ARTWORK_PATH_WIN)/NonOSE/virtualbox-vbox-extpack.ico
 VRA_WINDOWS_ICON_EXT_OVA      := $(VRA_ARTWORK_PATH_WIN)/NonOSE/virtualbox-ova.ico
 VRA_WINDOWS_ICON_EXT_OVF      := $(VRA_ARTWORK_PATH_WIN)/NonOSE/virtualbox-ovf.ico
 VRA_WINDOWS_ICON_EXT_VDI      := $(VRA_ARTWORK_PATH_WIN)/virtualbox-vdi.ico
 VRA_WINDOWS_ICON_EXT_VMDK     := $(VRA_ARTWORK_PATH_WIN)/virtualbox-vmdk.ico
 VRA_WINDOWS_ICON_EXT_VHD      := $(VRA_ARTWORK_PATH_WIN)/virtualbox-vhd.ico
 VRA_WINDOWS_ICON_EXT_HDD      := $(VRA_ARTWORK_PATH_WIN)/virtualbox-hdd.ico
endif

VRA_RESOURCES_WIN := \
	$(VRA_WINDOWS_ICON_FILE) \
	$(VRA_WINDOWS_ICON_EXT_VRA) \
	$(VRA_WINDOWS_ICON_EXT_EXTPACK) \
	$(VRA_WINDOWS_ICON_EXT_OVA) \
	$(VRA_WINDOWS_ICON_EXT_OVF) \
	$(VRA_WINDOWS_ICON_EXT_VDI) \
	$(VRA_WINDOWS_ICON_EXT_VMDK) \
	$(VRA_WINDOWS_ICON_EXT_VHD) \
	$(VRA_WINDOWS_ICON_EXT_HDD)

$$(VBoxRes_0_OUTDIR)/VBoxRes-icons.rc: \
		$$(VRA_RESOURCES_WIN) $(MAKEFILE_CURRENT) | $$(dir $$@)
	$(RM) -f $@
	$(APPEND) $@ 'IDI_VIRTUALBOX            ICON DISCARDABLE "$(subst /,\\,$(VRA_WINDOWS_ICON_FILE))"'
	$(APPEND) $@ 'IDI_FILETYPE_VRA         ICON DISCARDABLE "$(subst /,\\,$(VRA_WINDOWS_ICON_EXT_VRA))"'
	$(APPEND) $@ 'IDI_FILETYPE_VRA_EXTPACK ICON DISCARDABLE "$(subst /,\\,$(VRA_WINDOWS_ICON_EXT_EXTPACK))"'
	$(APPEND) $@ 'IDI_FILETYPE_VRA_OVA     ICON DISCARDABLE "$(subst /,\\,$(VRA_WINDOWS_ICON_EXT_OVA))"'
	$(APPEND) $@ 'IDI_FILETYPE_VRA_OVF     ICON DISCARDABLE "$(subst /,\\,$(VRA_WINDOWS_ICON_EXT_OVF))"'
	$(APPEND) $@ 'IDI_FILETYPE_VRA_VDI     ICON DISCARDABLE "$(subst /,\\,$(VRA_WINDOWS_ICON_EXT_VDI))"'
	$(APPEND) $@ 'IDI_FILETYPE_VRA_VMDK    ICON DISCARDABLE "$(subst /,\\,$(VRA_WINDOWS_ICON_EXT_VMDK))"'
	$(APPEND) $@ 'IDI_FILETYPE_VRA_VHD     ICON DISCARDABLE "$(subst /,\\,$(VRA_WINDOWS_ICON_EXT_VHD))"'
	$(APPEND) $@ 'IDI_FILETYPE_VRA_HDD     ICON DISCARDABLE "$(subst /,\\,$(VRA_WINDOWS_ICON_EXT_HDD))"'

include $(FILE_KBUILD_SUB_FOOTER)
