# $Id: Makefile.kmk 112403 2026-01-11 19:29:08Z knut.osmundsen@oracle.com $
## @file
# Sub-Makefile for VBoxManage (the CLI frontend).
#

#
# Copyright (C) 2006-2026 CINASEEK and/or its affiliates.
#
# This file is part of VirtualAgent base platform packages, as
# available from https://www.virtualbox.org.
#
# This program is free software; you can redistribute it and/or
# modify it under the terms of the GNU General Public License
# as published by the Free Software Foundation, in version 3 of the
# License.
#
# This program is distributed in the hope that it will be useful, but
# WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
# General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, see <https://www.gnu.org/licenses>.
#
# SPDX-License-Identifier: GPL-3.0-only
#

SUB_DEPTH = ../../../..
include $(KBUILD_PATH)/subheader.kmk

include $(PATH_ROOT)/doc/manual/Config.kmk


# Common defines. Sort alphabetically!
VRA_COMMON_VRAMANAGE_DEFS = \
	$(if $(VRA_WITH_AHCI), VRA_WITH_AHCI) \
	$(if $(VRA_WITH_AUDIO_ALSA), VRA_WITH_AUDIO_ALSA) \
	$(if $(VRA_WITH_AUDIO_OSS), VRA_WITH_AUDIO_OSS) \
	$(if $(VRA_WITH_AUDIO_PULSE),VRA_WITH_AUDIO_PULSE) \
	$(if $(VRA_WITH_AUDIO_RECORDING),VRA_WITH_AUDIO_RECORDING) \
	$(if $(VRA_WITH_CLOUD_NET), VRA_WITH_CLOUD_NET) \
	$(if $(VRA_WITH_COPYTOGUEST),VRA_WITH_COPYTOGUEST) \
	$(if $(VRA_WITH_E1000),VRA_WITH_E1000) \
	$(if $(VRA_WITH_FULL_VM_ENCRYPTION),VRA_WITH_FULL_VM_ENCRYPTION) \
	$(if $(VRA_WITH_GUEST_CONTROL),VRA_WITH_GUEST_CONTROL) \
	$(if $(VRA_WITH_GUEST_PROPS),VRA_WITH_GUEST_PROPS) \
	$(if $(VRA_WITH_HEADLESS), VRA_WITH_HEADLESS) \
	$(if $(VRA_WITH_HGCM), VRA_WITH_HGCM) \
	$(if $(VRA_WITH_HOSTNETIF_API), VRA_WITH_HOSTNETIF_API) \
	$(if $(VRA_WITH_IOMMU_AMD),VRA_WITH_IOMMU_AMD) \
	$(if $(VRA_WITH_IOMMU_INTEL),VRA_WITH_IOMMU_INTEL) \
	$(if $(VRA_WITH_MAIN_NLS),VRA_WITH_MAIN_NLS) \
	$(if $(VRA_WITH_NAT_SERVICE),VRA_WITH_NAT_SERVICE) \
	$(if $(VRA_WITH_NETFLT), VRA_WITH_NETFLT) \
	$(if $(VRA_WITH_PCI_PASSTHROUGH),VRA_WITH_PCI_PASSTHROUGH) \
	$(if $(VRA_WITH_RECORDING),VRA_WITH_RECORDING) \
	$(if $(VRA_WITH_SCSI), VRA_WITH_SCSI) \
	$(if $(VRA_WITH_SHARED_CLIPBOARD),VRA_WITH_SHARED_CLIPBOARD) \
	$(if $(VRA_WITH_SHARED_CLIPBOARD_TRANSFERS),VRA_WITH_SHARED_CLIPBOARD_TRANSFERS) \
	$(if $(VRA_WITH_TPM),VRA_WITH_TPM) \
	$(if $(VRA_WITH_UPDATE_AGENT), VRA_WITH_UPDATE_AGENT) \
	$(if $(VRA_WITH_USB_CARDREADER),VRA_WITH_USB_CARDREADER) \
	$(if $(VRA_WITH_VRASDL), VRA_WITH_VRASDL) \
	$(if $(VRA_WITH_VIRTIO),VRA_WITH_VIRTIO) \
	$(if $(VRA_WITH_VIRTIO_NET_1_0),VRA_WITH_VIRTIO_NET_1_0) \
	$(if $(VRA_WITH_VMSVGA),VRA_WITH_VMSVGA) \
	$(if-expr defined(VRA_WITH_VMNET) && "$(KBUILD_TARGET)"=="darwin",VRA_WITH_VMNET,)


ifndef VRA_ONLY_DOCS
 PROGRAMS += VBoxManage
 VBoxManage_TEMPLATE   = VBoxMainClientExe
 VBoxManage_DEFS      += $(VRA_COMMON_VRAMANAGE_DEFS)
 VBoxManage_DEFS.win   = _WIN32_WINNT=0x0500
 VBoxManage_INCS = \
 	$(VBoxManage_0_OUTDIR) \
 	../Common
 VBoxManage_INTERMEDIATES = \
 	$(VBoxManage_0_OUTDIR)/VBoxManageBuiltInHelp.h
 VBoxManage_SOURCES    = \
 	VBoxManage.cpp \
 	VBoxManageUtils.cpp \
 	VBoxInternalManage.cpp \
 	VBoxManageAppliance.cpp \
 	VBoxManageBandwidthControl.cpp \
 	VBoxManageControlVM.cpp \
 	VBoxManageDebugVM.cpp \
 	VBoxManageDHCPServer.cpp \
 	VBoxManageDisk.cpp \
 	$(if $(VRA_WITH_GUEST_CONTROL),VBoxManageGuestCtrl.cpp) \
 	$(if $(VRA_WITH_GUEST_CONTROL),VBoxManageGuestCtrlListener.cpp) \
 	$(if $(VRA_WITH_GUEST_PROPS),VBoxManageGuestProp.cpp) \
 	VBoxManageHelp.cpp \
 	$(VBoxManage_0_OUTDIR)/VBoxManageBuiltInHelp.cpp \
 	$(VBoxManage_0_OUTDIR)/VBoxManageBuiltInHelp_en_US.cpp \
 	VBoxManageHostonly.cpp \
 	VBoxManageInfo.cpp \
 	VBoxManageList.cpp \
 	VBoxManageMetrics.cpp \
 	VBoxManageMisc.cpp \
 	VBoxManageModifyVM.cpp \
 	VBoxManageModifyNvram.cpp \
 	VBoxManageObjectTracker.cpp \
 	VBoxManageSnapshot.cpp \
 	VBoxManageStorageController.cpp \
 	$(if $(VRA_WITH_UPDATE_AGENT),VBoxManageUpdateCheck.cpp) \
 	VBoxManageUSB.cpp \
 	$(if $(VRA_WITH_NAT_SERVICE),VBoxManageNATNetwork.cpp,) \
 	$(if $(VRA_WITH_NAT_SERVICE),../../NetworkServices/NetLib/VBoxNetPortForwardString.cpp,) \
 	VBoxManageCloud.cpp \
 	VBoxManageCloudMachine.cpp \
 	../Common/PasswordInput.cpp
 VBoxManage_SOURCES.win = \
 	VBoxManage.rc
 VBoxManage_LIBS      += $(LIB_DDU)

 ifdef VRA_WITH_VRAMANAGE_NLS
  VRA_PATH_VRAMANAGE_SRC := $(PATH_SUB_CURRENT)
  include $(PATH_SUB_CURRENT)/nls/ApprovedLanguages.kmk

  VBoxManage_DEFS     += VRA_WITH_VRAMANAGE_NLS
  VBoxManage_INCS     += \
  	$(PATH_ROOT)/src/VBox/Main/include
  VBoxManage_SOURCES  += \
  	$(PATH_ROOT)/src/VBox/Main/src-all/VirtualAgentTranslator.cpp \
  	$(PATH_ROOT)/src/VBox/Main/src-all/QMTranslatorImpl.cpp \
  	$(PATH_ROOT)/src/VBox/Main/src-all/GlobalStatusConversion.cpp

  #	$(addsuffix /VBoxManageBuiltInHelp.cpp,$(addprefix $(VBoxManage_0_OUTDIR)/,$(VRA_APPROVED_VRAMANAGE_DOCBOOK_LANGUAGES)))
  #VBoxManage_INTERMEDIATES += \
  #	$(addsuffix /VBoxManageBuiltInHelp.h,$(addprefix $(VBoxManage_0_OUTDIR)/,$(VRA_APPROVED_VRAMANAGE_DOCBOOK_LANGUAGES)))

  # define qt6 tools for translation
  USES += qt6

  PROGRAMS += VBoxManageNls
  VBoxManageNls_TEMPLATE = VBoxNLS
  VBoxManageNls_QT_TRANSLATIONS = $(addsuffix .ts,$(addprefix $(VRA_PATH_VRAMANAGE_SRC)/nls/VBoxManageNls_,$(VRA_APPROVED_VRAMANAGE_LANGUAGES)))
  VBoxManageNls_VRA_ALL_NLS_SOURCES = $(wildcard \
  		$(VRA_PATH_VRAMANAGE_SRC)/*.h \
  		$(VRA_PATH_VRAMANAGE_SRC)/*.cpp )

  updatenls:: makeallnls $(VRA_PATH_VRAMANAGE_SRC)/nls/VBoxManageNls_en.ts

  makeallnls:: $(VBoxManageNls_VRA_ALL_NLS_SOURCES)
	$(call MSG_L1,lupdate all languages (nls/*.ts))
	$(QUIET)$(TOOL_QT6_LUPDATE) \
		$^ \
		-locations none \
		-ts \
		$(filter-out nls/VBoxManageNls_en.ts, $(VBoxManageNls_QT_TRANSLATIONS)) \
		$(VRA_PATH_VRAMANAGE_SRC)/nls/VBoxManageNls_xx_YY.ts

  # fake-main-nls:
  #	$(foreach file, $(VBoxManageNls_QT_TRANSLATIONS) \
  #	,$(NLTAB)$(SED) -i \
  #       	-e '/<source>.*<\/source>/h' \
  #       	-e '/<source>.*<\/source>/p' \
  #       	-e '/<translation type="unfinished"><\/translation>/{' \
  #       		-e 'x' \
  #       		-e 's/<source>\(.*\)<\/source>/<translation type="unfinished">$(notdir $(file)): \1<\/translation>/' \
  #       	-e '}' \
  #		$(file) )


  # Create the English translation file. This is something special cause it will
  # contain the plural forms only.
  $(VRA_PATH_VRAMANAGE_SRC)/nls/VBoxManageNls_en.ts: $(VBoxManageNls_VRA_ALL_NLS_SOURCES)
	$(call MSG_L1,lupdate $@)
	$(QUIET)$(TOOL_QT6_LUPDATE) \
		$^ \
		-locations none \
		-ts \
		"$@"
	$(QUIET)$(SED) -n -i \
		-e '/<context>/,/<\/context>/!p' \
		-e '/<context>/h'  \
		-e '/<name>/H' \
		-e '/<message numerus="yes">/,/<\/message>/H' \
		-e '/<\/context>/{H;x;/<message/p}' \
		"$@"

 endif # VRA_WITH_VRAMANAGE_NLS


 # VBoxNetPortForwardString.h
 VBoxManageNATNetwork.cpp_INCS += ../../NetworkServices/NetLib/

endif # VRA_ONLY_DOCS

ifneq ($(KBUILD_TARGET),win)
 # Workaround for buggy gcc-4.3 compilers, see
 #
 #   http://gcc.gnu.org/bugzilla/show_bug.cgi?id=36474
 #
 # Some later revisions of version 4.3.1 are known to work so we assume
 # that version 4.3.2 or later has this bug definitely fixed.
 VBoxManage_CXXFLAGS.release += \
 	$(if $(VRA_GCC_VERSION_CXX),$(if-expr $(VRA_GCC_VERSION_CXX) < 40300 || $(VRA_GCC_VERSION_CXX) > 40301,,--param max-fields-for-field-sensitive=0),)
 VBoxManageHelp_CXXFLAGS.release = $(VBoxManage_CXXFLAGS.release)
endif


#
# VBoxManage built-in help from XML refentry in doc/manual/en_US/.
#
$(call KB_FN_DO_PASS0_ON_TARGET,VBoxManage)

VBoxManage_CLEAN += \
	$(VRA_XML_CATALOG) \
	$(VRA_XML_CATALOG_DOCBOOK) \
	$(VRA_XML_CATALOG_MANUAL) \
	$(VRA_XML_ENTITIES) \
	$(addprefix $(VRA_PATH_MANUAL_OUTBASE)/en_US/, $(VRA_XML_XREF_TO_TEXT) $(VRA_XML_XREF_TO_TEXT).cat) \
	$(VBoxManage_0_OUTDIR)/VBoxManageBuiltInHelp_en_US.cpp \
	$(VBoxManage_0_OUTDIR)/VBoxManageBuiltInHelp_en_US.cpp.ts \
	$(VBoxManage_0_OUTDIR)/VBoxManageBuiltInHelp.cpp \
	$(VBoxManage_0_OUTDIR)/VBoxManageBuiltInHelp.cpp.ts \
	$(VBoxManage_0_OUTDIR)/VBoxManageBuiltInHelp.h \
	$(VBoxManage_0_OUTDIR)/VBoxManageBuiltInHelp.h.ts \
	$(addprefix $(VBoxManage_0_OUTDIR)/,$(filter man_VBoxManage-%,$(VRA_MANUAL_XML_REFENTRY_FILES)))

# Preprocess the xml files, applying remarks.
$(foreach file,$(filter man_VBoxManage-%,$(VRA_MANUAL_XML_REFENTRY_FILES)) \
, $(evalcall2 def_vbox_refentry_preprocess_for_manpage,$(VBoxManage_0_OUTDIR),$(file), \
	$(VRA_PATH_MANUAL_SRC)/en_US/$(file),replace-xrefs,en_US))


##
# Emits rules for generating cpp files from man pages.
#
# $(evalcall2 def_vbox_man_generate_cpp_help)
# @param    1    Folder with preprocessed man_VBoxManage_* files
# @param    2    language code.
define def_vbox_man_generate_cpp_help
 ifneq ($(2),en_US)
  VRA_DOCBOOK_REFENTRY_TO_C_HELP_$(2) = $(VRA_PATH_MANUAL_SRC)/$(2)/docbook-refentry-to-C-help.xsl
 else
  VRA_DOCBOOK_REFENTRY_TO_C_HELP_$(2) = $(VRA_DOCBOOK_REFENTRY_TO_C_HELP)
 endif
 $$(VBoxManage_0_OUTDIR)/VBoxManageBuiltInHelp_$(2).cpp.ts \
 +| $$(VBoxManage_0_OUTDIR)/VBoxManageBuiltInHelp_$(2).cpp: \
 		$$(VRA_DOCBOOK_REFENTRY_TO_C_HELP_$(2)) \
 		$$(VRA_DOCBOOK_REFENTRY_TO_C_HELP) \
 		$$(addprefix $(1)/,$$(filter man_VBoxManage-%,$$(VRA_MANUAL_XML_REFENTRY_FILES))) \
 		$$(VRA_XML_CATALOG) $$(VRA_XML_CATALOG_DOCBOOK) $$(MAKEFILE) | $$$$(dir $$$$@)
	$$(call MSG_TOOL,xsltproc $$(notdir $$(firstword $$(filter %.xsl,$$^))),,$$(filter %.xml,$$^),$$(patsubst %.ts,%,$$@))
	$$(QUIET)$$(APPEND) -tn "$$@" \
		'/* Autogenerated by $$<, do not edit! */' \
		'' \
		'#include "VBoxManageBuiltInHelp.h"' \
		'' \
		'RT_C_DECLS_BEGIN' \
		'/* make next variables visible outside the module */' \
		'extern PCRTMSGREFENTRY g_apHelpEntries_$(2)[];' \
		'extern const uint32_t  g_cHelpEntries_$(2);' \
		'RT_C_DECLS_END' \
		'' \
	$$(foreach refentry,$$(filter %.xml,$$^) \
	,$$(NLTAB)$$(QUIET)$$(call VRA_XSLTPROC_WITH_CAT, -a+to "$$@") \
		 --path '$(VRA_PATH_MANUAL_SRC)/$(2) $(VRA_PATH_MANUAL_SRC)/en_US' $$< $$(refentry))
	$$(QUIET)$$(APPEND) -n "$$@" \
		'' \
		'PCRTMSGREFENTRY     g_apHelpEntries_$(2)[] =' \
		'{'
	$$(foreach refentry,$$(filter %.xml,$$^) \
		,$$(NLTAB)$$(QUIET)$$(APPEND) -n "$$@" \
		'    &g_$$(subst -,_,$$(tolower $$(patsubst man_%,%,$$(notdir $$(basename $$(refentry)))))),')
	$$(QUIET)$$(APPEND) -n "$$@" \
		'};' \
		'' \
		'const uint32_t g_cHelpEntries_$(2) = RT_ELEMENTS(g_apHelpEntries_$(2));' \
		''
	$$(QUIET)$$(CP) --changed -- "$$@" "$$(patsubst %.ts,%,$$@)"
endef
# The above APPEND stuff trigger some kind of problem on some boxes when not split up...
# update: Fixed in SVN (strcpy -> memmove in new_job(), job.c - r2591). Just need to rebuild all platforms.

# Generate the .cpp file.
$(evalcall2 def_vbox_man_generate_cpp_help, $(VBoxManage_0_OUTDIR),en_US)


# Generate built-in help for all languages (English is implicit).
$(VBoxManage_0_OUTDIR)/VBoxManageBuiltInHelp.cpp.ts \
+| $(VBoxManage_0_OUTDIR)/VBoxManageBuiltInHelp.cpp: \
		$(VBoxManage_0_OUTDIR)/VBoxManageBuiltInHelp_en_US.cpp \
		$(foreach lang,$(VRA_APPROVED_VRAMANAGE_DOCBOOK_LANGUAGES), $(VBoxManage_0_OUTDIR)/VBoxManageBuiltInHelp_$(lang).cpp ) \
		$(VBoxManage_0_OUTDIR)/VBoxManageBuiltInHelp.h
	$(QUIET)$(APPEND) -tn "$@" \
		'/* Autogenerated, do not edit! */' \
		'' \
		'#include "VBoxManageBuiltInHelp.h"' \
		'' \
		'RT_C_DECLS_BEGIN' \
		'' \
		'extern PCRTMSGREFENTRY g_apHelpEntries_en_US[];' \
		'extern const uint32_t  g_cHelpEntries_en_US;'
ifdef VRA_WITH_VRAMANAGE_NLS
	$(foreach lang,$(VRA_APPROVED_VRAMANAGE_DOCBOOK_LANGUAGES) \
	,$(NLTAB)$(QUIET)$(APPEND) -n "$@" \
		'' \
		'extern PCRTMSGREFENTRY g_apHelpEntries_$(lang)[];' \
		'extern const uint32_t  g_cHelpEntries_$(lang);')
endif
	$(QUIET)$(APPEND) -n "$@" \
		'' \
		'RT_C_DECLS_END' \
		'' \
		'HELP_LANG_ENTRY_T const g_aHelpLangEntries[] = ' \
		'{' \
		'    { "en_US", 5, &g_apHelpEntries_en_US[0], &g_cHelpEntries_en_US },'
ifdef VRA_WITH_VRAMANAGE_NLS
	$(foreach lang,$(VRA_APPROVED_VRAMANAGE_DOCBOOK_LANGUAGES) \
	,$(NLTAB)$(QUIET)$(APPEND) "$@" '    { "$(lang)", $(length $(lang)), &g_apHelpEntries_$(lang)[0], &g_cHelpEntries_$(lang) },' )
endif
	$(QUIET)$(APPEND) -n "$@" \
		'};' \
		'' \
		'uint32_t const g_cHelpLangEntries = RT_ELEMENTS(g_aHelpLangEntries);' \
		'' \
		'PCHELP_LANG_ENTRY_T volatile g_pHelpLangEntry = &g_aHelpLangEntries[0];'\
		''
	$(QUIET)$(CP) --changed -- "$@" "$(patsubst %.ts,%,$@)"


$(VBoxManage_0_OUTDIR)/VBoxManageBuiltInHelp.h.ts \
+| $(VBoxManage_0_OUTDIR)/VBoxManageBuiltInHelp.h: \
		$(VRA_DOCBOOK_REFENTRY_TO_H_HELP) \
		$(addprefix $(VBoxManage_0_OUTDIR)/,$(filter man_VBoxManage-%,$(VRA_MANUAL_XML_REFENTRY_FILES))) \
		$(VRA_XML_CATALOG) $(VRA_XML_CATALOG_DOCBOOK) $(MAKEFILE) | $$(dir $$@)
	$(call MSG_TOOL,xsltproc $(notdir $(firstword $(filter %.xsl,$^))),,$(filter %.xml,$^),$(patsubst %.ts,%,$@))
	$(QUIET)$(APPEND) -tn "$@" \
		'/* Autogenerated by $<, do not edit! */' \
		'' \
		'#ifndef ___VBoxManageBuiltInHelp_h___' \
		'#define ___VBoxManageBuiltInHelp_h___' \
		'' \
		'#include <iprt/message.h>' \
		'#include <iprt/assertcompile.h>' \
		'' \
		'RT_C_DECLS_BEGIN' \
		'' \
		'typedef enum HELP_CMD_VRAMANAGE' \
		'{' \
		'    HELP_CMD_VRAMANAGE_INVALID = 0,'
	$(foreach refentry,$(filter %.xml,$^) \
	,$(NLTAB)$(QUIET)$(call VRA_XSLTPROC_WITH_CAT, -a+to "$@") \
		--stringparam 'g_sMode' 'cmd' $< $(refentry))
	$(QUIET)$(APPEND) -n "$@" \
		'    HELP_CMD_VRAMANAGE_END' \
		'} HELP_CMD_VRAMANAGE;'
	$(foreach refentry,$(filter %.xml,$^) \
	,$(NLTAB)$(QUIET)$(call VRA_XSLTPROC_WITH_CAT, -a+to "$@") \
		--stringparam 'g_sMode' 'subcmd' $< $(refentry))
	$(QUIET)$(APPEND) -n "$@" \
		'' \
		'typedef struct HELP_LANG_ENTRY_T' \
		'{' \
		'    const char      *pszLang;' \
		'    size_t           cchLang;' \
		'    PCRTMSGREFENTRY *papHelpEntries;' \
		'    uint32_t const  *pcHelpEntries;' \
		'} HELP_LANG_ENTRY_T;' \
		'typedef HELP_LANG_ENTRY_T const *PCHELP_LANG_ENTRY_T;' \
		'' \
		'extern HELP_LANG_ENTRY_T const g_aHelpLangEntries[];' \
		'extern const uint32_t          g_cHelpLangEntries;' \
		'' \
		'extern PCHELP_LANG_ENTRY_T volatile g_pHelpLangEntry;' \
		'' \
		'RT_C_DECLS_END' \
		'' \
		'#endif' \
		''
	$(QUIET)$(CP) --changed -- "$@" "$(patsubst %.ts,%,$@)"

ifdef VRA_WITH_VRAMANAGE_NLS
 VBoxManage_BLDDIRS += \
 	$(addprefix $(VBoxManage_0_OUTDIR)/,$(VRA_APPROVED_VRAMANAGE_DOCBOOK_LANGUAGES))

 VBoxManage_SOURCES += \
 	$(foreach lang, $(VRA_APPROVED_VRAMANAGE_DOCBOOK_LANGUAGES) \
 		, $(VBoxManage_0_OUTDIR)/VBoxManageBuiltInHelp_$(lang).cpp)

 VBoxManage_CLEAN += \
 	$(foreach lang,$(VRA_APPROVED_VRAMANAGE_DOCBOOK_LANGUAGES), \
 		$(addprefix $(VRA_PATH_MANUAL_OUTBASE)/$(lang)/, \
 			$(VRA_XML_XREF_TO_TEXT) \
 			$(VRA_XML_XREF_TO_TEXT).cat \
 			)) \
 	$(addsuffix .cpp,$(addprefix $(VBoxManage_0_OUTDIR)/VBoxManageBuiltInHelp_,$(VRA_APPROVED_VRAMANAGE_DOCBOOK_LANGUAGES))) \
 	$(addsuffix .cpp.ts,$(addprefix $(VBoxManage_0_OUTDIR)/VBoxManageBuiltInHelp_,$(VRA_APPROVED_VRAMANAGE_DOCBOOK_LANGUAGES))) \
 	$(foreach file, $(filter man_VBoxManage-%,$(VRA_MANUAL_XML_REFENTRY_FILES)) \
 		, $(addsuffix /$(file),$(addprefix $(VBoxManage_0_OUTDIR)/,$(VRA_APPROVED_VRAMANAGE_DOCBOOK_LANGUAGES))))

 # Preprocess the xml files, applying remarks.
 $(foreach lang, $(VRA_APPROVED_VRAMANAGE_DOCBOOK_LANGUAGES) \
 , $(foreach file,$(filter man_VBoxManage-%,$(VRA_MANUAL_XML_REFENTRY_FILES)) \
   , $(evalcall2 def_vbox_refentry_preprocess_for_manpage,$(VBoxManage_0_OUTDIR)/$(lang),$(file) \
       ,$(VRA_PATH_MANUAL_SRC)/$(lang)/$(file),replace-xrefs \
       ,$(if $(filter $(lang),$(VRA_MANUAL_LANGUAGES)),$(lang),en_US))))

 # Generate the .cpp file.
 $(foreach lang, $(VRA_APPROVED_VRAMANAGE_DOCBOOK_LANGUAGES) \
 , $(evalcall2 def_vbox_man_generate_cpp_help,$(VBoxManage_0_OUTDIR)/$(lang),$(lang)))

 # Ensure $(lang) subfolder in the $(VRA_PATH_MANUAL_OUTBASE) is created (for section names file)
 BLDDIRS += $(addprefix $(VRA_PATH_MANUAL_OUTBASE)/,$(VRA_APPROVED_VRAMANAGE_DOCBOOK_LANGUAGES))

 # Generate sections names file for $(lang)
 $(foreach lang, $(VRA_APPROVED_VRAMANAGE_DOCBOOK_LANGUAGES) \
 , $(evalcall2 def_vbox_xref_to_text,$(lang)))

endif

include $(FILE_KBUILD_SUB_FOOTER)
