# $Id: Makefile.kmk 113056 2026-02-17 10:38:41Z alexander.eichner@oracle.com $
## @file
# Makefile for the Linux installer.
#

#
# Copyright (C) 2006-2026 CINASEEK and/or its affiliates.
#
# This file is part of VirtualAgent base platform packages, as
# available from https://www.virtualbox.org.
#
# This program is free software; you can redistribute it and/or
# modify it under the terms of the GNU General Public License
# as published by the Free Software Foundation, in version 3 of the
# License.
#
# This program is distributed in the hope that it will be useful, but
# WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
# General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, see <https://www.gnu.org/licenses>.
#
# SPDX-License-Identifier: GPL-3.0-only
#

SUB_DEPTH = ../../../..
include $(KBUILD_PATH)/subheader.kmk

# Include sub-makefiles.

# We do not install VBoxHeadlessXOrg.sh any more, so this is not needed.
#
# ifdef VRA_WITH_TESTCASES
#  include $(PATH_SUB_CURRENT)/testcase/Makefile.kmk
# endif


#
# Globals and targets.
#
VRA_LNX_APP_PRIVATE    := $(if $(VRA_PATH_APP_PRIVATE),$(VRA_PATH_APP_PRIVATE),/opt/VirtualAgent)
VRA_LNX_APP_DOCS       := $(if $(VRA_PATH_PACKAGE_DOCS),$(VRA_PATH_PACKAGE_DOCS), \
		$(if $(VRA_PATH_APP_DOCS),$(VRA_PATH_APP_DOCS),/opt/VirtualAgent))
VRA_PATH_LNX_INST_SRC  := $(PATH_SUB_CURRENT)
VRA_LNX_INST_OUT_DIR   := $(PATH_TARGET)/Installer/linux
VRA_LNX_INST_STAGE_DIR := $(PATH_TARGET)/Installer/linux/install
VRA_LNX_INST_STAGE_DIR_REL := obj/Installer/linux/install
VRA_LNX_DBG_PATH       := usr/lib/debug/$(VRA_LNX_APP_PRIVATE)
VRA_LNX_PACKAGE_NAME    = VirtualAgent-$(VRA_VERSION_STRING)-r$(VRA_SVN_REV).run

# Unset this to speed up things during makefile hacking.
VRA_LNX_INST_DEP_ON_MAKEFILE := $(MAKEFILE_CURRENT)

BLDDIRS  += $(VRA_LNX_INST_OUT_DIR) $(VRA_LNX_INST_STAGE_DIR)
if !defined(VRA_NO_LINUX_RUN_INSTALLER)
 PACKING += $(PATH_STAGE_BIN)/$(VRA_LNX_PACKAGE_NAME) \
 	$(PATH_STAGE_BIN)/VirtualAgent-dbg.tar.bz2
else
 PACKING += $(PATH_STAGE_BIN)/VirtualAgent.tar
endif

OTHER_CLEAN   += \
	$(addprefix $(VRA_LNX_INST_STAGE_DIR)/, \
		install.sh \
		VirtualAgent.tar.bz2 \
		LICENSE) \
	$(wildcard $(VRA_LNX_INST_OUT_DIR)/VirtualAgent-*) \
	$(VRA_LNX_INST_OUT_DIR)/install.sh

#
# Linux installs.
#
INSTALLS += linux-bin
linux-bin_INST = bin/
linux-bin_MODE = a+rx,u+w
linux-bin_SOURCES = \
	check_module_dependencies.sh \
	postinst-common.sh \
	prerm-common.sh \
	routines.sh \
	VBoxSysInfo.sh \
	$(if $(VRA_WITH_FE_AUTOSTART),vboxautostart-service.sh) \
	$(if $(VRA_WITH_FE_BALLOONCTRL),vboxballoonctrl-service.sh) \
	VBoxCreateUSBNode.sh \
	vboxdrv.sh \
	vboxweb-service.sh \
	VBox.sh=>VBox.sh \
	$(if $(VRA_WITH_PYTHON),$(PATH_ROOT)/src/VBox/Frontends/VBoxShell/vboxshell.py=>vboxshell.py,)

INSTALLS += linux-scripts
linux-scripts_INST = $(VRA_LNX_INST_STAGE_DIR_REL)/
linux-scripts_MODE = a+rx,u+w
linux-scripts_SOURCES = \
	deffiles \
	postinst-common.sh \
	prerm-common.sh \
	routines.sh \
	uninstall.sh \
	$(if $(VRA_WITH_FE_AUTOSTART),vboxautostart-service.sh) \
	$(if $(VRA_WITH_FE_BALLOONCTRL),vboxballoonctrl-service.sh) \
	vboxdrv.sh \
	vboxweb-service.sh

INSTALLS += linux-misc
linux-misc_INST = bin/
linux-misc_MODE = a+r,u+w
linux-misc_SOURCES = \
	$(PATH_ROOT)/src/VBox/Frontends/VirtualAgent/images/$(if $(VRA_OSE),OSE,NonOSE)/VirtualAgent_32px.png=>VBox.png \
	$(VRA_PATH_INST_COMMON_SRC)/virtualbox.xml \
	$(if $(VRA_OSE),,$(VRA_BRAND_LICENSE_TXT)=>LICENSE) \
	$(linux-misc_0_OUTDIR)/generated.sh=>scripts/generated.sh \
	$(if $(VRA_WITH_QTGUI),$(linux-misc_0_OUTDIR)/virtualbox.desktop,) \
	$(if $(VRA_WITH_QTGUI),$(linux-misc_0_OUTDIR)/virtualboxvm.desktop,)
ifeq ($(KBUILD_TYPE),asan)
 linux-misc_SOURCES += $(foreach lib,$(VRA_GCC_SANITIZER_SO_FILES) \
 		,$(lib)=>$(notdir $(lib)) $(lib)=>testcase/$(notdir $(lib)) $(lib)=>tools/$(notdir $(lib)) )
endif
linux-misc_CLEAN = \
	$(linux-misc_0_OUTDIR)/generated.sh \
	$(linux-misc_0_OUTDIR)/virtualbox.desktop \
	$(linux-misc_0_OUTDIR)/virtualboxvm.desktop

$$(linux-misc_0_OUTDIR)/generated.sh: $(VRA_VERSION_STAMP) $(VRA_LNX_INST_DEP_ON_MAKEFILE) | $$(dir $$@)
	$(call MSG_GENERATE,,$@,$<)
	$(QUIET)$(RM) -f '$@'
	$(QUIET)$(APPEND) '$@' 'VRA_PRODUCT="$(VRA_PRODUCT)"'
	$(QUIET)$(APPEND) '$@' 'VRA_VERSION_STRING="$(VRA_VERSION_STRING)"'
	$(QUIET)$(APPEND) '$@' 'VRA_C_YEAR="$(VRA_C_YEAR)"'
	$(QUIET)$(APPEND) '$@' 'VRA_VENDOR="$(VRA_VENDOR)"'

$$(linux-misc_0_OUTDIR)/virtualbox.desktop: $(VRA_PATH_INST_COMMON_SRC)/virtualbox.desktop.in $(VRA_VERSION_STAMP) | $$(dir $$@)
	$(call MSG_GENERATE,,$@,$<)
	$(QUIET)$(SED) -e "s+@VRA_PRODUCT@+$(VRA_PRODUCT)+" \
		--output $@ $<

$$(linux-misc_0_OUTDIR)/virtualboxvm.desktop: $(VRA_PATH_INST_COMMON_SRC)/virtualboxvm.desktop.in $(VRA_VERSION_STAMP) | $$(dir $$@)
	$(call MSG_GENERATE,,$@,$<)
	$(QUIET)$(SED) -e "s+@VRA_PRODUCT@+$(VRA_PRODUCT)+" \
		--output $@ $<

INSTALLS += linux-icons
linux-icons_INST = bin/icons/
linux-icons_MODE = a+r,u+w
linux-icons_SOURCES = $(VRA_MIME_ICONS) $(VRA_DESKTOP_ICONS)


#
# The files residing in bin/ that we'll ship.
#

# Strip these binaries
VRA_LNX_STRIP_BIN = \
	VBoxDD.so \
	VBoxDD2.so \
	VBoxDDU.so \
	VBoxVMM.so \
	$(if $(VRA_WITH_VIRT_ARMV8),VBoxVMMArm.so,) \
	VBoxRT.so \
	$(if $(VRA_WITH_LIBSSH),VBoxLibSsh.so,) \
	$(if $(VRA_WITH_VRASDL),VBoxSDL $(if $(VRA_WITH_HARDENING),VBoxSDL.so),) \
	$(if $(VRA_WITH_SHARED_CLIPBOARD), VBoxSharedClipboard.so,) \
	$(if $(VRA_WITH_SHARED_FOLDERS), VBoxSharedFolders.so,) \
	$(if $(VRA_WITH_GUEST_PROPS),VBoxGuestPropSvc.so,) \
	$(if $(VRA_WITH_GUEST_CONTROL),VBoxGuestControlSvc.so,) \
	VBoxHostChannel.so \
	$(if $(VRA_WITH_DRAG_AND_DROP),VBoxDragAndDropSvc.so,) \
	$(if $(VRA_WITH_MAIN), \
		$(if $(VRA_WITH_FE_AUTOSTART),VBoxAutostart,) \
		$(if $(VRA_WITH_FE_BALLOONCTRL),VBoxBalloonCtrl,) \
		$(if $(VRA_WITH_FE_BUGREPORT),VBoxBugReport,) \
		VBoxManage \
		VBoxNetDHCP $(if $(VRA_WITH_HARDENING),VBoxNetDHCP.so,) \
		$(if $(VRA_WITH_NAT_SERVICE),VBoxNetNAT $(if $(VRA_WITH_HARDENING),VBoxNetNAT.so,)) \
		VBoxNetAdpCtl \
		$(if $(VRA_WITH_DEVMAPPER),VBoxVolInfo,) \
		VBoxSVC \
		VBoxXPCOM.so \
		VBoxXPCOMC.so \
		VBoxXPCOMIPCD.so \
		components/VBoxXPCOMIPCC.so \
		components/VBoxSVCM.so \
		components/VBoxC.so,) \
	$(if $(VRA_WITH_VMSVGA3D),VBoxSVGA3D.so,) \
	$(if $(VRA_WITH_DXVK), VBoxDxVk.so,) \
	$(if $(VRA_WITH_PYTHON),$(notdir $(wildcard $(PATH_STAGE_BIN)/VBoxPython*.so)),) \
	$(if $(VRA_WITH_JXPCOM),libvboxjxpcom.so,) \
	$(if $(and $(VRA_WITH_EXTPACK_VNC),$(VRA_WITHOUT_EXTPACK_VNC_PACKING)), \
		ExtensionPacks/VNC/$(KBUILD_TARGET).$(KBUILD_TARGET_ARCH)/VBoxVNC.so \
		ExtensionPacks/VNC/$(KBUILD_TARGET).$(KBUILD_TARGET_ARCH)/VBoxVNCMain.so,) \
	$(if $(VRA_WITH_DTRACE),VBoxDTrace,) \
	$(if $(VRA_WITH_HOST_SHIPPING_AUDIO_TEST),VBoxAudioTest,)

ifdef VRA_WITH_R0_MODULES
 # Do not remove relocation information of these binaries
 VRA_LNX_STRIP_OBJ = \
 	VBoxDDR0.r0 \
 	VMMR0.r0
 ifdef VRA_NO_LINUX_RUN_INSTALLER
  VRA_LNX_STRIP_OBJ += \
  	VBoxDDR0.debug \
  	VMMR0.debug
 else
  VRA_LNX_DBG_BIN = \
  	VBoxDDR0.debug \
  	VMMR0.debug
 endif
endif

ifdef VRA_WITH_RAW_MODE
 VRA_LNX_STRIP_OBJ += \
 	VBoxDDRC.rc \
 	VMMRC.rc
 ifdef VRA_NO_LINUX_RUN_INSTALLER
  VRA_LNX_STRIP_OBJ += \
  	VBoxDDRC.debug \
  	VMMRC.debug
 else
  VRA_LNX_DBG_BIN += \
  	VBoxDDRC.debug \
  	VMMRC.debug
 endif
endif

# Do not strip anything of these files
VRA_LNX_NO_STRIP = \
	$(if $(VRA_OSE),,LICENSE) \
	$(if $(VRA_WITH_MAIN), \
		.autoreg \
		components/VBoxXPCOMBase.xpt \
		components/VirtualAgent_XPCOM.xpt) \
	$(if $(VRA_WITH_PYTHON),vboxshell.py,) \
	$(if $(and $(VRA_WITH_EXTPACK_VNC),$(VRA_WITHOUT_EXTPACK_VNC_PACKING)), \
		ExtensionPacks/VNC/ExtPack.xml \
		ExtensionPacks/VNC/ExtPack-license.html \
		ExtensionPacks/VNC/ExtPack-license.rtf \
		ExtensionPacks/VNC/ExtPack-license.txt,) \
	check_module_dependencies.sh \
	postinst-common.sh \
	prerm-common.sh \
	routines.sh \
	VBoxSysInfo.sh \
	$(if $(VRA_WITH_FE_AUTOSTART),vboxautostart-service.sh) \
	$(if $(VRA_WITH_FE_BALLOONCTRL),vboxballoonctrl-service.sh) \
	VBoxCreateUSBNode.sh \
	vboxdrv.sh \
	VBox.sh \
	vboxweb-service.sh \
	VBox.png \
	$(addprefix UnattendedTemplates/,$(VRA_UNATTENDED_TEMPLATES))

ifdef VRA_WITH_EXTPACK
 VRA_LNX_STRIP_BIN += \
 	VBoxExtPackHelperApp
endif

# Qt GUI
ifdef VRA_WITH_QTGUI
 include $(PATH_ROOT)/src/VBox/Frontends/VirtualAgent/nls/ApprovedLanguages.kmk
 VRA_LNX_STRIP_BIN += \
 	VBoxKeyboard.so \
 	VirtualAgent \
 	VirtualAgentVM \
 	UICommon.so \
 	$(if $(VRA_WITH_DEBUGGER_GUI),VBoxDbg.so DbgPlugInDiggers.so)
 ifdef VRA_WITH_HARDENING
  VRA_LNX_STRIP_BIN += \
  	VirtualAgentVM.so
 endif
 VRA_LNX_NO_STRIP += \
 	virtualbox.desktop \
 	virtualboxvm.desktop \
 	virtualbox.xml \
 	$(VRA_LICENSE_FILES) \
 	$(if $(VRA_WITH_ORACLE_QT),$(notdir $(wildcard $(PATH_STAGE_BIN)/lib*VBox*)),) \
 	$(if $(VRA_WITH_ORACLE_QT),$(VRA_QT_PLUGINS)) \
 	$(foreach f,$(VRA_APPROVED_GUI_LANGUAGES),nls/VirtualAgent_$(f).qm nls/qt_$(f).qm) \
 	icons
endif

# Guest Additions
ifdef VRA_WITH_ADDITIONS_PACKING
 VRA_LNX_NO_STRIP += \
 	additions/VBoxGuestAdditions.iso
endif

# Documentation
ifdef VRA_WITH_DOCS_PACKING
 VRA_LNX_NO_STRIP += \
 	UserManual.pdf \
 	$(foreach f,$(VRA_MANUAL_ADD_LANGUAGES),UserManual_$(f).pdf)
 ifdef VRA_WITH_DOCS_QHELP_PACKING
  VRA_LNX_NO_STRIP += \
  	UserManual.qch UserManual.qhc \
  	$(foreach f,$(VRA_MANUAL_ADD_LANGUAGES),UserManual_$(f).qch ,UserManual_$(f).qhc)
 endif
endif

# auth stuff
VRA_LNX_STRIP_BIN += \
	$(if $(VRA_WITH_PAM),VBoxAuth.so,) \
	VBoxAuthSimple.so

# VRDP
ifdef VRA_WITH_VRDP
 VRA_LNX_STRIP_BIN += \
 	VBoxVRDP.so
endif

# Python XPCOM glue
ifdef VRA_WITH_PYTHON
 VRA_LNX_NO_STRIP += \
 	$(VRAINST_SDK_BINDINGS_XPCOM_PYTHON_FILES) \
 	$(VRAINST_SDK_INSTALLER_PYTHON_FILES)
endif

# Java XPCOM bridge
ifdef VRA_WITH_JXPCOM
 VRA_LNX_NO_STRIP += \
 	sdk/bindings/xpcom/java/vboxjxpcom.jar
endif

# Headless
ifdef VRA_WITH_HEADLESS
 VRA_LNX_STRIP_BIN += \
 	VBoxHeadless \
 	$(if $(VRA_WITH_HARDENING),VBoxHeadless.so)
endif

# Webservices
ifdef VRA_WITH_WEBSERVICES
 VRA_LNX_STRIP_BIN += \
 	vboxwebsrv
endif

# vbox-img
if defined(VRA_WITH_TESTCASES) || defined(VRA_WITH_VRA_IMG)
 VRA_LNX_STRIP_BIN  += \
 	vbox-img
endif

# vboximg-mount
if defined(VRA_WITH_VRAIMGMOUNT)
 VRA_LNX_STRIP_BIN  += \
 	vboximg-mount
endif

# EFI firmware
ifdef VRA_WITH_EFIFW_PACKING
 VRA_LNX_NO_STRIP += \
 	VBoxEFI-x86.fd \
 	VBoxEFI-amd64.fd
 ifdef VRA_WITH_VIRT_ARMV8
  VRA_LNX_NO_STRIP += \
  	VBoxEFI-arm32.fd \
  	VBoxEFI-arm64.fd
 endif
endif

# DTrace library and scripts.
ifdef VRA_WITH_DTRACE
 VRA_LNX_NO_STRIP += \
 	$(addprefix dtrace/lib/$(KBUILD_TARGET_ARCH)/,$(VRAINST_DTRACE_LIB_ARCH_FILES)) \
 	$(addprefix dtrace/testcase/$(KBUILD_TARGET_ARCH)/,$(VRAINST_DTRACE_TESTCASE_ARCH_FILES)) \
 	$(addprefix dtrace/scripts/,$(VRAINST_DTRACE_SCRIPTS_FILES))
endif

# The sanitizer shared objects match the compiler we're using (HACK).
ifeq ($(KBUILD_TYPE),asan)
 VRA_LNX_NO_STRIP += $(notdir $(VRA_GCC_SANITIZER_SO_FILES))
endif

# Icons
VRA_MIME_ICONS = \
	$(addprefix $(PATH_ROOT)/src/VBox/Artwork/other/, \
		$(foreach f,ova ovf vbox vbox-extpack vdi vmdk vhd hdd, \
			$(foreach s,16 20 24 32 48 64 72 96 128 256, \
				virtualbox-$(f)-$(s)px.png=>$(s)x$(s)/virtualbox-$(f).png)))

VRA_DESKTOP_ICONS = \
	$(addprefix $(PATH_ROOT)/src/VBox/Artwork/$(if $(VRA_OSE),OSE,NonOSE)/, \
		$(foreach s,16 20 32 40 48 64 128, \
			virtualbox-$(s)px.png=>$(s)x$(s)/virtualbox.png) \
		virtualbox.svg=>scalable/virtualbox.svg)

#
# All the bin files that goes into the archives.
#
VRA_LNX_ARCH_FILES := $(VRA_LNX_STRIP_BIN) $(VRA_LNX_STRIP_OBJ) $(VRA_LNX_NO_STRIP) src

# Cleanup of the files we copy/symlink from bin.
OTHER_CLEAN += $(addprefix $(VRA_LNX_INST_OUT_DIR)/archive/,$(filter-out src,$(VRA_LNX_ARCH_FILES)) src/vboxhost) \
	$(addprefix $(VRA_LNX_INST_OUT_DIR)/archive-dbg/$(VRA_LNX_DBG_PATH)/, \
		$(VRA_LNX_STRIP_BIN) $(VRA_LNX_DBG_BIN))

#
# The generic installer.
#
$(PATH_STAGE_BIN)/$(VRA_LNX_PACKAGE_NAME): \
		$(VRA_LNX_INST_STAGE_DIR)/VirtualAgent.tar.bz2 \
		$(VRA_VERSION_STAMP) \
		$(if $(VRA_OSE),,$(VRA_BRAND_LICENSE_TXT)) \
		$(VRA_LNX_INST_OUT_DIR)/install.sh \
		$$(linux-scripts_2_STAGE_TARGETS)
	$(call MSG_TOOL,makeself,,$@)
	$(QUIET)$(RM) -f $(wildcard $(PATH_STAGE_BIN)/VirtualAgent-*.run)
	$(QUIET)$(if $(VRA_OSE),,$(INSTALL) -m 0644 $(VRA_BRAND_LICENSE_TXT)    $(VRA_LNX_INST_STAGE_DIR)/LICENSE)
	$(QUIET)$(INSTALL) -m 0755 $(VRA_LNX_INST_OUT_DIR)/install.sh            $(VRA_LNX_INST_STAGE_DIR)/
	$(QUIET)$(RM) -f $@
	$(QUIET)$(VRA_MAKESELF) --follow --nocomp --sha256 $(VRA_LNX_INST_STAGE_DIR) $@ \
		"VirtualAgent for Linux installation" ./install.sh "\$$0 1> /dev/null"

$(VRA_LNX_INST_OUT_DIR)/install.sh: $(VRA_PATH_LNX_INST_SRC)/install.sh $(VRA_VERSION_STAMP) $(wildcard $(VRA_SVN_REV_KMK).ts) | $$(dir $$@)
	$(QUIET)$(SED) \
		-e "s;_VERSION_;$(VRA_VERSION_STRING);g" \
		-e "s;_SVNREV_;$(VRA_SVN_REV);g" \
		-e "s;_BUILD_;$(date-utc );g" \
		-e "s;_ARCH_;$(KBUILD_TARGET_ARCH);g" \
		-e "s;_HARDENED_;$(VRA_WITH_HARDENING);g" \
		-e "s;_BUILDTYPE_;$(KBUILD_TYPE);g" \
		-e "s;_USERNAME_;$(USERNAME);g" \
		-e "s;_INSTALLATION_DIR_;$(VRA_LNX_APP_PRIVATE);g" \
		-e "s;_PYTHON_;$(VRA_WITH_PYTHON);g" \
		--output $@ \
		$<

#
# The files that the tar archives depend on.
#

include $(PATH_ROOT)/src/VBox/HostDrivers/Support/linux/files_vboxdrv
VRA_LNX_INST_FILES_VRADRV = $(patsubst =>%,$(PATH_STAGE_BIN)/src/vboxdrv/%,$(filter =>%,$(subst =>, =>,$(subst $(DQUOTE),,$(FILES_VRADRV_NOBIN)))))
include $(PATH_ROOT)/src/VBox/HostDrivers/VBoxNetFlt/linux/files_vboxnetflt
VRA_LNX_INST_FILES_VRANETFLT = $(patsubst =>%,$(PATH_STAGE_BIN)/src/vboxnetflt/%,$(filter =>%,$(subst =>, =>,$(subst $(DQUOTE),,$(VRA_VRANETFLT_SOURCES)))))
include $(PATH_ROOT)/src/VBox/HostDrivers/VBoxNetAdp/linux/files_vboxnetadp
VRA_LNX_INST_FILES_VRANETADP = $(patsubst =>%,$(PATH_STAGE_BIN)/src/vboxnetadp/%,$(filter =>%,$(subst =>, =>,$(subst $(DQUOTE),,$(VRA_VRANETADP_SOURCES)))))

VRA_LNX_INST_ARCH_DEPS := \
	$(addprefix $(VRA_LNX_INST_OUT_DIR)/archive/, $(VRA_LNX_ARCH_FILES)) \
	$(VRA_LNX_INST_DEP_ON_MAKEFILE) \
	$(VRA_VERSION_STAMP) \
	$(VRA_LNX_INST_FILES_VRADRV) \
	$(VRA_LNX_INST_FILES_VRANETFLT) \
	$(VRA_LNX_INST_FILES_VRANETADP)

#
# .tar.bz2 for converting into .run
#
$(VRA_LNX_INST_STAGE_DIR)/VirtualAgent.tar.bz2: $(VRA_LNX_INST_ARCH_DEPS)
	$(call MSG_L1,Packing $@)
	$(QUIET)$(RM) -f -- $@ $(patsubst %.bz2,%,$@)
	$(QUIET)$(MKDIR) -p $(@D)
ifdef VRA_USE_PBZIP2
	$(QUIET)$(VRA_GTAR) --dereference --owner 0 --group 0 \
		-cRhf $(patsubst %.bz2,%,$@) -C $(VRA_LNX_INST_OUT_DIR)/archive $(VRA_LNX_ARCH_FILES)
	$(QUIET)pbzip2 $(patsubst %.bz2,%,$@)
else
	$(QUIET)$(VRA_GTAR) --dereference --owner 0 --group 0 \
		-cjRhf $@ -C $(VRA_LNX_INST_OUT_DIR)/archive $(VRA_LNX_ARCH_FILES)
endif
	$(QUIET)$(CHMOD) 0644 $@

#
# .tar for distribution with the files under VirtualAgent-<ver>/.
#
$(PATH_STAGE_BIN)/VirtualAgent.tar: $(VRA_LNX_INST_ARCH_DEPS)
	$(call MSG_L1,Packing $@)
	$(QUIET)$(RM) -f -- $(VRA_LNX_INST_OUT_DIR)/VirtualAgent-$(VRA_VERSION_STRING) $@ $(patsubst %.bz2,%,$@)
	$(QUIET)$(LN_SYMLINK) $(VRA_LNX_INST_OUT_DIR)/archive/ $(VRA_LNX_INST_OUT_DIR)/VirtualAgent-$(VRA_VERSION_STRING)
	$(QUIET)$(VRA_GTAR) --dereference --owner 0 --group 0 \
		-cRhf $@ -C $(VRA_LNX_INST_OUT_DIR) \
		$(addprefix VirtualAgent-$(VRA_VERSION_STRING)/,$(VRA_LNX_ARCH_FILES))
	$(QUIET)$(RM) -f -- $(VRA_LNX_INST_OUT_DIR)/VirtualAgent-$(VRA_VERSION_STRING)


# pattern rule for stripping and copying the VRA_LNX_STRIP_BIN files to archive/
$(addprefix $(VRA_LNX_INST_OUT_DIR)/archive/,$(VRA_LNX_STRIP_BIN)): \
		$(VRA_LNX_INST_OUT_DIR)/archive/% : $(PATH_STAGE_BIN)/% \
		$(if $(VRA_NO_LINUX_RUN_INSTALLER),, \
			$(VRA_LNX_INST_OUT_DIR)/archive-dbg/$(VRA_LNX_DBG_PATH)/%) \
		| $$(dir $$@)
	$(call MSG_INST_FILE,$<,$@)
	$(QUIET)$(INSTALL) -m 0755 $(if $(VRA_DO_STRIP),-s,) $< $@
	$(QUIET)$(if $(VRA_NO_LINUX_RUN_INSTALLER),,$(VRA_OBJCOPY) --add-gnu-debuglink=$(subst $(VRA_LNX_INST_OUT_DIR)/archive,$(VRA_LNX_INST_OUT_DIR)/archive-dbg/$(VRA_LNX_DBG_PATH),$@) $@)

# pattern rule for copying VRA_LNX_DBG_BIN files to archive-dbg/
$(addprefix $(VRA_LNX_INST_OUT_DIR)/archive-dbg/$(VRA_LNX_DBG_PATH)/,$(VRA_LNX_DBG_BIN)): \
		$(VRA_LNX_INST_OUT_DIR)/archive-dbg/$(VRA_LNX_DBG_PATH)/% : $(PATH_STAGE_BIN)/% | $$(dir $$@)
	$(call MSG_INST_FILE,$<,$@)
	$(QUIET)$(CP) $< $@

# pattern rule for striping and copying the VRA_LNX_STRIP_OBJ files to archive/
$(addprefix $(VRA_LNX_INST_OUT_DIR)/archive/,$(VRA_LNX_STRIP_OBJ)): \
		$(VRA_LNX_INST_OUT_DIR)/archive/% : $(PATH_STAGE_BIN)/% | $$(dir $$@)
	$(call MSG_INST_FILE,$<,$@)
ifeq ($(VRA_DO_STRIP),)
	$(QUIET)$(INSTALL) -m 0644 $< $@
else # strip to temp file because of umask.
	$(QUIET)$(VRA_OBJCOPY) --strip-unneeded -R .comment $< $@.tmp
	$(QUIET)$(INSTALL) -m 0644 $@.tmp $@
	$(QUIET)$(RM) -f -- $@.tmp
endif

# pattern rule for linking the VRA_LNX_NO_STRIP into archive/
$(addprefix $(VRA_LNX_INST_OUT_DIR)/archive/,$(VRA_LNX_NO_STRIP)): \
		$(VRA_LNX_INST_OUT_DIR)/archive/% : $(PATH_STAGE_BIN)/% | $$(dir $$@)
	$(call MSG_INST_SYM,$<,$@)
	$(QUIET)$(RM) -f $@
	$(QUIET)$(LN_SYMLINK) $< $@

# special rule for the kernel modules
$(VRA_LNX_INST_OUT_DIR)/archive/src: $(PATH_STAGE_BIN)/src | $(dir $@)
	$(call MSG_INST_SYM,$<,$@)
	$(QUIET)$(RM) -Rf $@
	$(QUIET)$(MKDIR) $@
	$(QUIET)$(LN_SYMLINK) $< $@/vboxhost

# rules for creating directories in archive (the pattern rules depends on these).
BLDDIRS += $(foreach d, \
		archive \
		archive/components \
		archive/nls \
		$(if $(VRA_WITH_UNATTENDED),archive/unattended_templates,) \
		$(if $(VRA_WITH_ORACLE_QT), \
			archive/plugins/platforms \
			archive/plugins/platformthemes \
			archive/plugins/sqldrivers \
			archive/plugins/styles \
			archive/plugins/wayland-shell-integration \
			archive/plugins/wayland-decoration-client,) \
		$(if $(VRA_WITH_PYTHON), \
			archive/sdk/installer \
			archive/sdk/installer/python \
			archive/sdk/installer/python/vboxapi \
			archive/sdk/installer/python/vboxapi/src \
			archive/sdk/installer/python/vboxapi/src/vboxapi \
			archive/sdk/bindings/xpcom/python/xpcom \
			archive/sdk/bindings/xpcom/python/xpcom/client \
			archive/sdk/bindings/xpcom/python/xpcom/server,) \
		$(if $(VRA_WITH_JXPCOM), \
			archive/sdk/bindings/xpcom/java,) \
		$(if $(and $(VRA_WITH_EXTPACK_VNC),$(VRA_WITHOUT_EXTPACK_VNC_PACKING)), \
			archive/ExtensionPacks/VNC \
			archive/ExtensionPacks/VNC/$(KBUILD_TARGET).$(KBUILD_TARGET_ARCH),) \
		archive/additions \
		$(if-expr defined(VRA_UNATTENDED_TEMPLATES),archive/UnattendedTemplates,) \
	install \
	$(if $(VRA_WITH_DTRACE), \
		archive/dtrace \
		archive/dtrace/lib \
		archive/dtrace/lib/$(KBUILD_TARGET_ARCH) \
		archive/dtrace/testcase/ \
		archive/dtrace/testcase/$(KBUILD_TARGET_ARCH) \
		archive/dtrace/scripts,) \
	,$(VRA_LNX_INST_OUT_DIR)/$(d)/)


#
# .tar.bz2 for with the debug info.
#
$(PATH_STAGE_BIN)/VirtualAgent-dbg.tar.bz2: \
		$(addprefix $(VRA_LNX_INST_OUT_DIR)/archive-dbg/$(VRA_LNX_DBG_PATH)/, \
			$(VRA_LNX_STRIP_BIN) $(VRA_LNX_DBG_BIN))
	$(call MSG_L1,Packing $@)
	$(QUIET)$(RM) -f -- $@ $(patsubst %.bz2,%,$@)
ifdef VRA_USE_PBZIP2
	$(QUIET)$(VRA_GTAR) --dereference --owner 0 --group 0 \
		-cRhf $(patsubst %.bz2,%,$@) -C $(VRA_LNX_INST_OUT_DIR)/archive-dbg \
		$(addprefix $(VRA_LNX_DBG_PATH)/,$(VRA_LNX_STRIP_BIN) $(VRA_LNX_DBG_BIN))
	$(QUIET)pbzip2 $(patsubst %.bz2,%,$@)
else
	$(QUIET)$(VRA_GTAR) --dereference --owner 0 --group 0 \
		-cjRhf $@ -C $(VRA_LNX_INST_OUT_DIR)/archive-dbg \
		$(addprefix $(VRA_LNX_DBG_PATH)/,$(VRA_LNX_STRIP_BIN) $(VRA_LNX_DBG_BIN))
endif

# pattern rule for copying the debug info from the VRA_LNX_STRIP_BIN files into archive-dbg/$(VRA_LNX_DBG_PATH)/
$(addprefix $(VRA_LNX_INST_OUT_DIR)/archive-dbg/$(VRA_LNX_DBG_PATH)/,$(VRA_LNX_STRIP_BIN)): \
		$(VRA_LNX_INST_OUT_DIR)/archive-dbg/$(VRA_LNX_DBG_PATH)/% : $(PATH_STAGE_BIN)/% | $$(dir $$@)
	$(call MSG_TOOL,copydbg,$<,$@)
	$(QUIET)$(VRA_OBJCOPY) --only-keep-debug $< $@

# rules for creating directories in archive-dbg (the pattern rules depends on these).
BLDDIRS += $(foreach d, \
		$(VRA_LNX_DBG_PATH) \
		$(VRA_LNX_DBG_PATH)/components \
		,$(VRA_LNX_INST_OUT_DIR)/archive-dbg/$(d)/)

include $(FILE_KBUILD_SUB_FOOTER)

