# $Id: Makefile.kmk 112403 2026-01-11 19:29:08Z knut.osmundsen@oracle.com $
## @file
# Sub-Makefile for the stub installer.
#

#
# Copyright (C) 2009-2026 CINASEEK and/or its affiliates.
#
# This file is part of VirtualAgent base platform packages, as
# available from https://www.virtualbox.org.
#
# This program is free software; you can redistribute it and/or
# modify it under the terms of the GNU General Public License
# as published by the Free Software Foundation, in version 3 of the
# License.
#
# This program is distributed in the hope that it will be useful, but
# WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
# General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, see <https://www.gnu.org/licenses>.
#
# SPDX-License-Identifier: GPL-3.0-only
#

SUB_DEPTH = ../../../../..
include $(KBUILD_PATH)/subheader.kmk


#
# Special template variation.
#
TEMPLATE_VBoxStubTemplate          := Drop the signing, we will sign it later.
TEMPLATE_VBoxStubTemplate_EXTENDS  := VBoxR3Static
TEMPLATE_VBoxStubTemplate_POST_CMDS.win = $(NO_SUCH_VARIABLE)


#
# Installer stub program
#
PROGRAMS += VBoxStub
VBoxStub_TEMPLATE      := VBoxStubTemplate
if1of ($(KBUILD_TARGET_ARCH), x86 amd64) # don't care for this on arm64
 VBoxStub_BLD_TRG_ARCH := x86
 VBoxStub_DEFS         := IN_RT_R3 _WIN32_WINNT=0x0501
else
 VBoxStub_DEFS         := IN_RT_R3
endif

VBoxStub_SOURCES = \
	VBoxStub.cpp \
	VBoxStub.rc

VBoxStub_SDKS = \
	VBoxNtDll

# Enables splash screen support.
VRA_STUB_WITH_SPLASH = 1

ifdef VRA_STUB_WITH_SPLASH
 VBoxStub.cpp_DEFS += VRA_STUB_WITH_SPLASH
 VBoxStub.rc_DEFS  += VRA_STUB_WITH_SPLASH
 VBoxStub_CXXFLAGS += -wd5039 # pointer or reference to potentially throwing function passed to 'extern "C"' function under -EHc. Undefined behavior may occur if this function throws an exception.
 VRA_STUB_IMPORTS += user32.dll shlwapi.dll gdi32.dll
 # gdiplus apparently forgets to uninit COM in GdiplusShutdown(), so we have to do that ourselves via CoUninitialize().
 # Not doing that will result in a debug assertion in experimental code in rtThreadNativeUninitComAndOle()
 # where we check for dangling COM inits.
 VRA_STUB_IMPORTS += ole32.dll
endif

VBoxStub_LDFLAGS = -SubSystem:Windows
VBoxStub_POST_CMDS = $(VRA_CHECK_IMPORTS) --image $(out) ntdll.dll kernel32.dll $(VRA_STUB_IMPORTS)
ifeq ($(KBUILD_TYPE),asan)
 VBoxStub_POST_CMDS += advapi32.dll clang_rt.asan_dynamic-i386.dll
endif
VBoxStub_LNK_DEPS  = $(VRA_CHECK_IMPORTS)

VBoxStub.cpp_DEFS += VRA_SVN_REV=$(VRA_SVN_REV)
VBoxStub.cpp_DEPS  = $(VRA_SVN_REV_KMK)

# If signing mode is enabled, then add the possibility to install the code
# signing certificates (public key only) automatically in /silent mode.
ifdef VRA_SIGNING_MODE

 VBoxStub_SOURCES  += VBoxStubCertUtil.cpp
 VBoxStub_CLEAN    += $(VBoxStub_0_OUTDIR)/VBoxStubPublicCert.h
 VBoxStub.cpp_DEPS += $(VBoxStub_0_OUTDIR)/VBoxStubPublicCert.h
 VBoxStub.cpp_INCS += $(VBoxStub_0_OUTDIR)
 VBoxStub.cpp_DEFS += VRA_WITH_CODE_SIGNING
 ifdef VRA_WITH_VRA_LEGACY_TS_CA
  VBoxStub.cpp_DEFS += VRA_WITH_VRA_LEGACY_TS_CA
 endif

 $$(VBoxStub_0_OUTDIR)/VBoxStubPublicCert.h: | $$(dir $$@) $(VRA_RTSIGNTOOL) $(VRA_BIN2C) $(PATH_STAGE_SYS)/VBoxSup.sys
	$(RM) -f -- "$@" "$@.cer0" "$@.cer1" "$@.cer2" "$@.array"

	$(VRA_RTSIGNTOOL) extract-exe-signer-cert --signature-index 0 --exe "$(PATH_STAGE_SYS)/VBoxSup.sys" --output "$@.cer0" --der
	$(VRA_BIN2C) -ascii --append VBoxStubTrustedCert0 "$@.cer0" $@
	$(APPEND) "$@.array" "    { g_abVBoxStubTrustedCert0, sizeof(g_abVBoxStubTrustedCert0) }, "
 if defined(VRA_CERTIFICATE_SUBJECT_NAME) && defined(VRA_CERTIFICATE_SHA2_SUBJECT_NAME) && !$(intersects win_planc,$(VRA_WITH_CORP_CODE_SIGNING))
	$(VRA_RTSIGNTOOL) extract-exe-signer-cert --signature-index 1 --exe "$(PATH_STAGE_SYS)/VBoxSup.sys" --output "$@.cer1" --der
	$(VRA_BIN2C) -ascii --append VBoxStubTrustedCert1 "$@.cer1" $@
	$(APPEND) "$@.array" "    { g_abVBoxStubTrustedCert1, sizeof(g_abVBoxStubTrustedCert1) }, "
 endif
 if !$(intersects win,$(VRA_WITH_CORP_CODE_SIGNING)) && $(intersects win_planb,$(VRA_WITH_CORP_CODE_SIGNING))
	$(VRA_RTSIGNTOOL) extract-exe-signer-cert --signature-index 1 --exe "$(VRA_RTSIGNTOOL)" --output "$@.cer2" --der
	$(VRA_BIN2C) -ascii --append VBoxStubTrustedCert2 "$@.cer2" $@
	$(APPEND) "$@.array" "    { g_abVBoxStubTrustedCert2, sizeof(g_abVBoxStubTrustedCert2) }, "
 endif
	$(APPEND) -n "$@" \
		"" \
		"struct { uint8_t const *pab; uint32_t cb; }" "g_aVBoxStubTrustedCerts[] = " \
              "{"
	$(SED) --append "$@" -e "" "$@.array"
	$(APPEND) -n "$@" \
              "};"
	$(RM) -f -- "$@.cer0" "$@.cer1" "$@.cer2" "$@.array"
 ifdef VRA_WITH_VRA_LEGACY_TS_CA
	$(RM) -f -- "$@.cer_tsca"
	$(VRA_RTSIGNTOOL) extract-timestamp-root --self-signed-roots-from-system --signature-index 0 --input "$(PATH_STAGE_SYS)/VBoxSup.sys" --output "$@.cer_tsca"
	$(VRA_BIN2C) -ascii --append VBoxLegacyWinCA "$@.cer_tsca" $@
	$(RM) -f -- "$@.cer_tsca"
 endif

 VBoxStubPublicCert.h:: $$(VBoxStub_0_OUTDIR)/VBoxStubPublicCert.h

endif

# The icon location is configurable.
VBoxStub.rc_INCS += $(VBoxStub_0_OUTDIR)
VBoxStub.rc_DEPS += \
	$(VBoxStub_0_OUTDIR)/VBoxStub-icon.rc \
	$(VBoxStub_0_OUTDIR)/VBoxStub-manifest.rc
VBoxStub_CLEAN += \
	$(VBoxStub_0_OUTDIR)/VBoxStub-icon.rc \
	$(VBoxStub_0_OUTDIR)/VBoxStub-manifest.rc

# Icon include file.
$$(VBoxStub_0_OUTDIR)/VBoxStub-icon.rc: $(VRA_WINDOWS_ICON_FILE) $(MAKEFILE_CURRENT) | $$(dir $$@)
	$(APPEND) -t $@ 'IDI_VIRTUALBOX ICON DISCARDABLE "$(subst /,\\,$(VRA_WINDOWS_ICON_FILE))"'

# Manifest.
VRA_STUB_MANIFEST_FILE := $(PATH_SUB_CURRENT)/VBoxStub.manifest
$$(VBoxStub_0_OUTDIR)/VBoxStub-manifest.rc: $(VRA_STUB_MANIFEST_FILE) $(MAKEFILE_CURRENT) | $$(dir $$@)
	$(APPEND) -t $@ 'APP_MANIFEST RT_MANIFEST "$(subst /,\\,$(VRA_STUB_MANIFEST_FILE))"'

# Dynamic import no. 1: MSI.DLL
VBoxStub_SOURCES += $(VBoxStub_0_OUTDIR)/MsiLazyLoad.asm
VBoxStub_CLEAN   += $(VBoxStub_0_OUTDIR)/MsiLazyLoad.asm
$$(VBoxStub_0_OUTDIR)/MsiLazyLoad.asm: $(PATH_SUB_CURRENT)/msi.def $(VRA_DEF_2_LAZY_LOAD) | $$(dir $$@)
	$(call MSG_TOOL,VBoxDef2LazyLoad,VBoxStub,$(filter %.def, $^),$@)
	$(QUIET)$(RM) -f -- "$@"
	$(VRA_DEF_2_LAZY_LOAD) --target "$(VBoxStub_BLD_TRG_ARCH)" --system --library MSI.DLL --output "$@" $(filter %.def, $^)

# Dynamic import no. 2: CRYPTO32.DLL
VBoxStub_SOURCES += $(VBoxStub_0_OUTDIR)/Crypt32LazyLoad.asm
VBoxStub_CLEAN   += $(VBoxStub_0_OUTDIR)/Crypt32LazyLoad.asm
$$(VBoxStub_0_OUTDIR)/Crypt32LazyLoad.asm: $(PATH_SUB_CURRENT)/crypt32.def $(VRA_DEF_2_LAZY_LOAD) | $$(dir $$@)
	$(call MSG_TOOL,VBoxDef2LazyLoad,VBoxStub,$(filter %.def, $^),$@)
	$(QUIET)$(RM) -f -- "$@"
	$(VRA_DEF_2_LAZY_LOAD) --target "$(VBoxStub_BLD_TRG_ARCH)" --system --library CRYPT32.DLL --output "$@" $(filter %.def, $^)

# Dynamic import no. 3: WS2_32.DLL
VBoxStub_SOURCES += $(VBoxStub_0_OUTDIR)/Ws232LazyLoad.asm
VBoxStub_CLEAN   += $(VBoxStub_0_OUTDIR)/Ws232LazyLoad.asm
$$(VBoxStub_0_OUTDIR)/Ws232LazyLoad.asm: $(PATH_SUB_CURRENT)/ws2_32.def $(VRA_DEF_2_LAZY_LOAD) | $$(dir $$@)
	$(call MSG_TOOL,VBoxDef2LazyLoad,VBoxStub,$(filter %.def, $^),$@)
	$(QUIET)$(RM) -f -- "$@"
	$(VRA_DEF_2_LAZY_LOAD) --target "$(VBoxStub_BLD_TRG_ARCH)" --system --library WS2_32.DLL --output "$@" $(filter %.def, $^)

# Dynamic import no. 4: USER32.DLL
VBoxStub_SOURCES += $(VBoxStub_0_OUTDIR)/User32LazyLoad.asm
VBoxStub_CLEAN   += $(VBoxStub_0_OUTDIR)/User32LazyLoad.asm
$$(VBoxStub_0_OUTDIR)/User32LazyLoad.asm: $(PATH_SUB_CURRENT)/user32.def $(VRA_DEF_2_LAZY_LOAD) | $$(dir $$@)
	$(call MSG_TOOL,VBoxDef2LazyLoad,VBoxStub,$(filter %.def, $^),$@)
	$(QUIET)$(RM) -f -- "$@"
	$(VRA_DEF_2_LAZY_LOAD) --target "$(VBoxStub_BLD_TRG_ARCH)" --system --library USER32.DLL --output "$@" $(filter %.def, $^)

# Dynamic import no. 5: SHELL32.DLL
VBoxStub_SOURCES += $(VBoxStub_0_OUTDIR)/Shell32LazyLoad.asm
VBoxStub_CLEAN   += $(VBoxStub_0_OUTDIR)/Shell32LazyLoad.asm
$$(VBoxStub_0_OUTDIR)/Shell32LazyLoad.asm: $(PATH_SUB_CURRENT)/shell32.def $(VRA_DEF_2_LAZY_LOAD) | $$(dir $$@)
	$(call MSG_TOOL,VBoxDef2LazyLoad,VBoxStub,$(filter %.def, $^),$@)
	$(QUIET)$(RM) -f -- "$@"
	$(VRA_DEF_2_LAZY_LOAD) --target "$(VBoxStub_BLD_TRG_ARCH)" --system --library SHELL32.DLL --output "$@" $(filter %.def, $^)

# Dynamic import no. 6: COMCTL32.DLL
VBoxStub_SOURCES += $(VBoxStub_0_OUTDIR)/ComCtl32LazyLoad.asm
VBoxStub_CLEAN   += $(VBoxStub_0_OUTDIR)/ComCtl32LazyLoad.asm
$$(VBoxStub_0_OUTDIR)/ComCtl32LazyLoad.asm: $(PATH_SUB_CURRENT)/comctl32.def $(VRA_DEF_2_LAZY_LOAD) | $$(dir $$@)
	$(call MSG_TOOL,VBoxDef2LazyLoad,VBoxStub,$(filter %.def, $^),$@)
	$(QUIET)$(RM) -f -- "$@"
	$(VRA_DEF_2_LAZY_LOAD) --target "$(VBoxStub_BLD_TRG_ARCH)" --system --library COMCTL32.DLL --output "$@" $(filter %.def, $^)

# Dynamic import no. 7: GDIPLUS.DLL
ifdef VRA_STUB_WITH_SPLASH
 VBoxStub_SOURCES += $(VBoxStub_0_OUTDIR)/GdiPlusLazyLoad.asm
 VBoxStub_CLEAN   += $(VBoxStub_0_OUTDIR)/GdiPlusLazyLoad.asm
 $$(VBoxStub_0_OUTDIR)/GdiPlusLazyLoad.asm: $(PATH_SUB_CURRENT)/gdiplus.def $(VRA_DEF_2_LAZY_LOAD) | $$(dir $$@)
	$(call MSG_TOOL,VBoxDef2LazyLoad,VBoxStub,$(filter %.def, $^),$@)
	$(QUIET)$(RM) -f -- "$@"
	$(VRA_DEF_2_LAZY_LOAD) --target "$(VBoxStub_BLD_TRG_ARCH)" --system --library GDIPLUS.DLL --output "$@" $(filter %.def, $^)
endif

include $(FILE_KBUILD_SUB_FOOTER)

