# $Id: Makefile.kmk 112403 2026-01-11 19:29:08Z knut.osmundsen@oracle.com $
## @file
# Makefile for the VBox debugger.
#

#
# Copyright (C) 2006-2026 CINASEEK and/or its affiliates.
#
# This file is part of VirtualAgent base platform packages, as
# available from https://www.virtualbox.org.
#
# This program is free software; you can redistribute it and/or
# modify it under the terms of the GNU General Public License
# as published by the Free Software Foundation, in version 3 of the
# License.
#
# This program is distributed in the hope that it will be useful, but
# WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
# General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, see <https://www.gnu.org/licenses>.
#
# SPDX-License-Identifier: GPL-3.0-only
#

SUB_DEPTH = ../../..
include $(KBUILD_PATH)/subheader.kmk

#
# The targets.
#
ifdef VRA_WITH_DEBUGGER
 LIBRARIES += Debugger
 ifdef VRA_WITH_TESTCASES
  PROGRAMS += tstDBGCParser
 endif
endif # VRA_WITH_DEBUGGER


#
# Debugger library - linked into VBoxVMM.
#
Debugger_TEMPLATE  = VBoxR3Dll
Debugger_DEFS      = IN_VMM_R3 IN_DBG_R3 IN_DIS VRA_WITH_DEBUGGER
ifneq ($(KBUILD_TYPE),release)
 Debugger_DEFS    += VRA_WITH_DEBUGGER_TCP_BY_DEFAULT
endif
Debugger_SOURCES   = \
	DBGConsole.cpp \
	DBGCEval.cpp \
	DBGCBuiltInSymbols.cpp \
	DBGCCmdHlp.cpp \
	DBGCCmdWorkers.cpp \
	DBGCCommands.cpp \
	DBGCDumpImage.cpp \
	DBGCNtCommands.cpp \
	DBGCFunctions.cpp \
	DBGCEmulateCodeView.cpp \
	DBGCOps.cpp \
	DBGCGdbRemoteStub.cpp \
	DBGCRemoteKd.cpp \
	DBGCIo.cpp \
	DBGCIoProvTcp.cpp \
	DBGCIoProvUdp.cpp \
	DBGCIoProvIpc.cpp \
	DBGCScreenAscii.cpp

ifdef VRA_WITH_VIRT_ARMV8
 #
 # Debugger library - linked into VBoxVMM, ARMv8 variant.
 #
 # @todo Can this be merged into one library later maybe?
 ifdef VRA_WITH_DEBUGGER
  LIBRARIES += Debugger-armv8
 endif
 Debugger-armv8_TEMPLATE  = VBoxR3Dll
 Debugger-armv8_DEFS      = VRA_VMM_TARGET_ARMV8 IN_VMM_R3 IN_DBG_R3 IN_DIS VRA_WITH_DEBUGGER
 ifneq ($(KBUILD_TYPE),release)
  Debugger-armv8_DEFS    += VRA_WITH_DEBUGGER_TCP_BY_DEFAULT
 endif
 Debugger-armv8_SOURCES   = \
 	DBGConsole.cpp \
 	DBGCEval.cpp \
 	DBGCBuiltInSymbols.cpp \
 	DBGCCmdHlp.cpp \
 	DBGCCmdWorkers.cpp \
 	DBGCCommands.cpp \
 	DBGCDumpImage.cpp \
 	DBGCNtCommands.cpp \
 	DBGCFunctions.cpp \
 	DBGCEmulateCodeView.cpp \
 	DBGCOps.cpp \
 	DBGCGdbRemoteStub.cpp \
 	DBGCRemoteKd.cpp \
 	DBGCIo.cpp \
 	DBGCIoProvTcp.cpp \
 	DBGCIoProvUdp.cpp \
 	DBGCIoProvIpc.cpp \
 	DBGCScreenAscii.cpp
endif # VRA_WITH_VIRT_ARMV8


#
# Executable Image dumper based on the dumpimage debugger command.
#
PROGRAMS += VBoxDumpImage
VBoxDumpImage_TEMPLATE = VBoxR3Tool
VBoxDumpImage_DEFS    := DBGC_DUMP_IMAGE_TOOL
VBoxDumpImage_SOURCES := DBGCDumpImage.cpp
$(call VRA_SET_VER_INFO_DLL,VBoxDumpImage,VirtualAgent Executable Image Dumper Utility)


#
# The diggers plug-in.
#
DLLS += DbgPlugInDiggers
DbgPlugInDiggers_TEMPLATE = VBoxR3Dll
DbgPlugInDiggers_DEFS     = IN_DIS
DbgPlugInDiggers_SOURCES = \
	DBGPlugInDiggers.cpp \
	DBGPlugInDarwin.cpp \
	DBGPlugInLinux.cpp \
	DBGPlugInSolaris.cpp \
	DBGPlugInWinNt.cpp \
	DBGPlugInOS2.cpp \
	DBGPlugInFreeBsd.cpp \
	DBGPlugInCommonELF.cpp
DbgPlugInDiggers_LIBS = \
	$(PATH_STAGE_LIB)/DisasmR3$(VRA_SUFF_LIB) \
	$(LIB_RUNTIME)
$(call VRA_SET_VER_INFO_DLL,DbgPlugInDiggers,VirtualAgent Debugger Guest OS Digger Plug-in)


#
# The DBGC parser testcase.
# This stubs all the VBoxVMM APIs.
#
tstDBGCParser_TEMPLATE = VBoxR3TstExe
tstDBGCParser_DEFS = IN_VMM_R3
tstDBGCParser_CXXFLAGS = $(VRA_C_CXX_FLAGS_NO_UNUSED_PARAMETERS)
tstDBGCParser_SOURCES = \
	testcase/tstDBGCParser.cpp \
	testcase/tstDBGCStubs.cpp
tstDBGCParser_LIBS = \
	$(Debugger_1_TARGET) \
	$(LIB_RUNTIME)


if defined(VRA_WITH_QTGUI) && defined(VRA_WITH_DEBUGGER_GUI)
 #
 # Debugger GUI component (Qt).
 #
 USES += qt6
 DLLS += VBoxDbg
 VBoxDbg_TEMPLATE = VBoxQtGuiDll
 VBoxDbg_DEFS = IN_DBG_R3
 VBoxDbg_INCS = .
 VBoxDbg_QT_MODULES = Core Gui Widgets
 VBoxDbg_QT_MOCHDRS = \
 	VBoxDbgGui.h \
 	VBoxDbgConsole.h \
 	VBoxDbgStatsQt.h
 VBoxDbg_SOURCES = \
 	VBoxDbg.cpp \
 	VBoxDbgGui.cpp \
 	VBoxDbgBase.cpp \
 	VBoxDbgConsole.cpp \
 	VBoxDbgStatsQt.cpp
 VBoxDbg_CXXFLAGS.win += /permissive-
 VBoxDbg_LDFLAGS.darwin = \
 	-install_name $(VRA_DYLD_EXECUTABLE_PATH)/VBoxDbg.dylib
 $(call VRA_SET_VER_INFO_DLL,VBoxDbg,VirtualAgent Debugger GUI)
endif # Qt


include $(FILE_KBUILD_SUB_FOOTER)

