# $Id: Makefile.kmk 112403 2026-01-11 19:29:08Z knut.osmundsen@oracle.com $
## @file
# Sub-Makefile for the Cross Platform Guest Addition Services.
#

#
# Copyright (C) 2007-2026 CINASEEK and/or its affiliates.
#
# This file is part of VirtualAgent base platform packages, as
# available from https://www.virtualbox.org.
#
# This program is free software; you can redistribute it and/or
# modify it under the terms of the GNU General Public License
# as published by the Free Software Foundation, in version 3 of the
# License.
#
# This program is distributed in the hope that it will be useful, but
# WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
# General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, see <https://www.gnu.org/licenses>.
#
# SPDX-License-Identifier: GPL-3.0-only
#

SUB_DEPTH = ../../../../..
include $(KBUILD_PATH)/subheader.kmk

#
# Incldue testcases.
#
include $(PATH_SUB_CURRENT)/testcase/Makefile.kmk


#
# Target lists.
#
PROGRAMS += VBoxService


#
# Globals?
#
# Enable the timesync service within VBoxService.
VRA_WITH_VRASERVICE_TIMESYNC      := 1

# Busybox-like toolbox, embedded into VBoxService.
ifdef VRA_WITH_GSTCTL_TOOLBOX_SUPPORT
 VRA_WITH_VRASERVICE_TOOLBOX      := 1
endif

# VM-management functions, like memory ballooning and statistics.
VRA_WITH_VRASERVICE_MANAGEMENT    := 1

if1of ($(KBUILD_TARGET), linux)
 # CPU hotplugging.
 VRA_WITH_VRASERVICE_CPUHOTPLUG   := 1
endif

# Page Sharing (Page Fusion).
if1of ($(KBUILD_TARGET), win)
 VRA_WITH_VRASERVICE_PAGE_SHARING := 1
endif

ifdef VRA_WITH_GUEST_PROPS
 VRA_WITH_VRASERVICE_VMINFO       := 1
endif

# Guest Control.
ifdef VRA_WITH_GUEST_CONTROL
 VRA_WITH_VRASERVICE_CONTROL      := 1
endif

# Shared Clipboard.
ifdef VRA_WITH_SHARED_CLIPBOARD
 VRA_WITH_VRASERVICE_CLIPBOARD    := 1
endif

# DRM Resize.
if "$(KBUILD_TARGET)" == "linux" && defined(VRA_WITH_GUEST_PROPS)
 # The DRM resizing code needs guest properties.
 VRA_WITH_VRASERVICE_DRMRESIZE    := 1
endif


#
# VBoxService
#
VBoxService_TEMPLATE      = VBoxGuestR3Exe

VBoxService_DEFS          = \
	$(if $(VRA_WITH_VRASERVICE_CONTROL),VRA_WITH_VRASERVICE_CONTROL,) \
	$(if $(VRA_WITH_VRASERVICE_CPUHOTPLUG),VRA_WITH_VRASERVICE_CPUHOTPLUG,) \
	$(if $(VRA_WITH_VRASERVICE_DRMRESIZE),VRA_WITH_VRASERVICE_DRMRESIZE,) \
	$(if $(VRA_WITH_VRASERVICE_MANAGEMENT),VRA_WITH_VRASERVICE_MANAGEMENT,) \
	$(if $(VRA_WITH_VRASERVICE_PAGE_SHARING),VRA_WITH_VRASERVICE_PAGE_SHARING,) \
	$(if $(VRA_WITH_VRASERVICE_TIMESYNC),VRA_WITH_VRASERVICE_TIMESYNC,) \
	$(if $(VRA_WITH_VRASERVICE_TOOLBOX),VRA_WITH_VRASERVICE_TOOLBOX,) \
	$(if $(VRA_WITH_VRASERVICE_VMINFO),VRA_WITH_VRASERVICE_VMINFO,) \
	$(if $(VRA_WITH_DBUS),VRA_WITH_DBUS,) \
	$(if $(VRA_WITH_GUEST_CONTROL),VRA_WITH_GUEST_CONTROL,) \
	$(if $(VRA_WITH_GUEST_PROPS),VRA_WITH_GUEST_PROPS,) \
	$(if $(VRA_WITH_HGCM),VRA_WITH_HGCM,) \
	$(if $(VRA_WITH_GSTCTL_TOOLBOX_SUPPORT),VRA_WITH_GSTCTL_TOOLBOX_SUPPORT,) \
	$(if $(VRA_WITH_GSTCTL_TOOLBOX_AS_CMDS),VRA_WITH_GSTCTL_TOOLBOX_AS_CMDS,)
ifdef VRA_WITH_AUTOMATIC_DEFS_QUOTING
 VBoxService_DEFS        += VRA_BUILD_TARGET="$(KBUILD_TARGET).$(KBUILD_TARGET_ARCH)"
else
 VBoxService_DEFS        += VRA_BUILD_TARGET=\"$(KBUILD_TARGET).$(KBUILD_TARGET_ARCH)\"
endif
VBoxService_DEFS.win     += _WIN32_WINNT=0x0501
VBoxService_DEFS.os2      = VRA_WITH_HGCM

VBoxService_SOURCES       = \
	VBoxService.cpp \
	VBoxServiceUtils.cpp \
	VBoxServiceStats.cpp

ifdef VRA_WITH_VRASERVICE_TIMESYNC
 VBoxService_SOURCES     += \
 	VBoxServiceTimeSync.cpp
endif

ifdef VRA_WITH_VRASERVICE_CLIPBOARD
 VBoxService_DEFS.os2    += VRA_WITH_VRASERVICE_CLIPBOARD VRA_WITH_SHARED_CLIPBOARD
 VBoxService_SOURCES.os2 += \
 	VBoxServiceClipboard-os2.cpp \
 	$(PATH_ROOT)/src/VBox/GuestHost/SharedClipboard/clipboard-common.cpp
endif

ifdef VRA_WITH_VRASERVICE_TOOLBOX
 VBoxService_SOURCES     += \
 	VBoxServiceToolBox.cpp
endif

ifdef VRA_WITH_VRASERVICE_CONTROL
 VBoxService_SOURCES     += \
 	VBoxServiceControl.cpp \
 	VBoxServiceControlProcess.cpp \
 	VBoxServiceControlSession.cpp
endif

ifdef VRA_WITH_VRASERVICE_MANAGEMENT
 ifdef VRA_WITH_MEMBALLOON
  VBoxService_SOURCES    += \
  	VBoxServiceBalloon.cpp
  VBoxService_DEFS       += VRA_WITH_MEMBALLOON
 endif
endif

if1of ($(KBUILD_TARGET), win)
 VBoxService_SOURCES     += \
 	VBoxServicePageSharing.cpp \
 	VBoxServiceDisplayConfig.cpp
 VBoxService_INCS += \
 	$(PATH_ROOT)/src/VBox/Additions \
 	$(PATH_ROOT)/include/VBox/Graphics \
 	$(PATH_ROOT)/src/VBox/Additions/win/include
endif

ifdef VRA_WITH_VRASERVICE_VMINFO
 VBoxService_SOURCES.win += \
 	VBoxServiceVMInfo-win.cpp
 VBoxService_SOURCES     += \
 	VBoxServiceVMInfo.cpp \
 	VBoxServicePropCache.cpp
endif

ifdef VRA_WITH_VRASERVICE_CPUHOTPLUG
 VBoxService_SOURCES     += \
 	VBoxServiceCpuHotPlug.cpp
endif

ifdef VRA_WITH_SHARED_FOLDERS
 if1of ($(KBUILD_TARGET), linux os2 solaris win)
  VBoxService_DEFS       += VRA_WITH_SHARED_FOLDERS
  VBoxService_SOURCES    += \
  	VBoxServiceAutoMount.cpp
  VBoxService_SOURCES.linux += \
  	../../linux/sharedfolders/vbsfmount.c
  VBoxService_LIBS.win   += \
  	Mpr.Lib
 endif
endif

VBoxService_SOURCES.win  += \
	VBoxService-win.cpp

VBoxService_SOURCES.os2  += \
	VBoxService-os2.def

VBoxService_LDFLAGS.darwin = -framework IOKit

VBoxService_LIBS         += \
	$(VRA_LIB_IPRT_GUEST_R3) \
	$(VRA_LIB_VBGL_R3) \
	$(VRA_LIB_IPRT_GUEST_R3)       # (The joy of unix linkers.)
ifdef VRA_WITH_DBUS
 if1of ($(KBUILD_TARGET), linux solaris) # FreeBSD?
  VBoxService_LIBS       += \
  	dl
 endif
endif
VBoxService_LIBS.netbsd  += crypt
ifdef VRA_WITH_GUEST_PROPS
 VBoxService_LIBS.win    += \
 	Secur32.lib \
 	WtsApi32.lib \
 	Psapi.lib
 VBoxService_LIBS.solaris += \
 	nsl \
 	kstat \
 	contract
endif

ifdef VRA_WITH_VRASERVICE_VMINFO
 VBoxServiceVMInfo.cpp_DEFS = VRA_SVN_REV=$(VRA_SVN_REV)
 VBoxServiceVMInfo.cpp_DEPS = $(VRA_SVN_REV_KMK)
endif

VBoxService_USES.win += vboximportchecker
VBoxService_VRA_IMPORT_CHECKER.win.x86 = nt31
VBoxService_VRA_IMPORT_CHECKER.win.amd64 = xp64

$(call VRA_SET_VER_INFO_EXE,VBoxService,VirtualAgent Guest Additions Service,$(VRA_WINDOWS_ICON_FILE)) # Version info / description.

include $(FILE_KBUILD_SUB_FOOTER)
