# $Id: Makefile.kmk 113146 2026-02-24 15:28:25Z vadim.galitsyn@oracle.com $
## @file
# Makefile for the linux guest additions base directory.
#

#
# Copyright (C) 2006-2026 CINASEEK and/or its affiliates.
#
# This file is part of VirtualAgent base platform packages, as
# available from https://www.virtualbox.org.
#
# This program is free software; you can redistribute it and/or
# modify it under the terms of the GNU General Public License
# as published by the Free Software Foundation, in version 3 of the
# License.
#
# This program is distributed in the hope that it will be useful, but
# WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
# General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, see <https://www.gnu.org/licenses>.
#
# SPDX-License-Identifier: GPL-3.0-only
#

SUB_DEPTH = ../../../..
include $(KBUILD_PATH)/subheader.kmk

#
# Include sub-makefiles.
#
include $(PATH_SUB_CURRENT)/sharedfolders/Makefile.kmk
include $(PATH_SUB_CURRENT)/drm/Makefile.kmk


#
# Globals
#

# Basic path components
VRA_LNX_ADD_PACKAGE_NAME         := VBoxGuestAdditions
VRA_LNX_ADD_INST_OUT_DIR         := $(PATH_TARGET)/Additions/Installer/linux/
VRA_LNX_ADD_INST_DBG_DIR         := $(VRA_LNX_ADD_INST_OUT_DIR)debug/
VRA_LNX_ADD_INST_STAGE_DIR       := $(VRA_LNX_ADD_INST_OUT_DIR)install/

# Installation paths for binaries and files
VRA_LNX_ADD_INST_BIN_DIR         := $(VRA_LNX_ADD_INST_OUT_DIR)bin/
VRA_LNX_ADD_INST_SBIN_DIR        := $(VRA_LNX_ADD_INST_OUT_DIR)sbin/
VRA_LNX_ADD_INST_LIB_DIR         := $(VRA_LNX_ADD_INST_OUT_DIR)lib/
VRA_LNX_ADD_INST_OTHER_DIR       := $(VRA_LNX_ADD_INST_OUT_DIR)other/
VRA_LNX_ADD_INST_KMOD_DIR_BASE   := $(VRA_LNX_ADD_INST_OUT_DIR)src/
# This is a symbolic link, so no trailing slash.
VRA_LNX_ADD_INST_KMOD_PATH       := $(VRA_LNX_ADD_INST_KMOD_DIR_BASE)vboxguest-$(VRA_VERSION_STRING)
VRA_LNX_ADD_INST_INIT_DIR        := $(VRA_LNX_ADD_INST_OUT_DIR)init/

VRA_LNX_ADD_ARCH_INST_DIRS       := \
	$(VRA_LNX_ADD_INST_OUT_DIR) \
	$(VRA_LNX_ADD_INST_BIN_DIR) \
	$(VRA_LNX_ADD_INST_SBIN_DIR) \
	$(VRA_LNX_ADD_INST_INIT_DIR)

# Installation paths for debug symbols
VRA_LNX_ADD_DBG_BIN_DIR          := $(VRA_LNX_ADD_INST_DBG_DIR)bin/
VRA_LNX_ADD_DBG_SBIN_DIR         := $(VRA_LNX_ADD_INST_DBG_DIR)sbin/
VRA_LNX_ADD_DBG_LIB_DIR          := $(VRA_LNX_ADD_INST_DBG_DIR)lib/
VRA_LNX_ADD_DBG_OTHER_DIR        := $(VRA_LNX_ADD_INST_DBG_DIR)other/

VRA_LNX_ADD_DBG_DIRS             := \
	$(VRA_LNX_ADD_DBG_BIN_DIR) \
	$(VRA_LNX_ADD_DBG_SBIN_DIR) \
	$(VRA_LNX_ADD_DBG_OTHER_DIR)

# Script source directories
VRA_PATH_LNX_ADD_INST            := $(PATH_SUB_CURRENT)/installer/
VRA_REL_LNX_ADD_INST             := $(subst $(PATH_ROOT)/src/VBox, ../..,$(VRA_PATH_LNX_ADD_INST))
VRA_PATH_X11_ADD_INST            := $(PATH_ROOT)/src/VBox/Additions/x11/Installer/
VRA_REL_X11_ADD_INST             := $(subst $(PATH_ROOT)/src/VBox, ../..,$(VRA_PATH_X11_ADD_INST))
VRA_PATH_LNX_INST_SRC            := $(PATH_ROOT)/src/VBox/Installer/linux/
VRA_REL_LNX_INST_SRC             := $(subst $(PATH_ROOT)/src/VBox, ../..,$(VRA_PATH_LNX_INST_SRC))
VRA_PATH_LNX_HOST_DRV            := $(PATH_ROOT)/src/VBox/HostDrivers/linux/
VRA_REL_LNX_HOST_DRV             := $(subst $(PATH_ROOT)/src/VBox, ../..,$(VRA_PATH_LNX_HOST_DRV))

# Unset this to speed up things during makefile hacking.
VRA_LNX_ADD_INST_DEP_ON_MAKEFILE := $(MAKEFILE_CURRENT)


#
# Targets
#
VRA_SELINUX_CMPLD := $(PATH_SUB_CURRENT)/selinux-fedora/vbox_x11.pp
VRA_LNX_ADD_ARCHIVE.x86   := $(PATH_OUT_BASE)/linux.x86/$(KBUILD_TYPE)/bin/additions/VBoxGuestAdditions-x86.tar.bz2
VRA_LNX_ADD_ARCHIVE.amd64 := $(PATH_OUT_BASE)/linux.amd64/$(KBUILD_TYPE)/bin/additions/VBoxGuestAdditions-amd64.tar.bz2
ifdef VRA_WITH_LNX_ARM64_ADDITIONS
 VRA_LNX_ADD_ARCHIVE.arm64 := $(PATH_OUT_BASE)/linux.arm64/$(KBUILD_TYPE)/bin/additions/VBoxGuestAdditions-arm64.tar.bz2
endif
ifndef VRA_WITH_COMBINED_LINUX_GUEST_PACKAGE
 VRA_LNX_ADD_ARCHIVES := $(PATH_STAGE_BIN)/additions/VBoxGuestAdditions-$(KBUILD_TARGET_ARCH).tar.bz2
else
 VRA_LNX_ADD_ARCHIVES := \
 	$(VRA_LNX_ADD_ARCHIVE.x86) \
 	$(VRA_LNX_ADD_ARCHIVE.amd64) \
 	$(if-expr defined(VRA_WITH_LNX_ARM64_ADDITIONS) && defined(VRA_WITH_COMBINED_LINUX_GUEST_PACKAGE_INCLUDING_ARM64),$(VRA_LNX_ADD_ARCHIVE.arm64),)
endif
BLDDIRS     += \
	$(VRA_LNX_ADD_ARCH_INST_DIRS) \
	$(VRA_LNX_ADD_DBG_DIRS) \
	$(VRA_LNX_ADD_INST_STAGE_DIR)

# Use VRA_WITHOUT_LINUX_GUEST_PACKAGE to skip building the .run installer.
# This will only take effect if you also use VRA_WITHOUT_ADDITIONS_ISO.
PACKING     += \
	$(if-expr !defined(VRA_WITHOUT_LINUX_GUEST_PACKAGE), $(PATH_STAGE_BIN)/additions/VBoxLinuxAdditions.run,) \
	$(VRA_LNX_ADD_ARCHIVES) \
	$(PATH_STAGE_BIN)/additions/VBoxGuestAdditions-dbg.tar.bz2
OTHER_CLEAN += \
	$(PACKING) \
	$(VRA_LNX_ADD_INST_KMOD_PATH) \
	$(foreach file, $(VRA_LNX_ADD_ARCHIVES), $(VRA_LNX_ADD_INST_STAGE_DIR)$(subst -r$(VRA_SVN_REV),,$(notdir $(file))))


#
# Files to install
#
VRA_LNX_ADD_STRIP_BIN += \
	VBoxControl \
	VBoxDRMClient \
	VBoxClient
ifdef VRA_WITH_ADDITIONS_SHIPPING_AUDIO_TEST
 VRA_LNX_ADD_STRIP_BIN += \
 	VBoxAudioTest
endif
ifdef VRA_WITH_WAYLAND_ADDITIONS
 VRA_LNX_ADD_STRIP_BIN += \
 	vboxwl
endif

VRA_LNX_ADD_STRIP_SBIN += \
	VBoxService

VRA_LNX_ADD_STRIP_MOD = \
	$(if $(VRA_WITH_PAM),pam_vbox.so,) \
	mount.vboxsf

ifndef VRA_NO_LEGACY_XORG_X11
 VRA_LNX_ADD_STRIP_MOD += \
 	vboxmouse_drv_70.so \
 	vboxmouse_drv_71.so \
 	vboxmouse_drv_13.so \
 	vboxmouse_drv_14.so \
 	vboxmouse_drv_15.so \
 	vboxmouse_drv_16.so \
 	$(addsuffix .so,$(filter-out %_32,$(filter vboxvideo_drv_%,$(DLLS))))
endif

VRA_LNX_ADD_MOD = \
	98vboxadd-xclient \
	x11config.sh

ifndef VRA_NO_LEGACY_XORG_X11
 VRA_LNX_ADD_STRIP_OBJ = \
 	vboxmouse_drv.o \
 	vboxvideo_drv.o
endif

VRA_LNX_ADD_INIT = \
	vboxadd \
	vboxadd-service \
	vboxadd-x11

#
# All the files that go into the archive
#
VRA_LNX_ADD_INST_FILES := \
	$(addprefix $(VRA_LNX_ADD_INST_BIN_DIR),$(VRA_LNX_ADD_STRIP_BIN)) \
	$(addprefix $(VRA_LNX_ADD_INST_BIN_DIR),$(VRA_LNX_ADD_BIN)) \
	$(addprefix $(VRA_LNX_ADD_INST_SBIN_DIR),$(VRA_LNX_ADD_STRIP_SBIN)) \
	$(addprefix $(VRA_LNX_ADD_INST_LIB_DIR),$(VRA_LNX_ADD_STRIP_LIB)) \
	$(addprefix $(VRA_LNX_ADD_INST_OTHER_DIR),$(VRA_LNX_ADD_STRIP_MOD)) \
	$(addprefix $(VRA_LNX_ADD_INST_OTHER_DIR),$(VRA_LNX_ADD_MOD)) \
	$(addprefix $(VRA_LNX_ADD_INST_OTHER_DIR),$(VRA_LNX_ADD_STRIP_OBJ)) \
	$(addprefix $(VRA_LNX_ADD_INST_INIT_DIR),$(VRA_LNX_ADD_INIT))

VRA_LNX_ADD_DBG_FILES := \
	$(addprefix $(VRA_LNX_ADD_DBG_BIN_DIR),$(VRA_LNX_ADD_STRIP_BIN)) \
	$(addprefix $(VRA_LNX_ADD_DBG_SBIN_DIR),$(VRA_LNX_ADD_STRIP_SBIN)) \
	$(addprefix $(VRA_LNX_ADD_DBG_LIB_DIR),$(VRA_LNX_ADD_STRIP_LIB)) \
	$(addprefix $(VRA_LNX_ADD_DBG_OTHER_DIR),$(VRA_LNX_ADD_STRIP_MOD))

# Cleanup of the installer directory files
OTHER_CLEAN += $(VRA_LNX_ADD_INST_FILES) $(VRA_LNX_ADD_DBG_FILES)

# pattern rules for copying the debug info from the VRA_LNX_ADD_STRIP_* files to the installation directory
$(addprefix $(VRA_LNX_ADD_DBG_BIN_DIR),$(VRA_LNX_ADD_STRIP_BIN)): \
		$(VRA_LNX_ADD_DBG_BIN_DIR)% : $(PATH_STAGE_BIN)/additions/% | $$(dir $$@)
	$(call MSG_TOOL,copydbg,$<,$@)
	$(QUIET)$(VRA_OBJCOPY) --only-keep-debug $< $@

$(addprefix $(VRA_LNX_ADD_DBG_SBIN_DIR),$(VRA_LNX_ADD_STRIP_SBIN)): \
		$(VRA_LNX_ADD_DBG_SBIN_DIR)% : $(PATH_STAGE_BIN)/additions/% | $$(dir $$@)
	$(call MSG_TOOL,copydbg,$<,$@)
	$(QUIET)$(VRA_OBJCOPY) --only-keep-debug $< $@

$(addprefix $(VRA_LNX_ADD_DBG_LIB_DIR),$(VRA_LNX_ADD_STRIP_LIB)): \
		$(VRA_LNX_ADD_DBG_LIB_DIR)% : $(PATH_STAGE_BIN)/additions/% | $$(dir $$@)
	$(call MSG_TOOL,copydbg,$<,$@)
	$(QUIET)$(VRA_OBJCOPY) --only-keep-debug $< $@

$(addprefix $(VRA_LNX_ADD_DBG_OTHER_DIR),$(VRA_LNX_ADD_STRIP_MOD)): \
		$(VRA_LNX_ADD_DBG_OTHER_DIR)% : $(PATH_STAGE_BIN)/additions/% | $$(dir $$@)
	$(call MSG_TOOL,copydbg,$<,$@)
	$(QUIET)$(VRA_OBJCOPY) --only-keep-debug $< $@

# pattern rule for stripping and copying the VRA_LNX_ADD_STRIP_BIN files to the installation directory
$(addprefix $(VRA_LNX_ADD_INST_BIN_DIR),$(VRA_LNX_ADD_STRIP_BIN)): \
		$(VRA_LNX_ADD_INST_BIN_DIR)% : $(PATH_STAGE_BIN)/additions/% \
		$(VRA_LNX_ADD_DBG_BIN_DIR)% \
		| $$(dir $$@)
	$(call MSG_INST_FILE,$<,$@)
	$(QUIET)$(INSTALL) -m 0755 $(if $(VRA_DO_STRIP),-s,) $< $@
	$(QUIET)$(VRA_OBJCOPY) --add-gnu-debuglink=$(subst $(VRA_LNX_ADD_INST_BIN_DIR),$(VRA_LNX_ADD_DBG_BIN_DIR),$@) $@

# pattern rule for stripping and copying the VRA_LNX_ADD_STRIP_SBIN files to the installation directory
$(addprefix $(VRA_LNX_ADD_INST_SBIN_DIR), \
	$(filter-out vbox-greeter,$(VRA_LNX_ADD_STRIP_SBIN))): \
		$(VRA_LNX_ADD_INST_SBIN_DIR)% : $(PATH_STAGE_BIN)/additions/% \
		$(VRA_LNX_ADD_DBG_SBIN_DIR)% \
		| $$(dir $$@)
	$(call MSG_INST_FILE,$<,$@)
	$(QUIET)$(INSTALL) -m 0755 $(if $(VRA_DO_STRIP),-s,) $< $@
	$(QUIET)$(VRA_OBJCOPY) --add-gnu-debuglink=$(subst $(VRA_LNX_ADD_INST_SBIN_DIR),$(VRA_LNX_ADD_DBG_SBIN_DIR),$@) $@

# pattern rule for stripping and copying vbox-greeter to the installation directory
$(addprefix $(VRA_LNX_ADD_INST_SBIN_DIR),vbox-greeter): \
		$(VRA_LNX_ADD_INST_SBIN_DIR)% : $(subst linux.amd64/release,linux.amd64/release/greeter,$(subst linux.x86/release,linux.x86/release/greeter,$(PATH_STAGE_BIN)))/additions/% \
		| $$(dir $$@)
	$(call MSG_INST_FILE,$<,$@)
	$(QUIET)$(INSTALL) -m 0755 $< $@

# pattern rule for stripping and copying the VRA_LNX_ADD_STRIP_LIB files to the installation directory
$(addprefix $(VRA_LNX_ADD_INST_LIB_DIR),$(VRA_LNX_ADD_STRIP_LIB)): \
		$(VRA_LNX_ADD_INST_LIB_DIR)% : $(PATH_STAGE_BIN)/additions/% \
		$(VRA_LNX_ADD_DBG_LIB_DIR)% \
		| $$(dir $$@)
	$(call MSG_INST_FILE,$<,$@)
	$(QUIET)$(INSTALL) -m 0755 $(if $(VRA_DO_STRIP),-s,) $< $@
	$(QUIET)$(VRA_OBJCOPY) --add-gnu-debuglink=$(subst $(VRA_LNX_ADD_INST_LIB_DIR),$(VRA_LNX_ADD_DBG_LIB_DIR),$@) $@

# pattern rule for stripping and copying the VRA_LNX_ADD_STRIP_MOD files to the installation directory
$(addprefix $(VRA_LNX_ADD_INST_OTHER_DIR),$(VRA_LNX_ADD_STRIP_MOD)): \
		$(VRA_LNX_ADD_INST_OTHER_DIR)% : $(PATH_STAGE_BIN)/additions/% \
		$(VRA_LNX_ADD_DBG_OTHER_DIR)% \
		| $$(dir $$@)
	$(call MSG_INST_FILE,$<,$@)
	$(QUIET)$(INSTALL) -m 0755 $(if $(VRA_DO_STRIP),-s,) $< $@
	$(QUIET)$(VRA_OBJCOPY) --add-gnu-debuglink=$(subst $(VRA_LNX_ADD_INST_OTHER_DIR),$(VRA_LNX_ADD_DBG_OTHER_DIR),$@) $@

# pattern rule for stripping and copying the VRA_LNX_ADD_STRIP_OBJ files to the installation directory
$(addprefix $(VRA_LNX_ADD_INST_OTHER_DIR),$(VRA_LNX_ADD_STRIP_OBJ)): \
		$(VRA_LNX_ADD_INST_OTHER_DIR)% : $(PATH_STAGE_BIN)/additions/% | $$(dir $$@)
	$(call MSG_INST_FILE,$<,$@)
ifeq ($(VRA_DO_STRIP),)
	$(QUIET)$(INSTALL) -m 0644 $< $@
else # strip to temp file because of umask.
	$(QUIET)$(VRA_OBJCOPY) --strip-unneeded -R .comment $< $@.tmp
	$(QUIET)$(INSTALL) -m 0644 $@.tmp $@
	$(QUIET)$(RM) -f -- $@.tmp
endif

include $(PATH_ROOT)/src/VBox/Additions/common/VBoxGuest/linux/files_vboxguest
VRA_LNX_ADD_INST_FILES_VRAGUEST = $(patsubst =>%,$(PATH_STAGE_BIN)/additions/src/vboxguest/%,$(filter =>%,$(subst =>, =>,$(subst $(DQUOTE),,$(FILES_VRAGUEST_NOBIN)))))
include $(PATH_ROOT)/src/VBox/Additions/linux/sharedfolders/files_vboxsf
VRA_LNX_ADD_INST_FILES_VRASF = $(patsubst =>%,$(PATH_STAGE_BIN)/additions/src/vboxsf/%,$(filter =>%,$(subst =>, =>,$(subst $(DQUOTE),,$(FILES_VRASF_NOBIN)))))
include $(PATH_ROOT)/src/VBox/Additions/linux/drm/files_vboxvideo_drv
VRA_LNX_ADD_INST_FILES_VRAVIDEO = $(patsubst =>%,$(PATH_STAGE_BIN)/additions/src/vboxvideo/%,$(filter =>%,$(subst =>, =>,$(subst $(DQUOTE),,$(FILES_VRAVIDEO_DRM_NOBIN)))))

# special rule for the kernel modules
$(VRA_LNX_ADD_INST_KMOD_DIR_BASE): \
		$(PATH_STAGE_BIN)/additions/src/ \
		$(PATH_ROOT)/Version.kmk \
		| $(dir $@)
	$(call MSG_INST_SYM,$<,$@)
	$(QUIET)$(RM) -Rf $@
	$(QUIET)$(MKDIR) $@
	$(QUIET)$(LN_SYMLINK) $< $(VRA_LNX_ADD_INST_KMOD_PATH)

INSTALLS += GuestDrivers-src
GuestDrivers-src_INST = $(INST_ADDITIONS)src/
GuestDrivers-src_MODE = a+r,u+w
GuestDrivers-src_SOURCES = Makefile


INSTALLS += lnx_add_inst-exec
lnx_add_inst-exec_INST     = $(VRA_LNX_ADD_INST_OTHER_DIR)
lnx_add_inst-exec_INSTTYPE = stage
lnx_add_inst-exec_EXEC_SOURCES  = \
	$(VRA_REL_X11_ADD_INST)98vboxadd-xclient \
	$(VRA_REL_X11_ADD_INST)x11config.sh \
	$(VRA_REL_LNX_INST_SRC)check_module_dependencies.sh


INSTALLS += lnx_add_inst-noexec
lnx_add_inst-noexec_INST     = $(VRA_LNX_ADD_INST_OTHER_DIR)
lnx_add_inst-noexec_INSTTYPE = stage
lnx_add_inst-noexec_SOURCES  = \
	$(VRA_REL_X11_ADD_INST)vboxclient.desktop \
	$(VRA_REL_X11_ADD_INST)vboxvideo.ids \
	selinux-fedora/vbox_x11.pp \
	selinux-fedora/vbox_accel.pp

INSTALLS += lnx_add_inst-license
lnx_add_inst-license_INST     = $(VRA_LNX_ADD_INST_OUT_DIR)
lnx_add_inst-license_INSTTYPE = stage
lnx_add_inst-license_SOURCES  = \
	$(VRA_BRAND_LICENSE_TXT)=>LICENSE


#
# We need our routines.sh and the uninstallation scripts in the staging
# directory too
#
INSTALLS += LnxAdd-scripts
LnxAdd-scripts_INST     = $(VRA_LNX_ADD_INST_STAGE_DIR)
LnxAdd-scripts_INSTTYPE = stage
LnxAdd-scripts_SOURCES  = \
	$(VRA_REL_LNX_ADD_INST)deffiles
LnxAdd-scripts_EXEC_SOURCES  = \
	$(VRA_REL_LNX_INST_SRC)routines.sh


#
# And the init scripts
#
INSTALLS += LnxAdd-init-scripts
LnxAdd-init-scripts_INST         = $(VRA_LNX_ADD_INST_INIT_DIR)
LnxAdd-init-scripts_INSTTYPE     = stage
LnxAdd-init-scripts_EXEC_SOURCES = \
	$(foreach i,$(VRA_LNX_ADD_INIT), installer/$(i).sh=>$(i))

# this file needs editing before it can be included in the generic installer.
$(VRA_LNX_ADD_INST_STAGE_DIR)install.sh: \
		$(VRA_PATH_LNX_ADD_INST)install.sh.in \
		$(VRA_VERSION_STAMP) | $$(dir $$@)
	$(RM) -f -- $@
	$(QUIET)$(SED) \
		-e "s;_VERSION_;$(VRA_VERSION_STRING);g" \
		-e "s;_BUILDTYPE_;$(KBUILD_TYPE);g" \
		-e "s;_USERNAME_;$(USERNAME);g" \
		--output $@ \
		$<
	$(QUIET)$(CHMOD) 0755 $@
OTHER_CLEAN += \
	$(VRA_LNX_ADD_INST_OUT_DIR)install.sh \
	$(VRA_LNX_ADD_INST_STAGE_DIR)install.sh


#
# Build test for the Guest Additions' vboxvideo kernel module (kmk check).
# We deprecated module starting from kernel 7.0, so only build
# it for earlier versions.
#
KERN_MAJ = $(shell uname -r | cut -d . -f1)
$(if-expr $(KERN_MAJ) < 7,$(evalcall2 VRA_LINUX_KMOD_TEST_BUILD_RULE_FN,vboxvideo-src,,),)


include $(FILE_KBUILD_SUB_FOOTER)


# All the files that go into our archive
VRA_LNX_ADD_ARCH_FILES = \
	$(lnx_add_inst-noexec_2_STAGE_TARGETS) \
	$(lnx_add_inst-exec_2_STAGE_TARGETS) \
	$(lnx_add_inst-license_2_STAGE_TARGETS) \
	$(VRA_LNX_ADD_INST_FILES) \
	$(VRA_LNX_ADD_INST_KMOD_DIR_BASE)

VRA_LNX_ADD_INST_ARCH_DEPS := \
	$(VRA_LNX_ADD_ARCH_FILES) \
	$(VRA_LNX_ADD_INST_DEP_ON_MAKEFILE) \
	$(VRA_VERSION_STAMP) \
	$(VRA_LNX_ADD_INST_FILES_VRAGUEST) \
	$(VRA_LNX_ADD_INST_FILES_VRASF) \
	$(VRA_LNX_ADD_INST_FILES_VRAVIDEO)

#
# .tar.bz2 for converting into .run
#
$(VRA_LNX_ADD_ARCHIVE.$(KBUILD_TARGET_ARCH)): \
		$(VRA_LNX_ADD_INST_ARCH_DEPS)
	$(call MSG_L1,Packing $@)
	$(QUIET)$(RM) -f -- $(wildcard $(dir $@)VBoxGuestAdditions-*r*.tar.bz2)
	$(QUIET)$(MKDIR) -p $(@D)
	$(QUIET)$(CHMOD) 0755 $(VRA_LNX_ADD_ARCH_INST_DIRS)
ifdef VRA_USE_PBZIP2
	$(QUIET)$(VRA_GTAR) --dereference --owner 0 --group 0 -cRf $(patsubst %.bz2,%,$@) \
		-C $(VRA_LNX_ADD_INST_OUT_DIR) \
		LICENSE bin init lib other sbin src \
		$(if $(filter $(KBUILD_TYPE),debug),debug)
	$(QUIET)pbzip2 $(patsubst %.bz2,%,$@)
else
	$(QUIET)$(VRA_GTAR) --dereference --owner 0 --group 0 --ignore-failed-read -cjRf $@ \
 		-C $(VRA_LNX_ADD_INST_OUT_DIR) \
 		LICENSE bin init lib other sbin src \
 		$(if $(filter $(KBUILD_TYPE),debug),debug)
endif
	$(QUIET)$(CHMOD) 0644 $@


#
# .tar.bz2 containing the debug information
#
$(PATH_STAGE_BIN)/additions/VBoxGuestAdditions-dbg.tar.bz2: \
		$(VRA_LNX_ADD_DBG_FILES) \
		$(VRA_LNX_ADD_INST_DEP_ON_MAKEFILE)
	$(call MSG_L1,Packing $@)
	$(QUIET)$(RM) -f -- $@ $(patsubst %.bz2,%,$@)
	$(QUIET)$(MKDIR) -p $(@D)
	$(QUIET)$(CHMOD) 0755 $(VRA_LNX_ADD_DBG_DIRS)
ifdef VRA_USE_PBZIP2
	$(QUIET)$(VRA_GTAR) --dereference --owner 0 --group 0 -cRf $(patsubst %.bz2,%,$@) \
		-C $(VRA_LNX_ADD_INST_DBG_DIR) \
		bin lib sbin
	$(QUIET)pbzip2 $(patsubst %.bz2,%,$@)
else
	$(QUIET)$(VRA_GTAR) --dereference --owner 0 --group 0 --ignore-failed-read -cjRf $@ \
 		-C $(VRA_LNX_ADD_INST_DBG_DIR) \
 		bin lib sbin
endif
	$(QUIET)$(CHMOD) 0644 $@


#
# Build the Linux Guest Additions self extracting installer.
#
# Note that $(PATH_SUB_CURRENT) was changed by subfooter.kmk above and
# any references should be made via variables assigned a know value via := .
#
$(PATH_STAGE_BIN)/additions/VBoxLinuxAdditions.run: \
		$(VRA_LNX_ADD_ARCHIVES) \
		$(VRA_LNX_ADD_INST_STAGE_DIR)install.sh \
		$$(LnxAdd-scripts_2_STAGE_TARGETS) \
		$(VRA_VERSION_STAMP)
# Remove any archives left over from previous builds so that they don't
# end up in our installer as well.
	$(QUIET)$(RM) -f $(foreach file, $(wildcard $(VRA_LNX_ADD_INST_STAGE_DIR)$(VRA_LNX_ADD_PACKAGE_NAME)-*.tar.bz2), $(file))
	$(QUIET)$(foreach file, $(VRA_LNX_ADD_ARCHIVES), \
		$(CP) -f $(file) $(VRA_LNX_ADD_INST_STAGE_DIR)$(subst -r$(VRA_SVN_REV),,$(notdir $(file)))$(NLTAB) )
	$(QUIET)$(VRA_MAKESELF) --nocomp $(if $(VRA_OSE),,--tar-no-format) $(VRA_LNX_ADD_INST_STAGE_DIR) $@ \
		"VirtualAgent $(VRA_VERSION_STRING) Guest Additions for Linux" \
		/bin/sh ./install.sh "\$$0"
