# $Id: Makefile.kmk 112921 2026-02-10 13:21:34Z knut.osmundsen@oracle.com $
## @file
# Sub-makefile for VBoxDTrace.
#
# Contributed by: bird
#

#
# Copyright (C) 2012-2026 CINASEEK and/or its affiliates.
#
# This file is part of VirtualAgent base platform packages, as
# available from http://www.virtualbox.org.
#
# The contents of this file are subject to the terms of the Common
# Development and Distribution License Version 1.0 (CDDL) only, as it
# comes in the "COPYING.CDDL" file of the VirtualAgent distribution.
#
# SPDX-License-Identifier: CDDL-1.0
#

SUB_DEPTH = ../../../../
include $(KBUILD_PATH)/subheader.kmk


#
# Globals.
#
VRA_EXTPACK_VRADTRACE_NAME         := CINASEEK VBoxDTrace Extension Pack
VRA_EXTPACK_VRADTRACE_MANGLED_NAME := CINASEEK_VBoxDTrace_Extension_Pack
VRA_PATH_EXTPACK_VRADTRACE = $(PATH_STAGE)/$(INST_EXTPACK)$(VRA_EXTPACK_VRADTRACE_MANGLED_NAME)
INST_EXTPACK_VRADTRACE = $(INST_EXTPACK)$(VRA_EXTPACK_VRADTRACE_MANGLED_NAME)/

VRADT_PATH                := $(PATH_ROOT)/src/VBox/ExtPacks/VBoxDTrace
VRADT_PATH_ONNV           := $(VRADT_PATH)/onnv
VRADT_PATH_UTS            := $(VRADT_PATH_ONNV)/uts
VRADT_PATH_CMD            := $(VRADT_PATH_ONNV)/cmd
VRADT_PATH_LIBCTF         := $(VRADT_PATH_ONNV)/lib/libctf
VRADT_PATH_CMN_CTF        := $(VRADT_PATH_ONNV)/common/ctf
VRADT_PATH_LIBDTRACE      := $(VRADT_PATH_ONNV)/lib/libdtrace
VRADT_PATH_CMN_DTRACE     := $(VRADT_PATH_ONNV)/common/dtrace


ifndef VRA_ONLY_EXTPACKS
 #
 # The generic wrapper that selects native or extpack dtrace cmd and adds our
 # library path to the command line.
 #
 # Note! This is not installed as part of the extension pack, but always shipped
 #       with the base VBox installation.
 #
 PROGRAMS += VBoxDTrace
 VBoxDTrace_TEMPLATE := VBoxR3Exe
 VBoxDTrace_SOURCES := VBoxDTraceWrapper.cpp
 VBoxDTrace_LIBS = $(LIB_RUNTIME)
 $(call VRA_SET_VER_INFO_DLL,VBoxDTrace,VirtualAgent DTrace Chooser)
endif


if defined(VRA_WITH_EXTPACK_VRADTRACE) && defined(VRA_WITH_EXTPACK)

 #
 # Extend the extension pack templates.
 #
 TEMPLATE_VBoxR3ExtPackDTrace = For the ring-3 context modules in the VBoxDTrace extension pack.
 TEMPLATE_VBoxR3ExtPackDTrace_EXTENDS = VBoxR3ExtPack
 TEMPLATE_VBoxR3ExtPackDTrace_INST = $(INST_EXTPACK_VRADTRACE)$(KBUILD_TARGET).$(KBUILD_TARGET_ARCH)/
 TEMPLATE_VBoxR3ExtPackDTrace_DEFS = $(TEMPLATE_VBoxR3ExtPack_DEFS) VRA_IN_DTRACE_EXTPACK
 if "$(VRA_VCC_TOOL_STEM)" >= "VCC140"
  # -wd4456: declaration of 'rval' hides previous local declaration
  # -wd4477: 'fprintf' : format string '%02lu' requires an argument of type 'unsigned long', but variadic argument 1 has type 'ulong_t'
  # -wd4457: warning C4457: declaration of 'arg' hides function parameter
  TEMPLATE_VBoxR3ExtPackDTrace_CFLAGS.win = $(TEMPLATE_VBoxR3ExtPack_CFLAGS.win) -wd4456 -wd4477 -wd4457
 endif

 TEMPLATE_VBoxR0ExtPackDTrace = For the ring-0 context modules in the VBoxDTrace extension pack.
 TEMPLATE_VBoxR0ExtPackDTrace_EXTENDS = VBoxR0ExtPack
 TEMPLATE_VBoxR0ExtPackDTrace_INST = $(INST_EXTPACK_VRADTRACE)$(KBUILD_TARGET).$(KBUILD_TARGET_ARCH)/
 TEMPLATE_VBoxR0ExtPackDTrace_DEFS = $(TEMPLATE_VBoxR0ExtPack_DEFS) VRA_IN_DTRACE_EXTPACK

 TEMPLATE_VBoxInsExtPackDTrace = For the install targets for the VBoxDTrace extension pack.
 TEMPLATE_VBoxInsExtPackDTrace_EXTENDS = VBoxR0ExtPack
 TEMPLATE_VBoxInsExtPackDTrace_INST = $(INST_EXTPACK_VRADTRACE)


 #
 # Install the description.
 #
 INSTALLS += VBoxDTraceIns
 VBoxDTraceIns_TEMPLATE = VBoxInsExtPackDTrace
 VBoxDTraceIns_SOURCES = \
 	$(VBoxDTraceIns_0_OUTDIR)/ExtPack.xml \
 	COPYING=>ExtPack-SourceCodeLicense.txt
 $(call VRA_EDIT_VERSION_RULE_FN,VBoxDTraceIns,ExtPack.xml)


 #
 # VBoxDTraceMain - The module which the VirtualAgent Main API talks to.
 #
 DLLS += VBoxDTraceMain
 VBoxDTraceMain_TEMPLATE = VBoxR3ExtPackDTrace
 VBoxDTraceMain_SOURCES = VBoxDTraceMain.cpp
 $(call VRA_SET_VER_INFO_DLL,VBoxDTraceMain,VBoxDTrace Main module)


 #
 # The ring-3 VBoxDTrace command implementation (library).
 #
 ifneq ($(KBUILD_TARGET),solaris) # Temporarily disabled on Solaris (not really needed)...
  DLLS += VBoxDTraceCmd
  VBoxDTraceCmd_TEMPLATE = VBoxR3ExtPackDTrace
  ifdef VRA_WITH_AUTOMATIC_DEFS_QUOTING
   VBoxDTraceCmd_DEFS = RTMEM_WRAP_TO_EF_APIS VRA_EXTPACK_VRADTRACE_MANGLED_NAME="$(VRA_EXTPACK_VRADTRACE_MANGLED_NAME)"
  else
   VBoxDTraceCmd_DEFS = RTMEM_WRAP_TO_EF_APIS VRA_EXTPACK_VRADTRACE_MANGLED_NAME=\"$(VRA_EXTPACK_VRADTRACE_MANGLED_NAME)\"
  endif
  #VBoxDTraceCmd_DEFS += YYDEBUG
  VBoxDTraceCmd_DEFS.linux = _XOPEN_SOURCE=700 _LARGEFILE64_SOURCE
  VBoxDTraceCmd_DEFS.win = YY_USE_PROTOS=1 YYENABLE_NLS=0 YYLTYPE_IS_TRIVIAL=0
  VBoxDTraceCmd_SDKS = VBoxZlib
  ifn1of ($(KBUILD_TARGET), win)
   VBoxDTraceCmd_CFLAGS = -Wno-format $(VRA_GCC_Wno-overlength-strings) -Wno-sign-compare -Wno-strict-prototypes -Wno-missing-prototypes -Wno-missing-declarations -Wno-shadow $(VRA_GCC_Wno-misleading-indentation)
  endif
  VBoxDTraceCmd_INCS = \
  	include \
  	$(VRADT_PATH_UTS)/common \
  	$(VRADT_PATH_LIBCTF)/common \
  	$(VRADT_PATH_LIBDTRACE)/common \
  	$(VRADT_PATH_CMN_CTF)
  VBoxDTraceCmd_SOURCES = \
  	$(VRADT_PATH_CMD)/dtrace/dtrace.c \
  	\
  	$(VRADT_PATH_LIBDTRACE)/common/dt_as.c \
  	$(VRADT_PATH_LIBDTRACE)/common/dt_aggregate.c \
  	$(VRADT_PATH_LIBDTRACE)/common/dt_buf.c \
  	$(VRADT_PATH_LIBDTRACE)/common/dt_cc.c \
  	$(VRADT_PATH_LIBDTRACE)/common/dt_cg.c \
  	$(VRADT_PATH_LIBDTRACE)/common/dt_consume.c \
  	$(VRADT_PATH_LIBDTRACE)/common/dt_decl.c \
  	$(VRADT_PATH_LIBDTRACE)/common/dt_dis.c \
  	$(VRADT_PATH_LIBDTRACE)/common/dt_dof.c \
  	$(VRADT_PATH_LIBDTRACE)/common/dt_error.c \
  	$(VRADT_PATH_LIBDTRACE)/common/dt_handle.c \
  	$(VRADT_PATH_LIBDTRACE)/common/dt_ident.c \
  	$(VRADT_PATH_LIBDTRACE)/common/dt_inttab.c \
  	$(VRADT_PATH_LIBDTRACE)/common/dt_list.c \
  	$(VRADT_PATH_LIBDTRACE)/common/dt_map.c \
  	$(VRADT_PATH_LIBDTRACE)/common/dt_module.c \
  	$(VRADT_PATH_LIBDTRACE)/common/dt_program.c \
  	$(VRADT_PATH_LIBDTRACE)/common/dt_open.c \
  	$(VRADT_PATH_LIBDTRACE)/common/dt_options.c \
  	$(VRADT_PATH_LIBDTRACE)/common/dt_parser.c \
  	$(VRADT_PATH_LIBDTRACE)/common/dt_pcb.c \
  	$(VRADT_PATH_LIBDTRACE)/common/dt_pragma.c \
  	$(VRADT_PATH_LIBDTRACE)/common/dt_printf.c \
  	$(VRADT_PATH_LIBDTRACE)/common/dt_proc.c \
  	$(VRADT_PATH_LIBDTRACE)/common/dt_provider.c \
  	$(VRADT_PATH_LIBDTRACE)/common/dt_regset.c \
  	$(VRADT_PATH_LIBDTRACE)/common/dt_string.c \
  	$(VRADT_PATH_LIBDTRACE)/common/dt_strtab.c \
  	$(VRADT_PATH_LIBDTRACE)/common/dt_subr.c \
  	$(VRADT_PATH_LIBDTRACE)/common/dt_work.c \
  	$(VRADT_PATH_LIBDTRACE)/common/dt_xlator.c \
  	\
  	$(VBoxDTraceCmd_0_OUTDIR)/dt_errtags.c \
  	$(VBoxDTraceCmd_0_OUTDIR)/dt_names.c \
  	\
  	$(VRADT_PATH_CMN_CTF)/ctf_create.c \
  	$(VRADT_PATH_CMN_CTF)/ctf_error.c \
  	$(VRADT_PATH_CMN_CTF)/ctf_decl.c \
  	$(VRADT_PATH_CMN_CTF)/ctf_hash.c \
  	$(VRADT_PATH_CMN_CTF)/ctf_labels.c \
  	$(VRADT_PATH_CMN_CTF)/ctf_lookup.c \
  	$(VRADT_PATH_CMN_CTF)/ctf_open.c \
  	$(VRADT_PATH_CMN_CTF)/ctf_types.c \
  	$(VRADT_PATH_CMN_CTF)/ctf_util.c \
  	\
  	$(VRADT_PATH_LIBCTF)/common/ctf_subr.c \
  	$(VRADT_PATH_LIBCTF)/common/ctf_lib.c

  # Source not used or wanted:
  #	$(VRADT_PATH_LIBDTRACE)/common/dt_link.c
  #	$(VRADT_PATH_LIBDTRACE)/common/dt_pid.c

  # Generate sources
  VBoxDTraceCmd_CLEAN = \
  	$(VBoxDTraceCmd_0_OUTDIR)/dt_errtags.c \
  	$(VBoxDTraceCmd_0_OUTDIR)/dt_names.c

  $$(VBoxDTraceCmd_0_OUTDIR)/dt_errtags.c: \
  		$(VRADT_PATH_LIBDTRACE)/common/dt_errtags.h \
  		$(VRADT_PATH_LIBDTRACE)/common/mkerrtags.sed \
  		| $$(dir $$@)
	$(MSG_GENERATE,VBoxDTraceCmd,$@,$<)
	$(SED) -n -f $(VRADT_PATH_LIBDTRACE)/common/mkerrtags.sed --output $@ $<

  $$(VBoxDTraceCmd_0_OUTDIR)/dt_names.c: \
  		$(VRADT_PATH_UTS)/common/sys/dtrace.h \
  		$(VRADT_PATH_LIBDTRACE)/common/mknames.sed \
  		| $$(dir $$@)
	$(MSG_GENERATE,VBoxDTraceCmd,$@,$<)
	$(SED) -n -f $(VRADT_PATH_LIBDTRACE)/common/mknames.sed --output $@ $<

  ifdef VRA_HAVE_BISON
   USES                  += yacc
   VBoxDTraceCmd_USES    += yacc
   VBoxDTraceCmd_YACCTOOL = BISON
   VBoxDTraceCmd_YACCFLAGS = -d -y
   VBoxDTraceCmd_SOURCES += \
   	$(VRADT_PATH_LIBDTRACE)/common/dt_grammar.y
   VBoxDTraceCmd_INCS    += $(VBoxDTraceCmd_0_OUTDIR)/src/VBox/ExtPacks/VBoxDTrace/onnv/lib/libdtrace/common
  else
   VBoxDTraceCmd_SOURCES += \
   	$(VRADT_PATH)/generated/dt_grammar.c
   VBoxDTraceCmd_INCS    += \
   	$(VRADT_PATH)/generated/
  endif

  ifdef VRA_HAVE_FLEX
   USES                  += lex
   VBoxDTraceCmd_USES    += lex
   VBoxDTraceCmd_LEXTOOL  = FLEX
   VBoxDTraceCmd_LEXFLAGS = -l -B #-d -T
   VBoxDTraceCmd_SOURCES += \
   	$(VRADT_PATH_LIBDTRACE)/common/dt_lex.l
  else
   VBoxDTraceCmd_SOURCES += \
   	$(VRADT_PATH)/generated/dt_lex.c
  endif
  ifeq ($(KBUILD_HOST),linux)
   if $(VRA_GCC_VERSION_CXX) >= 70000
    VBoxDTraceCmd_CFLAGS += -Wno-implicit-fallthrough
   endif
  endif
  VBoxDTraceCmd_DEFS     += USING_FLEX
  $(call VRA_SET_VER_INFO_DLL,VBoxDTraceCmd,VBoxDTrace Command Implementation)

  #
  # Updates the sources generated by flex and biosn.
  # The SED processing removes the paths the from #line statements.
  #
  vboxdtrace-update-generated-sources: \
  		$$(VBoxDTraceCmd_0_OUTDIR)/src/VBox/ExtPacks/VBoxDTrace/onnv/lib/libdtrace/common/dt_grammar.c \
  		$$(VBoxDTraceCmd_0_OUTDIR)/src/VBox/ExtPacks/VBoxDTrace/onnv/lib/libdtrace/common/dt_grammar.h \
  		$$(VBoxDTraceCmd_0_OUTDIR)/src/VBox/ExtPacks/VBoxDTrace/onnv/lib/libdtrace/common/dt_lex.c
	$(foreach file,dt_grammar.c dt_grammar.h dt_lex.c \
		,$(NLTAB)$(SED)  -e 's,$(VRADT_PATH_LIBDTRACE)/common/,,g'\
 		-e 's,$(VBoxDTraceCmd_0_OUTDIR)/src/VBox/ExtPacks/VBoxDTrace/onnv/lib/libdtrace/common/,,g' \
 		--output $(VRADT_PATH)/generated/$(file) \
 		$(VBoxDTraceCmd_0_OUTDIR)/src/VBox/ExtPacks/VBoxDTrace/onnv/lib/libdtrace/common/$(file))
 endif # Temporarily disabled on Solaris.

 #
 # The ring-0 part of VBoxDTrace.
 #
 ifneq ($(KBUILD_TARGET),solaris) # disabled on solaris - neiter needed nor currently able to build it here.
  $(if-expr defined(VRA_WITH_VRAR0_AS_DLL),DLLS,SYSMODS) += VBoxDTraceR0
 endif
 VBoxDTraceR0_TEMPLATE = VBoxR0ExtPackDTrace
 VBoxDTraceR0_DEFS = IN_VRADTRACE_R0 IN_RT_R0
 ifeq ($(VRA_LDR_FMT),elf)
  VBoxDTraceR0_LDFLAGS = -e ModuleInit
 endif
 VBoxDTraceR0_INCS = \
 	include \
 	$(VRADT_PATH_UTS)/common
 VBoxDTraceR0_SOURCES = \
 	VBoxDTraceR0.cpp \
 	$(VRADT_PATH_UTS)/common/dtrace/dtrace.c
 VBoxDTraceR0_SOURCES.amd64 = \
 	VBoxDTraceR0A.asm
 VBoxDTraceR0_SOURCES.x86 = \
 	VBoxDTraceR0A.asm
 VBoxDTraceR0_SOURCES.arm64 = \
 	VBoxDTraceR0A-arm64.S
 VBoxDTraceR0_LIBS = \
 	$(PATH_STAGE_LIB)/RuntimeR0$(VRA_SUFF_LIB) \
 	$(VRA_LIB_SUPR0)
 $(call VRA_SET_VER_INFO_R0,VBoxDTraceR0,VBoxDTrace Core (ring-0))


 #
 # Packing.
 #
 ifndef VRA_WITHOUT_EXTPACK_VRADTRACE_PACKING
  PACKING += $(VRA_PATH_PACKAGES)/$(VRA_EXTPACK_VRADTRACE_MANGLED_NAME)-$(VRA_VERSION_STRING)r$(VRA_SVN_REV).vbox-extpack
 endif

 ifndef VRA_WITH_EXTPACK_OS_ARCHS
  ifeq ($(USER),bird) # for now
   VRA_WITH_EXTPACK_OS_ARCHS = $(KBUILD_TARGET).$(KBUILD_TARGET_ARCH)
  endif
 endif

 # Build the file list.  The macro takes 1=darwin.x86, 2=dist/VirtualAgent.app/Contents/MacOS, 3=dylib
 VRA_VRADTRACE_FILES_MACRO = \
 	$(PATH_OUT_BASE)/$(1)/$(KBUILD_TYPE)/$(2)/ExtensionPacks/$(VRA_EXTPACK_VRADTRACE_MANGLED_NAME)/$(1)/VBoxDTraceMain.$(3)=>$(1)/VBoxDTraceMain.$(3) \
 	$(if $(intersects $1, solaris.x86 solaris.amd64),, \
 		$(PATH_OUT_BASE)/$(1)/$(KBUILD_TYPE)/$(2)/ExtensionPacks/$(VRA_EXTPACK_VRADTRACE_MANGLED_NAME)/$(1)/VBoxDTraceCmd.$(3)=>$(1)/VBoxDTraceCmd.$(3) \
 		$(PATH_OUT_BASE)/$(1)/$(KBUILD_TYPE)/$(2)/ExtensionPacks/$(VRA_EXTPACK_VRADTRACE_MANGLED_NAME)/$(1)/VBoxDTraceR0.r0=>$(1)/VBoxDTraceR0.r0 \
 		)

 VRA_VRADTRACE_FILES := \
 	$(VRA_PATH_EXTPACK_VRADTRACE)/ExtPack.xml=>ExtPack.xml \
 	$(VRA_PATH_EXTPACK_VRADTRACE)/ExtPack-SourceCodeLicense.txt=>ExtPack-SourceCodeLicense.txt

 if1of (darwin.amd64, $(VRA_WITH_EXTPACK_OS_ARCHS))
  VRA_VRADTRACE_FILES += $(call VRA_VRADTRACE_FILES_MACRO,darwin.amd64,dist/VirtualAgent.app/Contents/MacOS,dylib)
 endif
 if1of (darwin.x86, $(VRA_WITH_EXTPACK_OS_ARCHS))
  VRA_VRADTRACE_FILES += $(call VRA_VRADTRACE_FILES_MACRO,darwin.x86,dist/VirtualAgent.app/Contents/MacOS,dylib)
 endif
 if1of (freebsd.amd64, $(VRA_WITH_EXTPACK_OS_ARCHS))
  VRA_VRADTRACE_FILES += $(call VRA_VRADTRACE_FILES_MACRO,freebsd.amd64,bin,so)
 endif
 if1of (freebsd.x86, $(VRA_WITH_EXTPACK_OS_ARCHS))
  VRA_VRADTRACE_FILES += $(call VRA_VRADTRACE_FILES_MACRO,freebsd.x86,bin,so)
 endif
 if1of (linux.amd64, $(VRA_WITH_EXTPACK_OS_ARCHS))
  VRA_VRADTRACE_FILES += $(call VRA_VRADTRACE_FILES_MACRO,linux.amd64,bin,so)
 endif
 if1of (linux.x86, $(VRA_WITH_EXTPACK_OS_ARCHS))
  VRA_VRADTRACE_FILES += $(call VRA_VRADTRACE_FILES_MACRO,linux.x86,bin,so)
 endif
 if1of (os2.x86, $(VRA_WITH_EXTPACK_OS_ARCHS))
  VRA_VRADTRACE_FILES += $(call VRA_VRADTRACE_FILES_MACRO,os2.x86,bin,so)
 endif
 if1of (solaris.amd64, $(VRA_WITH_EXTPACK_OS_ARCHS))
  VRA_VRADTRACE_FILES += $(call VRA_VRADTRACE_FILES_MACRO,solaris.amd64,bin,so)
 endif
 if1of (solaris.x86, $(VRA_WITH_EXTPACK_OS_ARCHS))
  VRA_VRADTRACE_FILES += $(call VRA_VRADTRACE_FILES_MACRO,solaris.x86,bin,so)
 endif
 if1of (win.amd64, $(VRA_WITH_EXTPACK_OS_ARCHS))
  VRA_VRADTRACE_FILES += $(call VRA_VRADTRACE_FILES_MACRO,win.amd64,bin,dll)
 endif
 if1of (win.x86, $(VRA_WITH_EXTPACK_OS_ARCHS))
  VRA_VRADTRACE_FILES += $(call VRA_VRADTRACE_FILES_MACRO,win.x86,bin,dll)
 endif

 # Pack it all up using a temporary staging directory.
 $(VRA_PATH_PACKAGES)/$(VRA_EXTPACK_VRADTRACE_MANGLED_NAME)-$(VRA_VERSION_STRING)r$(VRA_SVN_REV).vbox-extpack: \
 		$$(foreach file, $$(VRA_VRADTRACE_FILES), $$(firstword $$(subst =>,$$(SP),$$(file)))) \
 		| $(VRA_PATH_PACKAGES)/
	$(RM) -f $(wildcard $(VRA_PATH_PACKAGES)/$(VRA_EXTPACK_VRADTRACE_MANGLED_NAME)-*.vbox-extpack) \
		$(VBoxDTraceIns_0_OUTDIR)/ExtPack.manifest \
		$(VBoxDTraceIns_0_OUTDIR)/ExtPack.signature
 # Stage all the files
	$(RM) -Rf $(VBoxDTraceIns_0_OUTDIR)/Stage/
	$(foreach file, $(VRA_VRADTRACE_FILES),\
		$(NLTAB)$(MKDIR) -p $(dir $(lastword $(subst =>,$(SP)$(VBoxDTraceIns_0_OUTDIR)/Stage/,$(file)))) \
		$(NLTAB)$(CP) $(subst =>,$(SP)$(VBoxDTraceIns_0_OUTDIR)/Stage/,$(file)) )
 # Create the manifest
	$(VRA_RTMANIFEST) \
		--manifest $(VBoxDTraceIns_0_OUTDIR)/Stage/ExtPack.manifest \
		--chdir $(VBoxDTraceIns_0_OUTDIR)/Stage/ \
		$(foreach file, $(VRA_VRADTRACE_FILES), $(lastword $(subst =>,$(SP),$(file))))
	$(APPEND) $(VBoxDTraceIns_0_OUTDIR)/Stage/ExtPack.signature "todo"
	$(CHMOD) a+r \
		$(VBoxDTraceIns_0_OUTDIR)/Stage/ExtPack.manifest \
		$(VBoxDTraceIns_0_OUTDIR)/Stage/ExtPack.signature
 # Tar it up.
 if 0
	tar -cvf - -C $(VBoxDTraceIns_0_OUTDIR)/Stage/ . | gzip -9c > $@
 else
	$(VRA_RTTAR) -cvf "$@" $(VRA_RTTAR_EXTPACK_OPTS) -C "$(VBoxDTraceIns_0_OUTDIR)/Stage/" .
 endif
 # Clean up
	$(RM) -Rf $(VBoxDTraceIns_0_OUTDIR)/Stage/

 BLDDIRS += $(VRA_PATH_PACKAGES)/

endif # VRA_WITH_EXTPACK_VRADTRACE


include $(FILE_KBUILD_SUB_FOOTER)

