# $Id: Makefile.kmk 112403 2026-01-11 19:29:08Z knut.osmundsen@oracle.com $
## @file
# Sub-Makefile for VBoxNine D3D9 state tracker.
#

#
# Copyright (C) 2016-2026 CINASEEK and/or its affiliates.
#
# This file is part of VirtualAgent base platform packages, as
# available from https://www.virtualbox.org.
#
# This program is free software; you can redistribute it and/or
# modify it under the terms of the GNU General Public License
# as published by the Free Software Foundation, in version 3 of the
# License.
#
# This program is distributed in the hope that it will be useful, but
# WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
# General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, see <https://www.gnu.org/licenses>.
#
# SPDX-License-Identifier: GPL-3.0-only
#

SUB_DEPTH = ../../../../../..
include $(KBUILD_PATH)/subheader.kmk

DLLS       += VBoxNine
DLLS.amd64 += VBoxNine-x86

VBoxNine_TEMPLATE = VBoxMesa3DGuestR3DllMinVista
if $(VRA_MESA_V_MAJOR) >= 24
 VBoxNine_DEFS     = \
 	VRA_MESA_STATIC_DRIVER
endif
#  -wd4100: unreferenced formal parameter
#  -wd4200: nonstandard extension used : zero-sized array in struct/union
#  -wd4245: 'return' : conversion from 'int' to 'unsigned int', signed/unsigned mismatch
#  -wd4255: no function prototype given
#  -wd4668: 'something' is not defined as a preprocessor macro, replacing with '0' for '#if/#elif'
VBoxNine_CFLAGS   = -wd4100 -wd4200 -wd4245 -wd4255 -wd4668
VBoxNine_INCS     = \
	$(VRA_PATH_MESA)/src/gallium/frontends/nine
if $(VRA_MESA_V_MAJOR) >= 24
 VBoxNine_INCS    += \
 	$(VRA_PATH_3D)/win/include \
 	$(VRA_PATH_3D)/win/VBoxSVGA \
 	$(VRA_PATH_MESA)/src/gallium/drivers/svga \
 	$(VRA_PATH_MESA)/src/gallium/drivers/svga/include \
 	$(VRA_PATH_MESA)/src/gallium/winsys/svga/drm
endif
VBoxNine_SOURCES  = \
	nine/nine_memory_helper.c \
	VBoxNine.c \
	VBoxNine.rc
if $(VRA_MESA_V_MAJOR) < 24
 VBoxNine_SOURCES += \
 	VBoxNine.def
else
 VBoxNine_SOURCES += \
 	VBoxNine_static_drv.def \
 	../VBoxSVGA/VBoxSVGA.c \
 	../VBoxSVGA/winsys/vmw_screen.c \
 	../VBoxSVGA/winsys/vmw_screen_wddm.c \
 	../VBoxSVGA/winsys/vmw_screen_ioctl.c
endif
VBoxNine_LIBS     = \
	$(VRA_PATH_ADDITIONS_LIB)/VBoxMesaGalliumAuxLib$(VRA_SUFF_LIB) \
	$(VRA_PATH_ADDITIONS_LIB)/VBoxMesaLib$(VRA_SUFF_LIB) \
	$(VRA_PATH_ADDITIONS_LIB)/VBoxMesaUtilLib$(VRA_SUFF_LIB) \
	$(VRA_PATH_ADDITIONS_LIB)/VBoxMesaNineLib$(VRA_SUFF_LIB) \
	$(VRA_PATH_ADDITIONS_LIB)/VBoxWddmUmHlp$(VRA_SUFF_LIB)
if $(VRA_MESA_V_MAJOR) >= 24
 VBoxNine_LIBS    += \
 	$(VRA_PATH_ADDITIONS_LIB)/VBoxMesaSVGAWinsysLib$(VRA_SUFF_LIB) \
 	$(VRA_PATH_ADDITIONS_LIB)/VBoxMesaSVGALib$(VRA_SUFF_LIB)
endif

if defined(VRA_SIGNING_MODE) && defined(VRA_SIGN_ADDITIONS)
 VBoxNine_INSTTYPE       = none
 VBoxNine_DEBUG_INSTTYPE = both
endif

#
# VBoxNine-x86 - x86 version of VBoxNine built for amd64 build
#
VBoxNine-x86_EXTENDS      = VBoxNine
VBoxNine-x86_BLD_TRG_ARCH = x86
VBoxNine-x86_LIBS         = \
	$(VRA_PATH_ADDITIONS_LIB)/VBoxWddmUmHlp-x86$(VRA_SUFF_LIB) \
	$(VRA_PATH_ADDITIONS_LIB)/VBoxMesaGalliumAuxLib-x86$(VRA_SUFF_LIB) \
	$(VRA_PATH_ADDITIONS_LIB)/VBoxMesaLib-x86$(VRA_SUFF_LIB) \
	$(VRA_PATH_ADDITIONS_LIB)/VBoxMesaUtilLib-x86$(VRA_SUFF_LIB) \
	$(VRA_PATH_ADDITIONS_LIB)/VBoxMesaNineLib-x86$(VRA_SUFF_LIB)
if $(VRA_MESA_V_MAJOR) >= 24
 VBoxNine-x86_LIBS    += \
 	$(VRA_PATH_ADDITIONS_LIB)/VBoxMesaSVGAWinsysLib-x86$(VRA_SUFF_LIB) \
 	$(VRA_PATH_ADDITIONS_LIB)/VBoxMesaSVGALib-x86$(VRA_SUFF_LIB)
endif
VBoxNine-x86_DEFS         = $(VBoxNine_DEFS) VRA_WOW64

include $(FILE_KBUILD_SUB_FOOTER)

