# $Id: Makefile.kmk 112403 2026-01-11 19:29:08Z knut.osmundsen@oracle.com $
## @file
# Sub-Makefile for VBoxInstallHelper.dll.
#

#
# Copyright (C) 2008-2026 CINASEEK and/or its affiliates.
#
# This file is part of VirtualAgent base platform packages, as
# available from https://www.virtualbox.org.
#
# This program is free software; you can redistribute it and/or
# modify it under the terms of the GNU General Public License
# as published by the Free Software Foundation, in version 3 of the
# License.
#
# This program is distributed in the hope that it will be useful, but
# WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
# General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, see <https://www.gnu.org/licenses>.
#
# SPDX-License-Identifier: GPL-3.0-only
#

SUB_DEPTH = ../../../../..
include $(KBUILD_PATH)/subheader.kmk


DLLS += VBoxInstallHelper
VBoxInstallHelper_TEMPLATE = VBoxR3StaticDllNoAsan
VBoxInstallHelper_SDKS     = ReorderCompilerIncs $(VRA_WINPSDK) $(VRA_WINDDK)
VBoxInstallHelper_DEFS     = _WIN32_WINNT=0x0501 _UNICODE UNICODE VRA_SVN_REV=$(VRA_SVN_REV)
if defined(VRA_WITH_NETFLT) || defined(VRA_WITH_NETADP)
 VBoxInstallHelper_SDKS   += VBoxWinNewDevLib
 VBoxInstallHelper_DEFS   += \
 	$(if $(VRA_WITH_NETFLT),VRA_WITH_NETFLT,) \
 	$(if $(VRA_WITH_NETADP),VRA_WITH_NETADP,)
 VBoxInstallHelper_LIBS   += \
 	$(PATH_STAGE_LIB)/WinNetConfigSharedStatic.lib \
 	$(PATH_STAGE_LIB)/VBoxDrvCfgSharedStatic.lib \
 	$(PATH_TOOL_$(VRA_VCC_TOOL)_LIB)/comsupp.lib \
 	$(PATH_SDK_$(VRA_WINPSDK)_LIB)/WbemUuid.Lib
endif
VBoxInstallHelper_DEPS     = $(VRA_SVN_REV_KMK)
VBoxInstallHelper_SOURCES  = \
	VBoxInstallHelper.cpp \
	VBoxInstallHelper.def \
	VBoxInstallHelper.rc \
	VBoxCommon.cpp \
	$(PATH_ROOT)/src/VBox/GuestHost/installation/VBoxWinDrvCommon.cpp \
	$(PATH_ROOT)/src/VBox/GuestHost/installation/VBoxWinDrvInst.cpp \
	$(PATH_ROOT)/src/VBox/GuestHost/installation/VBoxWinDrvStore.cpp
VBoxInstallHelper_INCS    += \
	$(PATH_ROOT)/src/VBox/GuestHost/installation
ifndef VRA_OSE
 VBoxInstallHelper_SOURCES += \
 	internal/VBoxSerial.cpp
endif
VBoxInstallHelper_LIBS += \
	$(PATH_SDK_$(VRA_WINPSDK)_LIB)/Msi.lib

if "$(KBUILD_TARGET)" == "win" && defined(VRA_WITH_TESTCASES) && !defined(VRA_OSE)
 include $(PATH_SUB_CURRENT)/testcase/Makefile.kmk
endif

include $(FILE_KBUILD_SUB_FOOTER)

